import { applicationRouteHref } from './applicationRouteHref'
import {SafeMarkdown} from '../../ui/SafeMarkdown'
import React,{useEffect,useRef,useState}from'react'
import{useSearchParams}from'react-router-dom'
import type{ApplicationDensity,ApplicationPresentation,ArtifactContent,EffectiveApplicationInstance,ExactArtifactRef,MalleableShellClient,PersonalEnvironmentOverrides,PersonalEnvironmentPreview,PersonalEnvironmentRevision,ShellCommandDescriptor,ShellCommandResult}from'../../services/contracts'
import{useStore}from'../../data/store'
import{EmptyState}from'../../ui/EmptyState'
import{getSurface,registerSurface}from'../../surfaces/registry'
import{SandboxApplicationHost}from'../../applications/SandboxApplicationHost'
import{reportAnnotatorV1,reportAnnotatorV2}from'../../applications/fixturePackages'
import type{ExecutableRendererManifest}from'../../applications/executableApplication'
import{CanonicalRendererLifecycle}from'../../applications/CanonicalRendererLifecycle'

void React
export const builtInEvidenceApplication={applicationId:'review.evidence',instanceId:'review-main'} as const
type Handoff={projectId:string;runId:string;artifactId:string;digest:string;commandId:string;commandVersion:number;descriptorDigest:string;invocationId:string;origin:string}
type State={kind:'loading'}|{kind:'error';reason:string}|{kind:'ready';key:string;client:MalleableShellClient;resource:ExactArtifactRef;descriptor:ShellCommandDescriptor;content:ArtifactContent;invocation?:ShellCommandResult}
const sameResource=(a:ExactArtifactRef,b:ExactArtifactRef)=>a.project_id===b.project_id&&a.run_id===b.run_id&&a.artifact_id===b.artifact_id&&a.digest===b.digest
const handoffKey=(h:Handoff)=>[h.projectId,h.runId,h.artifactId,h.digest,h.commandId,h.commandVersion,h.descriptorDigest,h.invocationId].join('\u0000')
const executableFixtureEnabled=()=>Boolean((import.meta as ImportMeta&{env?:{DEV?:boolean}}).env?.DEV)&&typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('applicationFixture')==='1'
const clientKeys=new WeakMap<object,string>();const connectionKey=(client:object)=>{let key=clientKeys.get(client);if(!key){key=crypto.randomUUID();clientKeys.set(client,key)}return key}
function ExecutableFixtureView({client,resource,content}:{client:MalleableShellClient;resource:ExactArtifactRef;content:ArtifactContent}){const[manifest,setManifest]=useState<ExecutableRendererManifest>(reportAnnotatorV1),[previous,setPrevious]=useState<ExecutableRendererManifest>(),[enabled,setEnabled]=useState(false);const replace=(next:ExecutableRendererManifest)=>{setPrevious(manifest);setManifest(next)};return <section className="cc-panel"><span className="eyebrow">Executable application fixture</span><h2>Report annotator</h2><p>This exact local package exercises the isolated application runtime. Canonical package activation remains unavailable until Core advertises the renderer contribution.</p><div className="page-actions"><button className="secondary-btn" onClick={()=>setEnabled(value=>!value)}>{enabled?'Close application':'Open fixture application'}</button>{enabled&&manifest.package_ref.version==='1.0.0'&&<button className="secondary-btn" onClick={()=>replace(reportAnnotatorV2)}>Replace with v2</button>}{enabled&&manifest.package_ref.version==='2.0.0'&&<button className="secondary-btn" onClick={()=>replace(reportAnnotatorV1)}>Revert to v1</button>}</div>{enabled&&<SandboxApplicationHost manifest={manifest} previousManifest={previous} contentUrl={`${import.meta.env.BASE_URL}application-fixtures/${manifest.entry_file}`} connectionKey={connectionKey(client)} projection={{resource,text:content.text,verified_bytes:true,fact_verification:'not_verified'}}/>}</section>}

function DesktopCanonicalRenderer({client,resource,content}:{client:MalleableShellClient;resource:ExactArtifactRef;content:ArtifactContent}){if(typeof window==='undefined'||!window.opensaddleDesktop)return null;return <CanonicalRendererLifecycle client={client} resource={resource} connectionKey={connectionKey(client)} projection={{resource,text:content.text,verified_bytes:true,fact_verification:'not_verified'}}/>}

function PersonalPresentationSettings({client,projectId,onEffective}:{client:MalleableShellClient;projectId:string;onEffective:(value?:EffectiveApplicationInstance)=>void}){
  const[state,setState]=useState<{kind:'loading'}|{kind:'error';reason:string}|{kind:'ready';personal:PersonalEnvironmentRevision;instance:EffectiveApplicationInstance;density:ApplicationDensity;presentation:ApplicationPresentation;preview?:PersonalEnvironmentPreview;error?:string;pending?:boolean}>({kind:'loading'});const generation=useRef(0),busy=useRef(false)
  useEffect(()=>{const current=++generation.current;busy.current=false;setState({kind:'loading'});onEffective(undefined);if(!client.personalEnvironment){setState({kind:'error',reason:'Personal presentation settings are unavailable from this server.'});return}void client.personalEnvironment(projectId).then(personal=>{if(current!==generation.current)return;const instance=personal.effective_instances.find(item=>item.instance_id===builtInEvidenceApplication.instanceId&&item.application_id===builtInEvidenceApplication.applicationId);if(!instance){setState({kind:'error',reason:'This evidence application has no registered personal presentation instance.'});return}onEffective(instance);setState({kind:'ready',personal,instance,density:instance.effective.density,presentation:instance.effective.presentation})},reason=>{if(current===generation.current)setState({kind:'error',reason:reason instanceof Error?reason.message:String(reason)})});return()=>{generation.current++;busy.current=false;onEffective(undefined)}},[client,projectId,onEffective])
  if(state.kind==='loading')return <section className="cc-panel" aria-busy="true"><span className="eyebrow">My presentation</span><p>Loading your saved application view…</p></section>
  if(state.kind==='error')return <section className="cc-unavailable"><div><h2>Personal presentation unavailable</h2></div><p>{state.reason}</p></section>
  const overrides=():PersonalEnvironmentOverrides=>({instances:{...state.personal.overrides.instances,[state.instance.instance_id]:{...state.personal.overrides.instances[state.instance.instance_id],density:state.density,presentation:state.presentation}}})
  const act=async(kind:'preview'|'apply'|'revert')=>{if(busy.current)return;const current=generation.current;busy.current=true;setState(value=>value.kind==='ready'?{...value,error:undefined,pending:true}:value);try{if(kind==='preview'){if(!client.previewPersonalEnvironment)throw Error('Personal change checking is unavailable from this server.');const preview=await client.previewPersonalEnvironment(projectId,state.personal.revision,overrides(),'Check my evidence presentation');if(current!==generation.current)return;setState(value=>value.kind==='ready'?{...value,preview,pending:false}:value)}else if(kind==='apply'){if(!client.applyPersonalEnvironment||!state.preview?.activatable)throw Error('Check these changes before saving them.');const personal=await client.applyPersonalEnvironment(projectId,state.personal.revision,overrides(),'Save my evidence presentation',state.preview.base_environment_revision,state.preview.base_definition_digest);if(current!==generation.current)return;const instance=personal.effective_instances.find(item=>item.instance_id===state.instance.instance_id);if(!instance)throw Error('The application instance became unavailable.');onEffective(instance);setState({kind:'ready',personal,instance,density:instance.effective.density,presentation:instance.effective.presentation})}else{if(!client.revertPersonalEnvironment||state.personal.parent_revision===null)throw Error('No previous personal revision is available.');const personal=await client.revertPersonalEnvironment(projectId,state.personal.revision,state.personal.parent_revision,'Restore my previous presentation');if(current!==generation.current)return;const instance=personal.effective_instances.find(item=>item.instance_id===state.instance.instance_id);if(!instance)throw Error('The application instance became unavailable.');onEffective(instance);setState({kind:'ready',personal,instance,density:instance.effective.density,presentation:instance.effective.presentation})}}catch(reason){if(current===generation.current)setState(value=>value.kind==='ready'?{...value,pending:false,error:reason instanceof Error?reason.message:String(reason)}:value)}finally{if(current===generation.current)busy.current=false}}
  const change=<K extends'density'|'presentation'>(key:K,value:K extends'density'?ApplicationDensity:ApplicationPresentation)=>{if(busy.current)return;setState(current=>current.kind==='ready'?{...current,[key]:value,preview:undefined,error:undefined}:current)}
  return <section className="cc-panel"><span className="eyebrow">My presentation</span><h2>Evidence view</h2><p>These display preferences belong to your account. Shared application defaults remain unchanged.</p><div className="review-control-grid"><label>Density<select disabled={state.pending} value={state.density} onChange={event=>change('density',event.target.value as ApplicationDensity)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label>Layout<select disabled={state.pending} value={state.presentation} onChange={event=>change('presentation',event.target.value as ApplicationPresentation)}><option value="document">Document</option><option value="split">Split report and evidence</option><option value="focus">Focused report</option></select></label></div><div className="page-actions"><button className="secondary-btn" disabled={state.pending} onClick={()=>act('preview')}>Check changes</button><button className="primary-btn" disabled={state.pending||!state.preview?.activatable} onClick={()=>act('apply')}>Save for me</button>{state.personal.parent_revision!==null&&<button className="secondary-btn" disabled={state.pending} onClick={()=>act('revert')}>Restore previous</button>}</div>{state.preview&&<p role="status">Changes checked against personal revision {state.preview.base_revision}. Saving will update this application instance only.</p>}{state.personal.conflicts.length>0&&<p role="alert">Saved settings conflict with unavailable instances: {state.personal.conflicts.join(', ')}.</p>}{state.error&&<p role="alert">{state.error}</p>}<details><summary>Shared defaults</summary><p>{state.instance.defaults.density} density · {state.instance.defaults.presentation} layout · order {state.instance.defaults.order}</p><p>Personal revision {state.personal.revision} over shared environment revision {state.personal.base_environment_revision}.</p></details></section>
}

export function ArtifactEvidenceSurface({client,handoff}:{client?:MalleableShellClient;handoff:Handoff}){
  const[state,setState]=useState<State>({kind:'loading'});const generation=useRef(0);const[effective,setEffective]=useState<EffectiveApplicationInstance>();const updateEffective=React.useCallback((value?:EffectiveApplicationInstance)=>setEffective(value),[])
  useEffect(()=>{const current=++generation.current;setState({kind:'loading'});if(!client?.content){setState({kind:'error',reason:'Artifact bytes are unavailable from this server.'});return}const expected:ExactArtifactRef={project_id:handoff.projectId,run_id:handoff.runId,artifact_id:handoff.artifactId,digest:handoff.digest};void Promise.all([client.artifacts(handoff.runId,handoff.projectId),client.commands(handoff.projectId),handoff.invocationId?client.invocation(handoff.invocationId):Promise.resolve(undefined)]).then(async([resources,commands,invocation])=>{if(current!==generation.current)return;const resource=resources.find(item=>sameResource(item,expected));const descriptor=commands.find(item=>item.command_id===handoff.commandId&&item.version===handoff.commandVersion&&item.descriptor_digest===handoff.descriptorDigest);if(!resource)throw Error('The exact artifact is missing, changed, or no longer authorized.');if(!descriptor||!descriptor.available.available)throw Error(descriptor?.available.reason??'The originating command descriptor is stale or unavailable.');if(invocation&&(!sameResource(invocation.resource,resource)||invocation.command_id!==descriptor.command_id||invocation.version!==descriptor.version||invocation.descriptor_digest!==descriptor.descriptor_digest))throw Error('The durable invocation no longer matches this exact resource and command authority.');const content=await client.content!(resource);if(current!==generation.current)return;if(content.digest!==resource.digest.replace(/^sha256:/,'').toLowerCase())throw Error('artifact_content_integrity_denied');setState({kind:'ready',key:handoffKey(handoff),client,resource,descriptor,content,invocation})}).catch(reason=>{if(current===generation.current)setState({kind:'error',reason:reason instanceof Error?reason.message:String(reason)})});return()=>{generation.current++}},[client,handoff.projectId,handoff.runId,handoff.artifactId,handoff.digest,handoff.commandId,handoff.commandVersion,handoff.descriptorDigest,handoff.invocationId])
  if(state.kind==='ready'&&(state.client!==client||state.key!==handoffKey(handoff)))return <main className="content-page cc-page" aria-busy="true"><p role="status">Reauthorizing the exact artifact at the destination…</p></main>
  if(state.kind==='loading')return <main className="content-page cc-page" aria-busy="true"><p role="status">Reauthorizing the exact artifact at the destination…</p></main>
  if(state.kind==='error')return <main className="content-page cc-page"><EmptyState role="alert" title="Evidence application unavailable" description={state.reason}/></main>
  const back=new URLSearchParams({project:handoff.projectId,run:handoff.runId,artifact:handoff.artifactId,digest:handoff.digest,...(state.invocation?{invocation:state.invocation.invocation_id}:{})})
  const summary=state.content.text.split(/\r?\n/).map(line=>line.replace(/^#+\s*/, '').trim()).find(Boolean)??'Artifact report'
  return <main className={`content-page cc-page artifact-evidence-view artifact-evidence-view--${effective?.effective.presentation??'document'} artifact-evidence-view--${effective?.effective.density??'comfortable'}`}><header className="cc-header"><div><span className="eyebrow">Independent application</span><h1>{summary}</h1><p>Authenticated artifact report · exact bytes verified against the recorded digest.</p></div><a className="cc-text-link" href={applicationRouteHref('review', back)}>Return to review workspace</a></header>
    <div className="artifact-evidence-primary"><section className="cc-panel artifact-evidence-report"><span className="eyebrow">Report</span><SafeMarkdown text={state.content.text} omitLeadingHeading/></section>
    <section className="cc-panel artifact-evidence-source"><span className="eyebrow">Evidence</span><h2>Source and freshness</h2><p>Read from the authenticated Core artifact endpoint for this exact Run. Integrity verified now against the recorded SHA-256 digest.</p>{state.resource.created_at&&<p>Artifact recorded <time dateTime={state.resource.created_at}>{new Date(state.resource.created_at).toLocaleString()}</time>.</p>}<p>{state.content.sizeBytes.toLocaleString()} bytes · {state.content.mediaType}</p></section></div>
    {state.invocation?<section className="cc-panel"><span className="eyebrow">Durable result</span><h2>{state.invocation.result.summary??'Recorded command result'}</h2><p>{state.invocation.result.verified?'Verified':'Not verified'} · invocation <code>{state.invocation.invocation_id}</code></p></section>:<section className="cc-unavailable" role="status"><div><h2>No matching invocation</h2></div><p>The artifact is authorized, but no durable invocation was supplied. Opening this application did not run one.</p></section>}
    {executableFixtureEnabled()&&<ExecutableFixtureView client={state.client} resource={state.resource} content={state.content}/>}
    <DesktopCanonicalRenderer client={state.client} resource={state.resource} content={state.content}/>
    <PersonalPresentationSettings key={`${state.key}:${state.client===client}`} client={state.client} projectId={state.resource.project_id} onEffective={updateEffective}/>
    <details className="cc-panel"><summary>Technical inspector</summary><dl><dt>Application</dt><dd><code>{builtInEvidenceApplication.applicationId}</code></dd><dt>Opened from</dt><dd><code>{handoff.origin}</code></dd><dt>Project</dt><dd><code>{state.resource.project_id}</code></dd><dt>Run</dt><dd><code>{state.resource.run_id}</code></dd><dt>Artifact</dt><dd><code>{state.resource.artifact_id}</code></dd><dt>Digest</dt><dd><code>{state.resource.digest}</code></dd><dt>Command</dt><dd><code>{state.descriptor.command_id}@{state.descriptor.version}</code></dd><dt>Descriptor</dt><dd><code>{state.descriptor.descriptor_digest}</code></dd>{state.invocation&&<><dt>Invocation</dt><dd><code>{state.invocation.invocation_id}</code></dd><dt>Receipt</dt><dd><code>{state.invocation.receipt.resource_digest}</code></dd></>}</dl><p>Destination access was checked again. Viewing this report does not dispatch the command.</p></details>
  </main>
}

if(!getSurface('artifact-evidence'))registerSurface({id:'artifact-evidence',inputs:['client','handoff'],Component:ArtifactEvidenceSurface})

export function ArtifactEvidencePage(){const{services}=useStore();const[p]=useSearchParams();const handoff:Handoff={projectId:p.get('project')??'',runId:p.get('run')??'',artifactId:p.get('artifact')??'',digest:p.get('digest')??'',commandId:p.get('command')??'',commandVersion:Number(p.get('version')??0),descriptorDigest:p.get('descriptor')??'',invocationId:p.get('invocation')??'',origin:p.get('origin')??'unknown'};if(!handoff.projectId||!handoff.runId||!handoff.artifactId||!handoff.digest||!handoff.commandId||!handoff.commandVersion||!handoff.descriptorDigest)return <main className="content-page"><EmptyState title="Choose an exact artifact" description="Open this application from a registered artifact application so every resource and command identity is preserved."/></main>;return <ArtifactEvidenceSurface client={services?.malleableShell} handoff={handoff}/>} 
