import React,{useEffect,useRef,useState}from'react'
import{useSearchParams}from'react-router-dom'
import type{ExactArtifactRef,MalleableShellClient,ShellCommandDescriptor,ShellCommandResult}from'../../services/contracts'
import{useStore}from'../../data/store'
import{EmptyState}from'../../ui/EmptyState'
import{getSurface,registerSurface}from'../../surfaces/registry'

void React
export const builtInEvidenceApplication={applicationId:'opensaddle.artifact.evidence.v1'} as const
type Handoff={projectId:string;runId:string;artifactId:string;digest:string;commandId:string;commandVersion:number;descriptorDigest:string;invocationId:string;origin:string}
type State={kind:'loading'}|{kind:'error';reason:string}|{kind:'ready';resource:ExactArtifactRef;descriptor:ShellCommandDescriptor;invocation?:ShellCommandResult}
const sameResource=(a:ExactArtifactRef,b:ExactArtifactRef)=>a.project_id===b.project_id&&a.run_id===b.run_id&&a.artifact_id===b.artifact_id&&a.digest===b.digest

export function ArtifactEvidenceSurface({client,handoff}:{client?:MalleableShellClient;handoff:Handoff}){
  const[state,setState]=useState<State>({kind:'loading'});const generation=useRef(0)
  useEffect(()=>{const current=++generation.current;setState({kind:'loading'});if(!client){setState({kind:'error',reason:'The connected server does not expose the public artifact resource boundary.'});return}const expected:ExactArtifactRef={project_id:handoff.projectId,run_id:handoff.runId,artifact_id:handoff.artifactId,digest:handoff.digest};void Promise.all([client.artifacts(handoff.runId,handoff.projectId),client.commands(handoff.projectId),handoff.invocationId?client.invocation(handoff.invocationId):Promise.resolve(undefined)]).then(([resources,commands,invocation])=>{if(current!==generation.current)return;const resource=resources.find(item=>sameResource(item,expected));const descriptor=commands.find(item=>item.command_id===handoff.commandId&&item.version===handoff.commandVersion&&item.descriptor_digest===handoff.descriptorDigest);if(!resource)throw Error('The exact artifact is missing, changed, or no longer authorized.');if(!descriptor||!descriptor.available.available)throw Error(descriptor?.available.reason??'The originating command descriptor is stale or unavailable.');if(invocation&&(!sameResource(invocation.resource,resource)||invocation.command_id!==descriptor.command_id||invocation.version!==descriptor.version||invocation.descriptor_digest!==descriptor.descriptor_digest))throw Error('The durable invocation no longer matches this exact resource and command authority.');setState({kind:'ready',resource,descriptor,invocation})}).catch(reason=>{if(current===generation.current)setState({kind:'error',reason:reason instanceof Error?reason.message:String(reason)})});return()=>{generation.current++}},[client,handoff.projectId,handoff.runId,handoff.artifactId,handoff.digest,handoff.commandId,handoff.commandVersion,handoff.descriptorDigest,handoff.invocationId])
  if(state.kind==='loading')return <main className="content-page cc-page" aria-busy="true"><p role="status">Reauthorizing the exact artifact at the destination…</p></main>
  if(state.kind==='error')return <main className="content-page cc-page"><EmptyState role="alert" title="Evidence application unavailable" description={state.reason}/></main>
  const back=new URLSearchParams({project:handoff.projectId,run:handoff.runId,artifact:handoff.artifactId,digest:handoff.digest,...(state.invocation?{invocation:state.invocation.invocation_id}:{})})
  return <main className="content-page cc-page"><header className="cc-header"><div><span className="eyebrow">Independent application</span><h1>Artifact evidence notebook</h1><p>A focused, read-only record of the exact artifact, its origin, and durable command result.</p></div><a className="cc-text-link" href={`review?${back}`}>Return to review workspace</a></header>
    <section className="cc-unavailable" aria-label="Application provenance"><div><h2>Application</h2><code>{builtInEvidenceApplication.applicationId}</code></div><p>Opened explicitly from <code>{handoff.origin}</code>. Destination access was checked again.</p></section>
    <div className="cc-grid"><section className="cc-panel"><span className="eyebrow">Bound resource</span><h2>Artifact identity</h2><dl><dt>Project</dt><dd><code>{state.resource.project_id}</code></dd><dt>Run</dt><dd><code>{state.resource.run_id}</code></dd><dt>Artifact</dt><dd><code>{state.resource.artifact_id}</code></dd><dt>Digest</dt><dd><code>{state.resource.digest}</code></dd></dl></section><section className="cc-panel"><span className="eyebrow">Shared authority</span><h2>{state.descriptor.title}</h2><dl><dt>Command</dt><dd><code>{state.descriptor.command_id}@{state.descriptor.version}</code></dd><dt>Descriptor</dt><dd><code>{state.descriptor.descriptor_digest}</code></dd><dt>Access</dt><dd>Reauthorized for this application</dd></dl><p>Viewing this notebook does not dispatch the command.</p></section></div>
    {state.invocation?<section className="cc-panel"><span className="eyebrow">Durable result</span><h2>{state.invocation.result.summary??'Recorded command result'}</h2><p>{state.invocation.result.verified?'Verified':'Not verified'} · invocation <code>{state.invocation.invocation_id}</code></p><p>Receipt <code>{state.invocation.receipt.resource_digest}</code></p></section>:<section className="cc-unavailable" role="status"><div><h2>No matching invocation</h2></div><p>The artifact is authorized, but no durable invocation was supplied. Opening this application did not run one.</p></section>}
  </main>
}

if(!getSurface('artifact-evidence'))registerSurface({id:'artifact-evidence',inputs:['client','handoff'],Component:ArtifactEvidenceSurface})

export function ArtifactEvidencePage(){const{services}=useStore();const[p]=useSearchParams();const handoff:Handoff={projectId:p.get('project')??'',runId:p.get('run')??'',artifactId:p.get('artifact')??'',digest:p.get('digest')??'',commandId:p.get('command')??'',commandVersion:Number(p.get('version')??0),descriptorDigest:p.get('descriptor')??'',invocationId:p.get('invocation')??'',origin:p.get('origin')??'unknown'};if(!handoff.projectId||!handoff.runId||!handoff.artifactId||!handoff.digest||!handoff.commandId||!handoff.commandVersion||!handoff.descriptorDigest)return <main className="content-page"><EmptyState title="Choose an exact artifact" description="Open this application from a registered artifact application so every resource and command identity is preserved."/></main>;return <ArtifactEvidenceSurface client={services?.malleableShell} handoff={handoff}/>} 
