import React,{useEffect,useRef,useState}from'react'
import{useSearchParams}from'react-router-dom'
import type{ArtifactContent,ExactArtifactRef,MalleableShellClient,ShellCommandDescriptor,ShellCommandResult}from'../../services/contracts'
import{useStore}from'../../data/store'
import{EmptyState}from'../../ui/EmptyState'
import{getSurface,registerSurface}from'../../surfaces/registry'

void React
export const builtInEvidenceApplication={applicationId:'opensaddle.artifact.evidence.v1'} as const
type Handoff={projectId:string;runId:string;artifactId:string;digest:string;commandId:string;commandVersion:number;descriptorDigest:string;invocationId:string;origin:string}
type State={kind:'loading'}|{kind:'error';reason:string}|{kind:'ready';key:string;client:MalleableShellClient;resource:ExactArtifactRef;descriptor:ShellCommandDescriptor;content:ArtifactContent;invocation?:ShellCommandResult}
const sameResource=(a:ExactArtifactRef,b:ExactArtifactRef)=>a.project_id===b.project_id&&a.run_id===b.run_id&&a.artifact_id===b.artifact_id&&a.digest===b.digest
const handoffKey=(h:Handoff)=>[h.projectId,h.runId,h.artifactId,h.digest,h.commandId,h.commandVersion,h.descriptorDigest,h.invocationId].join('\u0000')
function safeInline(value:string){const parts:Array<React.ReactNode>=[];const pattern=/\[([^\]]{1,200})\]\((https?:\/\/[^\s)]+)\)/g;let cursor=0,match:RegExpExecArray|null;while((match=pattern.exec(value))){parts.push(value.slice(cursor,match.index),<a key={`${match.index}:${match[2]}`} href={match[2]} target="_blank" rel="noreferrer">{match[1]}</a>);cursor=pattern.lastIndex}parts.push(value.slice(cursor));return parts}
function SafeMarkdown({text}:{text:string}){const lines=text.split(/\r?\n/);let fenced=false;return <div className="artifact-report">{lines.map((line,index)=>{if(line.startsWith('```')){fenced=!fenced;return null}if(fenced)return <pre key={index}>{line}</pre>;const heading=/^(#{1,3})\s+(.+)$/.exec(line);if(heading){const H=`h${heading[1].length+1}` as 'h2'|'h3'|'h4';return <H key={index}>{safeInline(heading[2])}</H>}if(/^[-*]\s+/.test(line))return <p key={index}>• {safeInline(line.slice(2))}</p>;if(/^>\s?/.test(line))return <blockquote key={index}>{safeInline(line.replace(/^>\s?/,''))}</blockquote>;return line?<p key={index}>{safeInline(line)}</p>:<br key={index}/>})}</div>}

export function ArtifactEvidenceSurface({client,handoff}:{client?:MalleableShellClient;handoff:Handoff}){
  const[state,setState]=useState<State>({kind:'loading'});const generation=useRef(0)
  useEffect(()=>{const current=++generation.current;setState({kind:'loading'});if(!client?.content){setState({kind:'error',reason:'Artifact bytes are unavailable from this server.'});return}const expected:ExactArtifactRef={project_id:handoff.projectId,run_id:handoff.runId,artifact_id:handoff.artifactId,digest:handoff.digest};void Promise.all([client.artifacts(handoff.runId,handoff.projectId),client.commands(handoff.projectId),handoff.invocationId?client.invocation(handoff.invocationId):Promise.resolve(undefined)]).then(async([resources,commands,invocation])=>{if(current!==generation.current)return;const resource=resources.find(item=>sameResource(item,expected));const descriptor=commands.find(item=>item.command_id===handoff.commandId&&item.version===handoff.commandVersion&&item.descriptor_digest===handoff.descriptorDigest);if(!resource)throw Error('The exact artifact is missing, changed, or no longer authorized.');if(!descriptor||!descriptor.available.available)throw Error(descriptor?.available.reason??'The originating command descriptor is stale or unavailable.');if(invocation&&(!sameResource(invocation.resource,resource)||invocation.command_id!==descriptor.command_id||invocation.version!==descriptor.version||invocation.descriptor_digest!==descriptor.descriptor_digest))throw Error('The durable invocation no longer matches this exact resource and command authority.');const content=await client.content!(resource);if(current!==generation.current)return;if(content.digest!==resource.digest.replace(/^sha256:/,'').toLowerCase())throw Error('artifact_content_integrity_denied');setState({kind:'ready',key:handoffKey(handoff),client,resource,descriptor,content,invocation})}).catch(reason=>{if(current===generation.current)setState({kind:'error',reason:reason instanceof Error?reason.message:String(reason)})});return()=>{generation.current++}},[client,handoff.projectId,handoff.runId,handoff.artifactId,handoff.digest,handoff.commandId,handoff.commandVersion,handoff.descriptorDigest,handoff.invocationId])
  if(state.kind==='ready'&&(state.client!==client||state.key!==handoffKey(handoff)))return <main className="content-page cc-page" aria-busy="true"><p role="status">Reauthorizing the exact artifact at the destination…</p></main>
  if(state.kind==='loading')return <main className="content-page cc-page" aria-busy="true"><p role="status">Reauthorizing the exact artifact at the destination…</p></main>
  if(state.kind==='error')return <main className="content-page cc-page"><EmptyState role="alert" title="Evidence application unavailable" description={state.reason}/></main>
  const back=new URLSearchParams({project:handoff.projectId,run:handoff.runId,artifact:handoff.artifactId,digest:handoff.digest,...(state.invocation?{invocation:state.invocation.invocation_id}:{})})
  const summary=state.content.text.split(/\r?\n/).map(line=>line.replace(/^#+\s*/, '').trim()).find(Boolean)??'Artifact report'
  return <main className="content-page cc-page"><header className="cc-header"><div><span className="eyebrow">Independent application</span><h1>{summary}</h1><p>Authenticated artifact report · exact bytes verified against the recorded digest.</p></div><a className="cc-text-link" href={`review?${back}`}>Return to review workspace</a></header>
    <section className="cc-unavailable" aria-label="Application provenance"><div><h2>Application</h2><code>{builtInEvidenceApplication.applicationId}</code></div><p>Opened explicitly from <code>{handoff.origin}</code>. Destination access was checked again.</p></section>
    <section className="cc-panel"><span className="eyebrow">Report</span><SafeMarkdown text={state.content.text}/></section>
    <section className="cc-panel"><span className="eyebrow">Evidence</span><h2>Source and freshness</h2><p>Read from the authenticated Core artifact endpoint for this exact Run. Integrity verified now against the recorded SHA-256 digest.</p>{state.resource.created_at&&<p>Artifact recorded <time dateTime={state.resource.created_at}>{new Date(state.resource.created_at).toLocaleString()}</time>.</p>}<p>{state.content.sizeBytes.toLocaleString()} bytes · {state.content.mediaType}</p></section>
    {state.invocation?<section className="cc-panel"><span className="eyebrow">Durable result</span><h2>{state.invocation.result.summary??'Recorded command result'}</h2><p>{state.invocation.result.verified?'Verified':'Not verified'} · invocation <code>{state.invocation.invocation_id}</code></p></section>:<section className="cc-unavailable" role="status"><div><h2>No matching invocation</h2></div><p>The artifact is authorized, but no durable invocation was supplied. Opening this application did not run one.</p></section>}
    <details className="cc-panel"><summary>Technical inspector</summary><dl><dt>Project</dt><dd><code>{state.resource.project_id}</code></dd><dt>Run</dt><dd><code>{state.resource.run_id}</code></dd><dt>Artifact</dt><dd><code>{state.resource.artifact_id}</code></dd><dt>Digest</dt><dd><code>{state.resource.digest}</code></dd><dt>Command</dt><dd><code>{state.descriptor.command_id}@{state.descriptor.version}</code></dd><dt>Descriptor</dt><dd><code>{state.descriptor.descriptor_digest}</code></dd>{state.invocation&&<><dt>Invocation</dt><dd><code>{state.invocation.invocation_id}</code></dd><dt>Receipt</dt><dd><code>{state.invocation.receipt.resource_digest}</code></dd></>}</dl><p>Viewing this notebook does not dispatch the command.</p></details>
  </main>
}

if(!getSurface('artifact-evidence'))registerSurface({id:'artifact-evidence',inputs:['client','handoff'],Component:ArtifactEvidenceSurface})

export function ArtifactEvidencePage(){const{services}=useStore();const[p]=useSearchParams();const handoff:Handoff={projectId:p.get('project')??'',runId:p.get('run')??'',artifactId:p.get('artifact')??'',digest:p.get('digest')??'',commandId:p.get('command')??'',commandVersion:Number(p.get('version')??0),descriptorDigest:p.get('descriptor')??'',invocationId:p.get('invocation')??'',origin:p.get('origin')??'unknown'};if(!handoff.projectId||!handoff.runId||!handoff.artifactId||!handoff.digest||!handoff.commandId||!handoff.commandVersion||!handoff.descriptorDigest)return <main className="content-page"><EmptyState title="Choose an exact artifact" description="Open this application from a registered artifact application so every resource and command identity is preserved."/></main>;return <ArtifactEvidenceSurface client={services?.malleableShell} handoff={handoff}/>} 
