import assert from'node:assert/strict'
import test from'node:test'
import React from'react'
import{act,create}from'react-test-renderer'
import{MemoryRouter}from'react-router-dom'
import type{ExactArtifactRef,MalleableShellClient,ShellCommandDescriptor,ShellCommandResult}from'../../services/contracts'
import{ArtifactEvidenceSurface}from'./ArtifactEvidenceApplication'

;(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;void React
const ref:ExactArtifactRef={project_id:'P1',run_id:'R1',artifact_id:'A1',digest:'digest-1'}
const command:ShellCommandDescriptor={command_id:'dev.opensaddle.artifact.review',version:2,descriptor_digest:'descriptor-2',title:'Review artifacts',description:'Review',effect:'read',required_actions:['artifacts:read'],available:{available:true},input_schema:{},output_schema:{}}
const result:ShellCommandResult={invocation_id:'inv-1',project_id:'P1',command_id:command.command_id,version:2,descriptor_digest:command.descriptor_digest,invoked_by:'user',created_at:'now',resource:ref,input:{},status:'completed',result:{summary:'Exact review',verified:true},receipt:{effect:'read',resource_digest:ref.digest,verified:true}}
const handoff={projectId:'P1',runId:'R1',artifactId:'A1',digest:'digest-1',commandId:command.command_id,commandVersion:2,descriptorDigest:command.descriptor_digest,invocationId:'inv-1',origin:'opensaddle.review.workspace.v1'}
const personal=(revision=0,density:'compact'|'comfortable'='comfortable',presentation:'document'|'split'|'focus'='document')=>({schema_version:'opensaddle.environment-personal.v1',project_id:'P1',subject:'member',revision,base_environment_revision:4,base_definition_digest:'b'.repeat(64),overrides:{instances:revision?{'review-main':{density,presentation}}:{}},effective_instances:[{instance_id:'review-main',application_id:'review.evidence',application_version:2,definition_digest:'a'.repeat(64),source_ref:{authority:'opensaddle://core',resource_type:'application-definition',resource_id:'artifact-evidence',version:'2',digest:`sha256:${'a'.repeat(64)}`},package_ref:null,defaults:{density:'comfortable' as const,presentation:'document' as const,order:10},effective:{density,presentation,order:10}}],conflicts:[],changed_by:revision?'member':null,reason:revision?'Saved':null,parent_revision:revision?revision-1:null,created_at:revision?'now':null})
function api(overrides:Partial<MalleableShellClient>={}):MalleableShellClient{return{artifacts:async()=>[ref],commands:async()=>[command],content:async()=>({text:'# Verified report\nSource: [safe](https://example.com)\n<script>alert(1)</script>\n[unsafe](javascript:alert(1))',mediaType:'text/markdown',sizeBytes:100,digest:'digest-1'}),invocation:async()=>result,invocations:async()=>[],invoke:async()=>{throw Error('view must not invoke')},connectors:async()=>[],invokeConnector:async()=>{throw Error('unused')},environment:async()=>{throw Error('unused')},preview:async()=>{throw Error('unused')},apply:async()=>{throw Error('unused')},revert:async()=>{throw Error('unused')},...overrides}}
async function mount(client:MalleableShellClient,props=handoff){let renderer!:ReturnType<typeof create>;await act(async()=>{renderer=create(<MemoryRouter><ArtifactEvidenceSurface client={client} handoff={props}/></MemoryRouter>)});return renderer}

test('destination independently reauthorizes exact resource, descriptor, and durable invocation without rerunning',async()=>{let invokes=0;let reads:string[]=[];const renderer=await mount(api({artifacts:async(run,project)=>{reads.push(`${project}/${run}`);return[ref]},commands:async project=>{reads.push(project);return[command]},invocation:async id=>{reads.push(id);return result},invoke:async()=>{invokes++;return result}}));const markup=JSON.stringify(renderer.toJSON());assert.deepEqual(reads,['P1/R1','P1','inv-1']);assert.equal(invokes,0);for(const value of['Verified report','safe','script','unsafe','review.evidence','opensaddle.review.workspace.v1','A1','digest-1','descriptor-2','inv-1'])assert.ok(markup.includes(value));assert.equal(renderer.root.findAllByType('script').length,0);assert.deepEqual(renderer.root.findAllByType('a').filter(node=>node.props.target==='_blank').map(node=>node.props.href),['https://example.com']);assert.match(markup,/Return to review workspace/);assert.ok(markup.indexOf('Report')<markup.indexOf('Technical inspector'));assert.equal(renderer.root.findAllByType('h1').length,1);assert.equal(renderer.root.findAllByType('h2').filter(node=>node.children.join('')==='Verified report').length,0)} )

test('revoked destination clears protected evidence during a client transition',async()=>{let reject!:(reason:Error)=>void;const denied=api({artifacts:async()=>new Promise((_,r)=>{reject=r})});const renderer=await mount(api());assert.match(JSON.stringify(renderer.toJSON()),/A1.*digest-1/s);await act(async()=>{renderer.update(<MemoryRouter><ArtifactEvidenceSurface client={denied} handoff={handoff}/></MemoryRouter>);await Promise.resolve()});assert.doesNotMatch(JSON.stringify(renderer.toJSON()),/A1|digest-1|inv-1/);await act(async()=>{reject(Error('access revoked'));await Promise.resolve()});const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Evidence application unavailable.*access revoked/s);assert.doesNotMatch(markup,/Exact review/)})

test('changed artifact or command version fails closed at destination',async()=>{const changed={...ref,digest:'digest-2'};const staleCommand={...command,version:3,descriptor_digest:'descriptor-3'};for(const client of[api({artifacts:async()=>[changed]}),api({commands:async()=>[staleCommand]})]){const renderer=await mount(client);const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Evidence application unavailable/);assert.doesNotMatch(markup,/Exact review|Artifact identity/)}})

test('bytes unavailable and integrity denial render explicit empty states',async()=>{for(const reason of['artifact_bytes_unavailable','artifact_content_integrity_denied']){const renderer=await mount(api({content:async()=>{throw Error(reason)}}));const markup=JSON.stringify(renderer.toJSON());assert.match(markup,new RegExp(reason));assert.doesNotMatch(markup,/Verified report|Exact review/)}})

test('late response from the origin route cannot publish into a new handoff',async()=>{let resolve!:(value:ExactArtifactRef[])=>void;const slow=api({artifacts:async()=>new Promise(r=>{resolve=r})});const renderer=await mount(slow);const next={...handoff,runId:'R2',artifactId:'A2',digest:'digest-2',invocationId:''};await act(async()=>{renderer.update(<MemoryRouter><ArtifactEvidenceSurface client={api({artifacts:async()=>[]})} handoff={next}/></MemoryRouter>);await Promise.resolve()});await act(async()=>{resolve([ref]);await Promise.resolve()});const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Evidence application unavailable/);assert.doesNotMatch(markup,/A1|digest-1|inv-1/)})

test('personal presentation previews exact CAS then applies the server effective instance',async()=>{const calls:Array<{kind:string;revision:number;overrides:unknown}>=[];const renderer=await mount(api({personalEnvironment:async()=>personal(),previewPersonalEnvironment:async(_project,revision,overrides)=>{calls.push({kind:'preview',revision,overrides});return{schema_version:'opensaddle.environment-personal-preview.v1',project_id:'P1',subject:'member',base_revision:revision,base_environment_revision:4,base_definition_digest:'b'.repeat(64),diff:{before:{instances:{}},after:overrides},activatable:true,requirements:[]}},applyPersonalEnvironment:async(_project,revision,overrides)=>{calls.push({kind:'apply',revision,overrides});return personal(1,'compact','split')}}));const selects=renderer.root.findAllByType('select');await act(async()=>{selects[0]!.props.onChange({target:{value:'compact'}});selects[1]!.props.onChange({target:{value:'split'}})});const button=(label:string)=>renderer.root.findAllByType('button').find(node=>node.children.join('')===label)!;assert.equal(button('Save for me').props.disabled,true);await act(async()=>{await button('Check changes').props.onClick()});assert.equal(button('Save for me').props.disabled,false);await act(async()=>{await button('Save for me').props.onClick()});assert.deepEqual(calls,[{kind:'preview',revision:0,overrides:{instances:{'review-main':{density:'compact',presentation:'split'}}}},{kind:'apply',revision:0,overrides:{instances:{'review-main':{density:'compact',presentation:'split'}}}}]);assert.match(renderer.root.findByType('main').props.className,/artifact-evidence-view--split.*artifact-evidence-view--compact/);assert.ok(renderer.root.findAllByType('p').some(node=>node.children.join('')==='Personal revision 1 over shared environment revision 4.'))})

test('personal conflicts are explicit and restore uses the previous immutable revision',async()=>{const conflicted={...personal(2),conflicts:['removed-instance'],parent_revision:1};let reverted=false;const renderer=await mount(api({personalEnvironment:async()=>conflicted,revertPersonalEnvironment:async(_project,expected,target)=>{assert.equal(expected,2);assert.equal(target,1);reverted=true;return personal(3)}}));assert.match(JSON.stringify(renderer.toJSON()),/conflict.*removed-instance/i);const restore=renderer.root.findAllByType('button').find(node=>node.children.join('')==='Restore previous')!;await act(async()=>{await restore.props.onClick()});assert.equal(reverted,true);assert.ok(renderer.root.findAllByType('p').some(node=>node.children.join('').startsWith('Personal revision 3 ')))})

test('a pending personal check locks the exact draft until its response resolves',async()=>{let resolve!:(value:any)=>void;const checked=new Promise<any>(done=>{resolve=done});const renderer=await mount(api({personalEnvironment:async()=>personal(),previewPersonalEnvironment:async()=>checked}));const selects=renderer.root.findAllByType('select');const check=renderer.root.findAllByType('button').find(node=>node.children.join('')==='Check changes')!;await act(async()=>{void check.props.onClick();await Promise.resolve()});assert.equal(renderer.root.findAllByType('select')[0]!.props.disabled,true);await act(async()=>{selects[0]!.props.onChange({target:{value:'compact'}})});assert.equal(renderer.root.findAllByType('select')[0]!.props.value,'comfortable');await act(async()=>{resolve({schema_version:'opensaddle.environment-personal-preview.v1',project_id:'P1',subject:'member',base_revision:0,base_environment_revision:4,base_definition_digest:'b'.repeat(64),diff:{before:{instances:{}},after:{instances:{}}},activatable:true,requirements:[]});await checked});assert.equal(renderer.root.findAllByType('select')[0]!.props.disabled,false)})

test('only a leading promoted heading is omitted from the report body',async()=>{const renderer=await mount(api({content:async()=>({text:'Opening summary\n## Evidence section\nDetails',mediaType:'text/markdown',sizeBytes:42,digest:'digest-1'})}));assert.equal(renderer.root.findByType('h1').children.join(''),'Opening summary');assert.ok(renderer.root.findAllByType('h3').some(node=>node.children.join('')==='Evidence section'))})

test('a shared-environment CAS conflict leaves the applied presentation unchanged',async()=>{const preview={schema_version:'opensaddle.environment-personal-preview.v1',project_id:'P1',subject:'member',base_revision:0,base_environment_revision:4,base_definition_digest:'b'.repeat(64),diff:{before:{instances:{}},after:{instances:{}}},activatable:true,requirements:[]};const renderer=await mount(api({personalEnvironment:async()=>personal(),previewPersonalEnvironment:async()=>preview,applyPersonalEnvironment:async()=>{throw Error('personal environment base revision conflict')}}));const selects=renderer.root.findAllByType('select');await act(async()=>{selects[1]!.props.onChange({target:{value:'split'}})});const button=(label:string)=>renderer.root.findAllByType('button').find(node=>node.children.join('')===label)!;await act(async()=>{await button('Check changes').props.onClick()});await act(async()=>{await button('Save for me').props.onClick()});assert.match(JSON.stringify(renderer.toJSON()),/personal environment base revision conflict/);assert.match(renderer.root.findByType('main').props.className,/artifact-evidence-view--document/);assert.doesNotMatch(renderer.root.findByType('main').props.className,/artifact-evidence-view--split/)})
