import assert from'node:assert/strict'
import test from'node:test'
import React from'react'
import{act,create}from'react-test-renderer'
import{MemoryRouter}from'react-router-dom'
import type{ExactArtifactRef,MalleableShellClient,ShellCommandDescriptor,ShellCommandResult}from'../../services/contracts'
import{ArtifactEvidenceSurface}from'./ArtifactEvidenceApplication'

;(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;void React
const ref:ExactArtifactRef={project_id:'P1',run_id:'R1',artifact_id:'A1',digest:'digest-1'}
const command:ShellCommandDescriptor={command_id:'dev.opensaddle.artifact.review',version:2,descriptor_digest:'descriptor-2',title:'Review artifacts',description:'Review',effect:'read',required_actions:['artifacts:read'],available:{available:true},input_schema:{},output_schema:{}}
const result:ShellCommandResult={invocation_id:'inv-1',project_id:'P1',command_id:command.command_id,version:2,descriptor_digest:command.descriptor_digest,invoked_by:'user',created_at:'now',resource:ref,input:{},status:'completed',result:{summary:'Exact review',verified:true},receipt:{effect:'read',resource_digest:ref.digest,verified:true}}
const handoff={projectId:'P1',runId:'R1',artifactId:'A1',digest:'digest-1',commandId:command.command_id,commandVersion:2,descriptorDigest:command.descriptor_digest,invocationId:'inv-1',origin:'opensaddle.review.workspace.v1'}
function api(overrides:Partial<MalleableShellClient>={}):MalleableShellClient{return{artifacts:async()=>[ref],commands:async()=>[command],content:async()=>({text:'# Verified report\nSource: [safe](https://example.com)\n<script>alert(1)</script>\n[unsafe](javascript:alert(1))',mediaType:'text/markdown',sizeBytes:100,digest:'digest-1'}),invocation:async()=>result,invocations:async()=>[],invoke:async()=>{throw Error('view must not invoke')},connectors:async()=>[],invokeConnector:async()=>{throw Error('unused')},environment:async()=>{throw Error('unused')},preview:async()=>{throw Error('unused')},apply:async()=>{throw Error('unused')},revert:async()=>{throw Error('unused')},...overrides}}
async function mount(client:MalleableShellClient,props=handoff){let renderer!:ReturnType<typeof create>;await act(async()=>{renderer=create(<MemoryRouter><ArtifactEvidenceSurface client={client} handoff={props}/></MemoryRouter>)});return renderer}

test('destination independently reauthorizes exact resource, descriptor, and durable invocation without rerunning',async()=>{let invokes=0;let reads:string[]=[];const renderer=await mount(api({artifacts:async(run,project)=>{reads.push(`${project}/${run}`);return[ref]},commands:async project=>{reads.push(project);return[command]},invocation:async id=>{reads.push(id);return result},invoke:async()=>{invokes++;return result}}));const markup=JSON.stringify(renderer.toJSON());assert.deepEqual(reads,['P1/R1','P1','inv-1']);assert.equal(invokes,0);for(const value of['Verified report','safe','script','unsafe','opensaddle.artifact.evidence.v1','opensaddle.review.workspace.v1','A1','digest-1','descriptor-2','inv-1'])assert.ok(markup.includes(value));assert.equal(renderer.root.findAllByType('script').length,0);assert.deepEqual(renderer.root.findAllByType('a').filter(node=>node.props.target==='_blank').map(node=>node.props.href),['https://example.com']);assert.match(markup,/Return to review workspace/)} )

test('revoked destination clears protected evidence during a client transition',async()=>{let reject!:(reason:Error)=>void;const denied=api({artifacts:async()=>new Promise((_,r)=>{reject=r})});const renderer=await mount(api());assert.match(JSON.stringify(renderer.toJSON()),/A1.*digest-1/s);await act(async()=>{renderer.update(<MemoryRouter><ArtifactEvidenceSurface client={denied} handoff={handoff}/></MemoryRouter>);await Promise.resolve()});assert.doesNotMatch(JSON.stringify(renderer.toJSON()),/A1|digest-1|inv-1/);await act(async()=>{reject(Error('access revoked'));await Promise.resolve()});const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Evidence application unavailable.*access revoked/s);assert.doesNotMatch(markup,/Exact review/)})

test('changed artifact or command version fails closed at destination',async()=>{const changed={...ref,digest:'digest-2'};const staleCommand={...command,version:3,descriptor_digest:'descriptor-3'};for(const client of[api({artifacts:async()=>[changed]}),api({commands:async()=>[staleCommand]})]){const renderer=await mount(client);const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Evidence application unavailable/);assert.doesNotMatch(markup,/Exact review|Artifact identity/)}})

test('bytes unavailable and integrity denial render explicit empty states',async()=>{for(const reason of['artifact_bytes_unavailable','artifact_content_integrity_denied']){const renderer=await mount(api({content:async()=>{throw Error(reason)}}));const markup=JSON.stringify(renderer.toJSON());assert.match(markup,new RegExp(reason));assert.doesNotMatch(markup,/Verified report|Exact review/)}})

test('late response from the origin route cannot publish into a new handoff',async()=>{let resolve!:(value:ExactArtifactRef[])=>void;const slow=api({artifacts:async()=>new Promise(r=>{resolve=r})});const renderer=await mount(slow);const next={...handoff,runId:'R2',artifactId:'A2',digest:'digest-2',invocationId:''};await act(async()=>{renderer.update(<MemoryRouter><ArtifactEvidenceSurface client={api({artifacts:async()=>[]})} handoff={next}/></MemoryRouter>);await Promise.resolve()});await act(async()=>{resolve([ref]);await Promise.resolve()});const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Evidence application unavailable/);assert.doesNotMatch(markup,/A1|digest-1|inv-1/)})
