import React,{useRef,useState} from 'react'
import {TeamsClient,type ProjectTeamAssociation,type TeamSummary} from '../../services/teams'
import {PresentationSettingsClient} from '../../services/presentationSettings'

export function ProjectTeamSettings({client,presentation,projectId}:{client:TeamsClient;presentation:PresentationSettingsClient;projectId:string}) {
 const [row,setRow]=useState<ProjectTeamAssociation>(),[teams,setTeams]=useState<TeamSummary[]>([]),[selected,setSelected]=useState(''),[manager,setManager]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[review,setReview]=useState<'propose'|'detach'>()
 const generation=useRef(0),lock=useRef(false)
 React.useEffect(()=>{const epoch=++generation.current;setRow(undefined);setTeams([]);setReview(undefined);setManager(false);setError('');lock.current=true;setBusy(true);Promise.all([client.association(projectId),client.list(),presentation.read('project',projectId)]).then(([row,teams,settings])=>{if(epoch===generation.current){setRow(row);setTeams(teams);setSelected(row.team_id??'');setManager(settings.can_write)}}).catch(()=>{if(epoch===generation.current)setError('Team association unavailable. Reload to check your access.')}).finally(()=>{if(epoch===generation.current){lock.current=false;setBusy(false)}});return()=>{generation.current++}},[client,presentation,projectId,refresh])
 async function apply(){if(lock.current||!row||!review)return;lock.current=true;setBusy(true);const epoch=generation.current;try{await client.changeAssociation(projectId,row.revision,review,selected);if(epoch===generation.current){presentation.notifyChanged();setRefresh(value=>value+1)}}catch{if(epoch===generation.current){setRow(undefined);setReview(undefined);setError('The association changed or your access changed. Reload before retrying.')}}finally{if(epoch===generation.current){lock.current=false;setBusy(false)}}}
 return <section className="settings-card presentation-editor"><h2>Team defaults</h2><p>Use one Team’s presentation defaults in this project. A Team manager must approve sharing them.</p><button disabled={busy} onClick={()=>setRefresh(value=>value+1)}>Reload association</button>{error&&<p role="alert">{error}</p>}{row&&<><p role="status">{row.team_id?`${teams.find(team=>team.team_id===row.team_id)?.display_name??row.team_id} · ${row.state}${row.state==='accepted'?(row.effective?' · Inheriting defaults':' · Inheritance inactive'):''}`:'No Team associated'}</p>{manager&&<><label>Presentation Team<select disabled={busy||!!review} value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose a Team</option>{teams.map(team=><option key={team.team_id} value={team.team_id}>{team.display_name}</option>)}</select></label><button disabled={busy||!selected||!!review} onClick={()=>setReview('propose')}>Review proposal</button>{row.team_id&&row.state!=='detached'&&<button disabled={busy||!!review} onClick={()=>setReview('detach')}>Detach Team</button>}{review&&<div><p>{review==='propose'?`Propose ${teams.find(team=>team.team_id===selected)?.display_name??selected}? Existing Team inheritance stops until this proposal is accepted.`:'Stop inheriting this Team’s defaults? Project and personal preferences remain.'}</p><p>Project membership and device access stay separate.</p><button disabled={busy} onClick={()=>void apply()}>{review==='propose'?'Confirm proposal':'Confirm detach'}</button><button disabled={busy} onClick={()=>setReview(undefined)}>Cancel</button></div>}</>}</>}</section>
}

export function TeamProjectReviews({client,teamId,presentation}:{client:TeamsClient;teamId:string;presentation?:PresentationSettingsClient}){
 const [rows,setRows]=useState<ProjectTeamAssociation[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[review,setReview]=useState<{row:ProjectTeamAssociation;action:'accept'|'detach'}>()
 const generation=useRef(0),lock=useRef(false)
 React.useEffect(()=>{const epoch=++generation.current;setRows([]);setReview(undefined);setError('');lock.current=true;setBusy(true);client.projects(teamId).then(rows=>{if(epoch===generation.current)setRows(rows)}).catch(()=>{if(epoch===generation.current)setError('Project associations unavailable. Reload to check your access.')}).finally(()=>{if(epoch===generation.current){lock.current=false;setBusy(false)}});return()=>{generation.current++}},[client,teamId,refresh])
 async function apply(){if(lock.current||!review)return;lock.current=true;setBusy(true);const epoch=generation.current;try{await client.changeAssociation(review.row.project_id,review.row.revision,review.action);if(epoch===generation.current){presentation?.notifyChanged();setRefresh(value=>value+1)}}catch{if(epoch===generation.current){setRows([]);setReview(undefined);setError('The association changed or your access changed. Reload before retrying.')}}finally{if(epoch===generation.current){lock.current=false;setBusy(false)}}}
 return <section className="settings-card presentation-editor"><h2>Project inheritance</h2><p>Review projects requesting this Team’s presentation defaults.</p><button disabled={busy} onClick={()=>setRefresh(value=>value+1)}>Reload project requests</button>{error&&<p role="alert">{error}</p>}{!busy&&!error&&!rows.length&&<p>No project associations.</p>}{rows.map(row=><div key={row.project_id}><p>{row.project_id} · {row.state}</p>{row.state==='proposed'&&<button disabled={busy||!!review} onClick={()=>setReview({row,action:'accept'})}>Review {row.project_id}</button>}<button disabled={busy||!!review} onClick={()=>setReview({row,action:'detach'})}>Detach {row.project_id}</button></div>)}{review&&<div><p>{review.action==='accept'?`Share this Team’s current and future presentation defaults with all current members of ${review.row.project_id}? They may override them in project or personal preferences.`:`Stop sharing defaults with ${review.row.project_id}?`}</p><p>This grants no Team membership, project membership or device access.</p><button disabled={busy} onClick={()=>void apply()}>{review.action==='accept'?'Accept project inheritance':'Confirm detach'}</button><button disabled={busy} onClick={()=>setReview(undefined)}>Cancel</button></div>}</section>
}
