import {TeamProjectReviews} from './ProjectTeamSettings'
import React,{useEffect,useRef,useState} from 'react'
import {TeamsClient,type TeamDetail,type TeamSummary} from '../../services/teams'
import type {PresentationSettingsClient} from '../../services/presentationSettings'
import {PresentationEditor} from '../settings/PresentationEditor'
export function TeamsPanel({client,presentation}:{client:TeamsClient;presentation?:PresentationSettingsClient}){
 const [teams,setTeams]=useState<TeamSummary[]>([]),[invitations,setInvitations]=useState<TeamSummary[]>([]),[selected,setSelected]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[review,setReview]=useState<TeamSummary>()
 const generation=useRef(0),locked=useRef(false),identity=client.identity()
 useEffect(()=>{const epoch=++generation.current;setTeams([]);setInvitations([]);setReview(undefined);setError('');setBusy(true);locked.current=true;Promise.all([client.list(),client.invitations()]).then(([teams,invitations])=>{if(epoch===generation.current){setTeams(teams);setInvitations(invitations);setSelected(current=>teams.some(team=>team.team_id===current)?current:'')}}).catch(()=>{if(epoch===generation.current)setError('Could not load your teams.')}).finally(()=>{if(epoch===generation.current){setBusy(false);locked.current=false}});return()=>{generation.current++}},[client,identity,revision])
 async function run(operation:()=>Promise<unknown>){if(locked.current)return;const epoch=generation.current;locked.current=true;setBusy(true);setError('');try{await operation();if(epoch===generation.current){setName('');setReview(undefined);setRevision(value=>value+1)}}catch{if(epoch===generation.current)setError('Team action failed. Refresh to inspect the latest state before retrying.')}finally{if(epoch===generation.current){locked.current=false;setBusy(false)}}}
 return <React.Fragment><section className="settings-card presentation-editor"><h2>Your teams</h2><button disabled={busy} onClick={()=>setRevision(value=>value+1)}>Refresh teams</button>{error&&<p role="alert">{error}</p>}<form onSubmit={event=>{event.preventDefault();void run(()=>client.create(name.trim()))}}><label>Team name<input maxLength={100} value={name} disabled={busy} onChange={event=>setName(event.target.value)}/></label><button disabled={busy||!name.trim()}>Create team</button></form><label>Team<select value={selected} disabled={busy} onChange={event=>setSelected(event.target.value)}><option value="">Choose a team</option>{teams.map(team=><option key={team.team_id} value={team.team_id}>{team.display_name}</option>)}</select></label></section>
 {invitations.length>0&&<section className="settings-card presentation-editor"><h2>Invitations</h2>{invitations.map(invitation=><div key={invitation.team_id}><p>{invitation.display_name} · {invitation.role}</p><button disabled={busy} onClick={()=>setReview(invitation)}>Review invitation</button></div>)}{review&&<div><p>Join {review.display_name} as {review.role}? This does not grant project or device access.</p><button disabled={busy} onClick={()=>void run(()=>client.accept(review.team_id,review.revision))}>Accept invitation</button><button disabled={busy} onClick={()=>setReview(undefined)}>Cancel</button></div>}</section>}
 {selected&&!busy&&client.associationsAvailable&&teams.some(team=>team.team_id===selected&&['owner','admin'].includes(team.viewer_role??''))&&<TeamProjectReviews key={'projects:'+selected+revision} client={client} teamId={selected} presentation={presentation}/>}
 {selected&&!busy&&<TeamRoster key={'roster:'+selected+revision} client={client} id={selected} onChanged={()=>setRevision(value=>value+1)} />}{selected&&presentation&&<PresentationEditor key={selected} client={presentation} scope="team" projectId={selected}/>}
 </React.Fragment>
}
function TeamRoster({client,id,onChanged}:{client:TeamsClient;id:string;onChanged:()=>void}){
 const [team,setTeam]=useState<TeamDetail>(),[subject,setSubject]=useState(''),[role,setRole]=useState('member'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[removing,setRemoving]=useState<string>()
 const live=useRef(true),locked=useRef(false)
 useEffect(()=>{live.current=true;client.read(id).then(value=>{if(live.current)setTeam(value)}).catch(()=>{if(live.current)setError('Team roster unavailable.')});return()=>{live.current=false}},[client,id])
 async function run(operation:()=>Promise<unknown>){if(locked.current)return;locked.current=true;setBusy(true);try{await operation();if(live.current)onChanged()}catch{if(live.current){setTeam(undefined);setError('Membership changed or the action failed. Refresh teams before retrying.')}}finally{if(live.current){locked.current=false;setBusy(false)}}}
 const manager=team&&['owner','admin'].includes(team.viewer_role??'')
 return <section className="settings-card presentation-editor"><h2>{team?.display_name??'Team'} · Members</h2>{error&&<p role="alert">{error}</p>}{team&&<><ul>{team.members.map(member=><li key={member.subject}>{member.subject} · {member.role} · {member.state}{manager&&member.role!=='owner'&&(team.viewer_role==='owner'||member.role==='member')&&<button disabled={busy} onClick={()=>setRemoving(member.subject)}>{member.state==='invited'?'Withdraw invitation':'Remove member'}</button>}</li>)}</ul>{manager&&<form onSubmit={event=>{event.preventDefault();void run(()=>client.invite(id,team.revision,subject.trim(),role))}}><label>Account ID<input value={subject} maxLength={200} disabled={busy} onChange={event=>setSubject(event.target.value)}/></label><label>Role<select value={role} disabled={busy} onChange={event=>setRole(event.target.value)}><option value="member">Member</option>{team.viewer_role==='owner'&&<option value="admin">Admin</option>}</select></label><button disabled={busy||!subject.trim()}>Invite member</button><p>The recipient must accept in OpenSaddle. No email is sent.</p></form>}{removing&&<div><p>Remove {removing} from this team? Team-based device consent will be rechecked.</p><button disabled={busy} onClick={()=>void run(()=>client.remove(id,team.revision,removing))}>Confirm removal</button><button disabled={busy} onClick={()=>setRemoving(undefined)}>Cancel</button></div>}</>}</section>
}
