import assert from'node:assert/strict'
import test from'node:test'
import{PersonalRuntimeClient,parsePersonalRuntime}from'./personalRuntime'
const status={schema_version:'opensaddle.personal-runtime.v1',service:'opensaddle',mode:'local',installation_id:'install-1',owner_subject:'owner',project:{project_id:'P',registry:'canonical_project_service',source_id:'source-1',source_revision:'rev-1',source_digest:'sha256:'+'a'.repeat(64),content_attested:false},lifecycle:'running',unresolved_assignments:[],workers:[{worker_id:'worker-1',adapter_id:'codex-app-server',state:'ready',pid:123,last_seen_at:'2026-09-08T01:00:00Z',readiness:{ready:true,reason:null,observed_at:'2026-09-08T01:00:00Z',expires_at:'2026-09-08T01:02:00Z'}}],knowledge:{available:false,reason:'provider_unavailable'},state_revision:3,updated_at:'2026-09-08T01:00:00Z'}
test('personal runtime parser preserves authoritative project lifecycle and readiness',()=>{const value=parsePersonalRuntime(status);assert.equal(value.project.projectId,'P');assert.equal(value.workers[0].readiness.ready,true);assert.equal(value.stateRevision,3)})
test('personal runtime parser rejects unknown and synthetic authority',()=>{assert.throws(()=>parsePersonalRuntime({...status,schema_version:'unknown'}));assert.throws(()=>parsePersonalRuntime({...status,project:{...status.project,content_attested:true}}));assert.throws(()=>parsePersonalRuntime({...status,state_revision:1.5}))})
test('personal runtime actions use exact negotiated routes, caller and CAS revision',async()=>{const original=globalThis.fetch;const requests:Request[]=[];globalThis.fetch=async(input,init)=>{requests.push(new Request(input,init));return Response.json(status)};try{const client=new PersonalRuntimeClient('https://core.example/',()=> 'owner','token');await client.status();await client.lifecycle('drain',3);assert.equal(new URL(requests[0].url).pathname,'/api/v2/personal-runtime');assert.equal(new URL(requests[1].url).pathname,'/api/v2/personal-runtime/lifecycle');assert.equal(requests[1].headers.get('X-OpenSaddle-User'),'owner');assert.equal(requests[1].headers.get('Authorization'),'Bearer token');assert.deepEqual(JSON.parse(await requests[1].text()),{action:'drain',expected_revision:3})}finally{globalThis.fetch=original}})
test('personal runtime preserves intervention-required Run leases',()=>{const next=parsePersonalRuntime({...status,lifecycle:'intervention_required',unresolved_assignments:[{run_id:'run-1',lease_epoch:2,lease_expires_at:'2026-09-08T02:00:00Z'}]});assert.equal(next.lifecycle,'intervention_required');assert.deepEqual(next.unresolvedAssignments,[{runId:'run-1',leaseEpoch:2,leaseExpiresAt:'2026-09-08T02:00:00Z'}])})
test('personal runtime recovery binds exact interrupted Run lease and revision',async()=>{const original=globalThis.fetch;let request!:Request;globalThis.fetch=async(input,init)=>{request=new Request(input,init);return Response.json(status)};try{await new PersonalRuntimeClient('https://core.example',()=> 'owner').recover('run-1',2,9);assert.equal(new URL(request.url).pathname,'/api/v2/personal-runtime/recovery');assert.deepEqual(JSON.parse(await request.text()),{run_id:'run-1',lease_epoch:2,expected_revision:9})}finally{globalThis.fetch=original}})
