import assert from'node:assert/strict';import test from'node:test';import{readFileSync}from'node:fs';import{RemoteJourneyClient}from'./remoteJourney'
const actualAuthorizedContextResponse=JSON.parse(readFileSync(new URL('./fixtures/authorized-context-packet.json',import.meta.url),'utf8'))
test('connected journey mutations preserve authenticated project and machine scope',async()=>{const original=globalThis.fetch,calls:Array<[string,RequestInit]> = [];globalThis.fetch=async(url,init)=>{calls.push([String(url),init??{}]);return new Response(JSON.stringify({ok:true}),{status:201,headers:{'Content-Type':'application/json'}})};try{const client=new RemoteJourneyClient('https://core.example/',()=> 'owner','private');await client.createProject('project-1');await client.addMember('project-1','member-2','member');await client.registerWorker({workerId:'machine-a',organizationId:'org-1',projectIds:['project-1'],runtimeKind:'remote_worker'});await client.createRun({projectId:'project-1',sourceId:'src_12345678',task:'Review the existing change'});assert.deepEqual(calls.map(([url])=>url),['https://core.example/api/v2/projects','https://core.example/api/v2/projects/project-1/members','https://core.example/api/v2/workers','https://core.example/api/v2/runs']);assert.ok(calls.every(([,init])=>(init.headers as Record<string,string>).Authorization==='Bearer private'));assert.match(String(calls[2][1].body),/"worker_id":"machine-a"/)}finally{globalThis.fetch=original}})
test('connected journey denial never becomes a success receipt',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({detail:'project owner or admin role required'}),{status:403,headers:{'Content-Type':'application/json'}});try{await assert.rejects(new RemoteJourneyClient('https://core.example',()=> 'member','token').addMember('project-1','other','member'),/project owner or admin role required/)}finally{globalThis.fetch=original}})
test('current roster is composed only from matching authenticated projections',async()=>{const original=globalThis.fetch;globalThis.fetch=async(url)=>new Response(JSON.stringify(String(url).endsWith('/members')?{project_id:'P',members:[{subject:'owner',role:'owner',status:'active'}]}:String(url).endsWith('/workers')?{project_id:'P',workers:[{worker_id:'machine-a',runtime_kind:'remote_worker',status:'unknown'}]}:{project_id:'P',invitations:[]}),{headers:{'Content-Type':'application/json'}});try{const value=await new RemoteJourneyClient('https://core.example',()=> 'owner','token').snapshot('P');assert.equal(value.members[0].subject,'owner');assert.equal(value.workers[0].workerId,'machine-a')}finally{globalThis.fetch=original}})
test('invitation acceptance is recipient and revision bound',async()=>{const original=globalThis.fetch;let call:[string,RequestInit]|undefined;globalThis.fetch=async(url,init)=>{call=[String(url),init??{}];return new Response(JSON.stringify({status:'accepted'}),{headers:{'Content-Type':'application/json'}})};try{await new RemoteJourneyClient('https://core.example',()=> 'member','token').acceptInvitation('P','invite-1',3);assert.equal(call?.[0],'https://core.example/api/v2/projects/P/invitations/invite-1/accept');assert.equal(call?.[1].body,JSON.stringify({expected_revision:3}))}finally{globalThis.fetch=original}})
test('recipient can load its pending invitation before Project membership',async()=>{const original=globalThis.fetch;globalThis.fetch=async(url)=>String(url).endsWith('/invitations')?new Response(JSON.stringify({project_id:'P',invitations:[{invitation_id:'I',recipient_subject:'member',status:'pending',revision:1,expires_at:'later'}]}),{headers:{'Content-Type':'application/json'}}):new Response(JSON.stringify({detail:'project membership required'}),{status:403,headers:{'Content-Type':'application/json'}});try{const value=await new RemoteJourneyClient('https://core.example',()=> 'member','token').snapshot('P');assert.equal(value.rosterAvailable,false);assert.equal(value.invitations[0].invitationId,'I');assert.deepEqual(value.members,[])}finally{globalThis.fetch=original}})
test('snapshot discovers bounded Project sources and active Runs without inventing an agent choice',async()=>{const original=globalThis.fetch;globalThis.fetch=async(url)=>{const path=new URL(String(url)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'owner',role:'owner',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources'))return Response.json({project_id:'P',items:[{source_id:'src-1',display_label:'git: main'}]});if(path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});return Response.json({active_runs:[{project_id:'P',run_id:'run-1',task:'Inspect change',status:'running',lease_epoch:1,requested_by:'owner',cancellation_requested:false}],outcomes:[]})};try{const value=await new RemoteJourneyClient('https://core.example',()=> 'owner','token').snapshot('P');assert.deepEqual(value.sources,[{sourceId:'src-1',label:'git: main'}]);assert.deepEqual(value.activeRuns,[{runId:'run-1',task:'Inspect change',status:'running',leaseEpoch:1,requestedBy:'owner',cancellationRequested:false}])}finally{globalThis.fetch=original}})
test('result cards use the authoritative Run task and worker instead of duplicate projection titles',async()=>{const original=globalThis.fetch;globalThis.fetch=async(url)=>{const path=new URL(String(url)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources')||path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});if(path.endsWith('/runs/run-1'))return Response.json({project_id:'P',run_id:'run-1',task:'Review auth boundary',status:'completed',assigned_worker_id:'machine-a',updated_at:'2026-09-07T19:00:00Z'});return Response.json({active_runs:[],outcomes:[{project_id:'P',run_id:'run-1',title:'Run completed with artifact evidence',verified:false,artifact_available:true}]})};try{const value=await new RemoteJourneyClient('https://core.example',()=> 'member','token').snapshot('P');assert.deepEqual(value.results,[{runId:'run-1',title:'Review auth boundary',verified:false,artifactAvailable:true,workerId:'machine-a',status:'completed',updatedAt:'2026-09-07T19:00:00Z'}])}finally{globalThis.fetch=original}})
test('capacity transport reads exact Project status and configures limits with current caller authority',async()=>{const original=globalThis.fetch,requests:Array<{path:string;method:string;body?:unknown;user:string|null}>=[];globalThis.fetch=async(input,init)=>{const request=new Request(input,init),path=new URL(request.url).pathname;requests.push({path,method:request.method,body:request.method==='PUT'?JSON.parse(await request.clone().text()):undefined,user:request.headers.get('X-OpenSaddle-User')});if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'owner',role:'owner',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources')||path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});if(path.endsWith('/capacity'))return Response.json({schema_version:'opensaddle.resource-capacity.v1',project_id:'P',accounting_enforced:true,state:'configured',admission_state:'idle',overcommit:null,limits:{cpu_millicores:2000,memory_mib:4096,max_concurrency:2},revision:1,usage:{cpu_millicores:500,memory_mib:1024,concurrency:1},available:{cpu_millicores:1500,memory_mib:3072,concurrency:1},workers:[],reservations:[],recent_releases:[],queued_admission:[],generated_at:'2026-09-07T22:00:00Z',pending_phases:['monetary_budgets','interactive_reserve','fairness']});if(path.endsWith('/capacity-limits'))return Response.json({schema_version:'opensaddle.resource-capacity.v1',project_id:'P',cpu_millicores:3000,memory_mib:6000,max_concurrency:3,revision:2});return Response.json({active_runs:[],outcomes:[]})};try{const client=new RemoteJourneyClient('https://core.example',()=> 'owner','private',true),snapshot=await client.snapshot('P');assert.deepEqual(snapshot.capacity?.available,{cpuMillicores:1500,memoryMiB:3072,concurrency:1});await client.configureCapacity('P',{cpuMillicores:3000,memoryMiB:6000,maxConcurrency:3});assert.deepEqual(requests.at(-1),{path:'/api/v2/projects/P/capacity-limits',method:'PUT',body:{cpu_millicores:3000,memory_mib:6000,max_concurrency:3},user:'owner'});assert.ok(requests.every(item=>item.user==='owner'))}finally{globalThis.fetch=original}})
test('malformed capacity never becomes invented zero usage',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input)=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'member',role:'member',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources')||path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});if(path.endsWith('/capacity'))return Response.json({schema_version:'opensaddle.resource-capacity.v1',project_id:'P',state:'configured',admission_state:'idle',limits:{},usage:null,available:null,pending_phases:[]});return Response.json({active_runs:[],outcomes:[]})};try{const snapshot=await new RemoteJourneyClient('https://core.example',()=> 'member',undefined,true).snapshot('P');assert.equal(snapshot.capacity,undefined);assert.match(snapshot.capacityError!,/enforcement is invalid/)}finally{globalThis.fetch=original}})
test('established member reads the Project when invitation administration is denied',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input)=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({detail:'invitation recipient or project owner required'},{status:403});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'member',role:'member',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources')||path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});return Response.json({active_runs:[],outcomes:[]})};try{const snapshot=await new RemoteJourneyClient('https://core.example',()=> 'member').snapshot('P');assert.equal(snapshot.rosterAvailable,true);assert.deepEqual(snapshot.invitations,[]);assert.equal(snapshot.canManage,false)}finally{globalThis.fetch=original}})

test('native readiness is strictly source-bound and selected adapter is sent exactly',async()=>{const original=globalThis.fetch,calls:Array<{path:string;body?:unknown}>=[];globalThis.fetch=async(input,init)=>{const request=new Request(input,init),path=new URL(request.url).pathname;calls.push({path,body:request.method==='POST'?JSON.parse(await request.clone().text()):undefined});if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'member',role:'member',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources'))return Response.json({project_id:'P',items:[{source_id:'src_12345678',display_label:'snapshot'}]});if(path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});if(path.endsWith('/native-adapters'))return Response.json({schema_version:'opensaddle.native-adapter-readiness.v1',project_id:'P',generated_at:'2026-09-07T23:00:00Z',items:[{schema_version:'opensaddle.native-adapter-readiness.v1',worker_id:'machine-a',project_id:'P',adapter_id:'codex-app-server',source_id:'src_12345678',revision:'rev-1',digest:'d'.repeat(64),executable_state:'installed',executable_version:'0.147.0',authentication_state:'authenticated',account_mode:'chatgpt',protocol_state:'compatible',protocol_version:'app-server-v1',workspace_state:'configured',ready:true,reason:null,observed_at:'2026-09-07T23:00:00Z',expires_at:'2026-09-07T23:02:00Z',reported_at:'2026-09-07T23:00:01Z'}]});if(path==='/api/v2/runs')return Response.json({run_id:'run-1',project_id:'P'},{status:201});return Response.json({active_runs:[],outcomes:[]})};try{const client=new RemoteJourneyClient('https://core.example',()=> 'member','token',false,true),snapshot=await client.snapshot('P');assert.equal(snapshot.nativeAdapters?.[0].ready,true);assert.equal(snapshot.nativeAdapters?.[0].sourceId,'src_12345678');await client.delegate('P','src_12345678','Read fact','codex-app-server');assert.match(String((calls.at(-1)?.body as Record<string,unknown>).idempotency_key),/^[a-f0-9-]{36}$/);delete (calls.at(-1)?.body as Record<string,unknown>).idempotency_key;assert.deepEqual(calls.at(-1),{path:'/api/v2/runs',body:{project_id:'P',source_id:'src_12345678',task:'Read fact',native_adapter_id:'codex-app-server'}})}finally{globalThis.fetch=original}})

test('malformed native readiness cannot synthesize an available agent',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input)=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'member',role:'member',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources')||path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});if(path.endsWith('/native-adapters'))return Response.json({schema_version:'opensaddle.native-adapter-readiness.v1',project_id:'P',generated_at:'later',items:[{ready:true}]});return Response.json({active_runs:[],outcomes:[]})};try{const snapshot=await new RemoteJourneyClient('https://core.example',()=> 'member',undefined,false,true).snapshot('P');assert.equal(snapshot.nativeAdapters,undefined);assert.match(snapshot.nativeAdaptersError!,/generation time is invalid/)}finally{globalThis.fetch=original}})

// INV-AUTHORIZED-CONTEXT-INSPECTOR: current-authorized packet must match the admitted immutable handle.
test('authorized context Inspector reads an actual Knowledge packet and permitted evidence',async()=>{const original=globalThis.fetch,response=structuredClone(actualAuthorizedContextResponse),packet=response.packet;response.core_binding.project_id='P';response.core_binding.run_id='run-1';globalThis.fetch=async(input)=>{assert.equal(new URL(String(input)).pathname,'/api/v2/runs/run-1/authorized-context-packet');return Response.json(response)};try{const value=await new RemoteJourneyClient('https://core.example',()=> 'member','token',false,false,true).authorizedContextPacket('P','run-1',{packetDigest:packet.packet_digest,requestDigest:packet.request_digest,capabilityId:packet.capability_id,capabilityVersion:packet.capability_version,capabilityDescriptorDigest:packet.capability_descriptor_digest});assert.equal(value.packetDigest,packet.packet_digest);assert.equal(value.packetId,packet.packet_id);assert.equal(value.assertions[0].text,packet.context.assertions[0].text);assert.equal(value.citations[0].content,packet.context.evidence.items[0].excerpt);assert.equal(value.citations[0].locator,packet.context.evidence.items[0].locator)}finally{globalThis.fetch=original}})

test('authorized context Inspector rejects substituted packet and coarse denial',async()=>{const original=globalThis.fetch,d='sha256:'+'d'.repeat(64),r='sha256:'+'e'.repeat(64),c='sha256:'+'c'.repeat(64),handle={packetDigest:d,requestDigest:r,capabilityId:'krail.authorized-context-packet',capabilityVersion:'1.0.0',capabilityDescriptorDigest:c};try{globalThis.fetch=async()=>Response.json({available:false,packet:null,reauthorization:null,reason:'context_packet_unavailable'},{status:409});await assert.rejects(new RemoteJourneyClient('https://core.example',()=> 'member',undefined,false,false,true).authorizedContextPacket('P','run-1',handle),/context_packet_unavailable/);globalThis.fetch=async()=>Response.json({available:true,packet:{},reauthorization:{}});await assert.rejects(new RemoteJourneyClient('https://core.example',()=> 'member',undefined,false,false,true).authorizedContextPacket('P','run-1',handle),/invalid|does not match/)}finally{globalThis.fetch=original}})

test('delegation sends only explicitly selected authorized context sources',async()=>{const original=globalThis.fetch;let body:unknown;globalThis.fetch=async(input,init)=>{assert.equal(new URL(String(input)).pathname,'/api/v2/runs');body=JSON.parse(String(init?.body));return Response.json({run_id:'run-context',project_id:'P'},{status:201})};try{await new RemoteJourneyClient('https://core.example',()=> 'member','token',false,false,true).delegate('P','source-main','Use selected context','codex-app-server',['source-main','source-issue']);assert.match(String((body as Record<string,unknown>).idempotency_key),/^[a-f0-9-]{36}$/);delete (body as Record<string,unknown>).idempotency_key;assert.deepEqual(body,{project_id:'P',source_id:'source-main',task:'Use selected context',native_adapter_id:'codex-app-server',authorized_context_source_ids:['source-main','source-issue']})}finally{globalThis.fetch=original}})

test('authorized context Inspector rejects hidden nested refs and wrong Core route binding',async()=>{const original=globalThis.fetch,response=structuredClone(actualAuthorizedContextResponse),packet=response.packet,handle={packetDigest:packet.packet_digest,requestDigest:packet.request_digest,capabilityId:packet.capability_id,capabilityVersion:packet.capability_version,capabilityDescriptorDigest:packet.capability_descriptor_digest};try{response.core_binding.project_id='wrong-project';response.core_binding.run_id='run-1';globalThis.fetch=async()=>Response.json(response);await assert.rejects(new RemoteJourneyClient('https://core.example',()=> 'member',undefined,false,false,true).authorizedContextPacket('P','run-1',handle),/Core Project|does not match/);const substituted=structuredClone(actualAuthorizedContextResponse),ref=structuredClone(substituted.packet.context.repository);ref.resource_id='hidden-resource';ref.digest='sha256:'+'9'.repeat(64);substituted.core_binding.project_id='P';substituted.core_binding.run_id='run-1';substituted.packet.context.freshness.push({source:ref,status:'fresh',basis:'substituted',processing_version:'krail.context-freshness.v1'});globalThis.fetch=async()=>Response.json(substituted);await assert.rejects(new RemoteJourneyClient('https://core.example',()=> 'member',undefined,false,false,true).authorizedContextPacket('P','run-1',handle),/outside admitted evidence/)}finally{globalThis.fetch=original}})

test('snapshot discovers immutable Knowledge sources separately from the runtime Run source',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input)=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'member',role:'member',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources'))return Response.json({project_id:'P',items:[{source_id:'runtime-workspace',display_label:'working tree'}]});if(path.endsWith('/authorized-context-sources'))return Response.json({schema_version:'opensaddle.authorized-context-source-list.v1',project_id:'P',items:[{source_id:'knowledge-version-1',classification:'internal',source_version:'commit-abc',resource_ref:{authority:'file:/fixture',resource_type:'document',resource_id:'docs/readme.md',version:'commit-abc',digest:'sha256:'+'1'.repeat(64)},immutable:true,provider_freshness:'rechecked_at_packet_create_and_read'}]});if(path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});return Response.json({active_runs:[],outcomes:[]})};try{const snapshot=await new RemoteJourneyClient('https://core.example',()=> 'member',undefined,false,false,true).snapshot('P');assert.deepEqual(snapshot.sources,[{sourceId:'runtime-workspace',label:'working tree'}]);assert.deepEqual(snapshot.authorizedContextSources,[{sourceId:'knowledge-version-1',label:'docs/readme.md',version:'commit-abc',classification:'internal'}]);assert.equal(snapshot.authorizedContextSourcesAvailable,true)}finally{globalThis.fetch=original}})

test('malformed Knowledge discovery is unavailable and never falls back to runtime source IDs',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input)=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources'))return Response.json({project_id:'P',items:[{source_id:'runtime-only',display_label:'workspace'}]});if(path.endsWith('/authorized-context-sources'))return Response.json({schema_version:'opensaddle.authorized-context-source-list.v1',project_id:'wrong',items:[]});if(path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});return Response.json({active_runs:[],outcomes:[]})};try{const snapshot=await new RemoteJourneyClient('https://core.example',()=> 'member',undefined,false,false,true).snapshot('P');assert.equal(snapshot.authorizedContextSources,undefined);assert.equal(snapshot.authorizedContextSourcesAvailable,false);assert.match(snapshot.authorizedContextSourcesError!,/source list is invalid/);assert.deepEqual(snapshot.sources,[{sourceId:'runtime-only',label:'workspace'}])}finally{globalThis.fetch=original}})

class TestStorage implements Storage { private values=new Map<string,string>();get length(){return this.values.size}clear(){this.values.clear()}getItem(key:string){return this.values.get(key)??null}key(index:number){return [...this.values.keys()][index]??null}removeItem(key:string){this.values.delete(key)}setItem(key:string,value:string){this.values.set(key,value)} }

test('portable continuation response loss reload replays the identical durable intent',async()=>{const original=globalThis.fetch,storage=new TestStorage(),requests:unknown[]=[];let lose=true;globalThis.fetch=async(input,init)=>{const path=new URL(String(input)).pathname;if(path.endsWith('/continuations')){requests.push(JSON.parse(String(init?.body)));if(lose){lose=false;throw Error('response lost')}return Response.json({continuation_id:'cont-1',run_id:'run-paused'},{status:201})}throw Error(`unexpected ${path}`)};const checkpoint={checkpointId:'chk_'+'1'.repeat(32),checkpointDigest:'2'.repeat(64),sourceLeaseEpoch:1,sourceWorkerId:'machine-a',createdAt:'2026-09-08T02:00:00Z'};try{const first=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,storage),intent=first.preparePortableContinuation('P','run-paused',checkpoint,'machine-b');await assert.rejects(first.continuePortable('P','run-paused',intent),/response lost/);const reloaded=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,storage);await reloaded.continuePortable('P','run-paused',intent);assert.deepEqual(requests,[requests[0],requests[0]]);assert.equal(storage.length,0)}finally{globalThis.fetch=original}})

test('portable continuation storage failure submits no request',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({})};const broken={length:0,clear(){},getItem(){return null},key(){return null},removeItem(){},setItem(){throw Error('disk full')}} satisfies Storage;try{const client=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,broken),checkpoint={checkpointId:'chk_'+'1'.repeat(32),checkpointDigest:'2'.repeat(64),sourceLeaseEpoch:1,sourceWorkerId:'machine-a',createdAt:'2026-09-08T02:00:00Z'};assert.throws(()=>client.preparePortableContinuation('P','run-paused',checkpoint,'machine-b'),/nothing was submitted/);assert.equal(calls,0)}finally{globalThis.fetch=original}})

test('paused Run snapshot exposes only strict current checkpoints and scoped pending intent',async()=>{const original=globalThis.fetch,storage=new TestStorage(),client=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,storage),checkpoint={checkpointId:'chk_'+'1'.repeat(32),checkpointDigest:'2'.repeat(64),sourceLeaseEpoch:1,sourceWorkerId:'machine-a',createdAt:'2026-09-08T02:00:00Z'},intent=client.preparePortableContinuation('P','run-paused',checkpoint,'machine-b');globalThis.fetch=async input=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'owner',role:'owner',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[{worker_id:'machine-b',runtime_kind:'remote_worker',status:'ready'}]});if(path.endsWith('/participants')||path.endsWith('/sources'))return Response.json({project_id:'P',items:[]});if(path.endsWith('/checkpoints'))return Response.json({schema_version:'opensaddle.run-checkpoints.v1',run_id:'run-paused',items:[{checkpoint_id:checkpoint.checkpointId,checkpoint_digest:checkpoint.checkpointDigest,source_lease_epoch:1,created_by_worker_id:'machine-a',created_at:checkpoint.createdAt}]});return Response.json({active_runs:[{project_id:'P',run_id:'run-paused',task:'Continue me',status:'paused',lease_epoch:2,requested_by:'requester',cancellation_requested:false}],outcomes:[]})};try{const snapshot=await client.snapshot('P');assert.deepEqual(snapshot.activeRuns?.[0].checkpoints,[checkpoint]);assert.deepEqual(snapshot.activeRuns?.[0].pendingContinuation,intent);assert.equal(snapshot.portableContinuationAvailable,true);assert.equal(snapshot.nativeSessionResume,false)}finally{globalThis.fetch=original}})

test('response-loss intent remains visible after Core has already queued the same Run',async()=>{const original=globalThis.fetch,storage=new TestStorage(),client=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,storage),checkpoint={checkpointId:'chk_'+'1'.repeat(32),checkpointDigest:'2'.repeat(64),sourceLeaseEpoch:1,sourceWorkerId:'machine-a',createdAt:'2026-09-08T02:00:00Z'},intent=client.preparePortableContinuation('P','run-queued',checkpoint,'machine-b');globalThis.fetch=async input=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'owner',role:'owner',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[{worker_id:'machine-b',runtime_kind:'remote_worker',status:'ready'}]});if(path.endsWith('/participants')||path.endsWith('/sources'))return Response.json({project_id:'P',items:[]});return Response.json({active_runs:[{project_id:'P',run_id:'run-queued',task:'Continue me',status:'queued',lease_epoch:2,requested_by:'requester',cancellation_requested:false}],outcomes:[]})};try{const snapshot=await client.snapshot('P');assert.deepEqual(snapshot.activeRuns?.[0].pendingContinuation,intent);assert.equal(snapshot.activeRuns?.[0].status,'queued')}finally{globalThis.fetch=original}})

test('portable continuation retains ambiguous server failures and clears definitive rejection',async()=>{const original=globalThis.fetch,storage=new TestStorage(),client=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,storage),checkpoint={checkpointId:'chk_'+'1'.repeat(32),checkpointDigest:'2'.repeat(64),sourceLeaseEpoch:1,sourceWorkerId:'machine-a',createdAt:'2026-09-08T02:00:00Z'},intent=client.preparePortableContinuation('P','run-paused',checkpoint,'machine-b');try{globalThis.fetch=async()=>Response.json({detail:'temporarily unavailable'},{status:503});await assert.rejects(client.continuePortable('P','run-paused',intent),/temporarily unavailable/);assert.equal(storage.length,1);globalThis.fetch=async()=>Response.json({detail:'checkpoint is stale'},{status:409});await assert.rejects(client.continuePortable('P','run-paused',intent),/checkpoint is stale/);assert.equal(storage.length,0)}finally{globalThis.fetch=original}})

test('preparing again preserves the unresolved exact continuation intent',()=>{const storage=new TestStorage(),client=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,storage),checkpoint={checkpointId:'chk_'+'1'.repeat(32),checkpointDigest:'2'.repeat(64),sourceLeaseEpoch:1,sourceWorkerId:'machine-a',createdAt:'2026-09-08T02:00:00Z'},first=client.preparePortableContinuation('P','run-paused',checkpoint,'machine-b'),second=client.preparePortableContinuation('P','run-paused',checkpoint,'machine-c');assert.deepEqual(second,first);assert.equal(second.targetWorkerId,'machine-b')})

test('broken continuation storage enumeration stays local to recovery',async()=>{const original=globalThis.fetch,storage={length:1,clear(){},getItem(){return null},key(){throw new DOMException('blocked','SecurityError')},removeItem(){},setItem(){}} satisfies Storage,client=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,storage);globalThis.fetch=async input=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'owner',role:'owner',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/participants')||path.endsWith('/sources'))return Response.json({project_id:'P',items:[]});return Response.json({active_runs:[],outcomes:[]})};try{const snapshot=await client.snapshot('P');assert.match(snapshot.portableContinuationError!,/storage is unavailable/);assert.deepEqual(snapshot.activeRuns,[])}finally{globalThis.fetch=original}})

test('inaccessible saved continuation does not hide other Runs or submit',async()=>{const original=globalThis.fetch,storage=new TestStorage(),client=new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,true,false,storage),checkpoint={checkpointId:'chk_'+'1'.repeat(32),checkpointDigest:'2'.repeat(64),sourceLeaseEpoch:1,sourceWorkerId:'machine-a',createdAt:'2026-09-08T02:00:00Z'};client.preparePortableContinuation('P','run-denied',checkpoint,'machine-b');globalThis.fetch=async input=>{const path=new URL(String(input)).pathname;if(path.endsWith('/runs/run-denied'))return Response.json({detail:'forbidden'},{status:403});if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'owner',role:'owner',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/participants')||path.endsWith('/sources'))return Response.json({project_id:'P',items:[]});return Response.json({active_runs:[{project_id:'P',run_id:'run-other',task:'Other',status:'queued',lease_epoch:0,requested_by:'owner',cancellation_requested:false}],outcomes:[]})};try{const snapshot=await client.snapshot('P');assert.equal(snapshot.activeRuns?.[0].runId,'run-other');assert.match(snapshot.portableContinuationError!,/forbidden/);assert.equal(storage.length,1)}finally{globalThis.fetch=original}})

function intentStorage(): Storage {
  const values = new Map<string, string>()
  return { get length() { return values.size }, clear: () => values.clear(), key: index => [...values.keys()][index] ?? null, getItem: key => values.get(key) ?? null, setItem: (key, value) => { values.set(key, value) }, removeItem: key => { values.delete(key) } }
}

test('lost accepted delegation response reopens with same exact key and creates one Run', async () => {
  const original = globalThis.fetch, storage = intentStorage(), runs = new Map<string, string>(), bodies: string[] = []
  let lost = false
  globalThis.fetch = async (_url, init) => {
    const body = JSON.parse(String(init?.body)); bodies.push(String(init?.body))
    if (!runs.has(body.idempotency_key)) runs.set(body.idempotency_key, `run-${runs.size + 1}`)
    if (!lost) { lost = true; throw Error('accepted response lost') }
    return Response.json({ project_id: body.project_id, run_id: runs.get(body.idempotency_key) })
  }
  const client = () => new RemoteJourneyClient('https://core.example', () => 'owner', undefined, false, false, false, false, false, storage)
  try {
    await assert.rejects(client().delegate('P', 'source', 'Fix the real bug', 'codex-app-server', ['doc-v1']), /response lost/)
    assert.equal(storage.length, 1)
    const retry = await client().delegate('P', 'source', 'Fix the real bug', 'codex-app-server', ['doc-v1'])
    assert.equal(retry.run_id, 'run-1'); assert.equal(runs.size, 1); assert.equal(bodies[0], bodies[1]); assert.equal(storage.length, 0)
    await client().delegate('P', 'source', 'Fix the real bug', 'codex-app-server', ['doc-v1'])
    assert.equal(runs.size, 2); assert.notEqual(bodies[1], bodies[2])
  } finally { globalThis.fetch = original }
})

test('changed task source project provider knowledge or caller never reuses an unknown intent', async () => {
  const original = globalThis.fetch, storage = intentStorage(), keys: string[] = []
  let subject = 'owner'
  globalThis.fetch = async (_url, init) => { keys.push(JSON.parse(String(init?.body)).idempotency_key); throw Error('unknown response') }
  const client = new RemoteJourneyClient('https://core.example', () => subject, undefined, false, false, false, false, false, storage)
  try {
    const submissions: Parameters<RemoteJourneyClient['delegate']>[] = [
      ['P','source','task','codex-app-server',['doc']], ['P','source','changed','codex-app-server',['doc']],
      ['P','other','task','codex-app-server',['doc']], ['Q','source','task','codex-app-server',['doc']],
      ['P','source','task','claude-code-stream-json',['doc']], ['P','source','task','codex-app-server',['other-doc']],
    ]
    for (const args of submissions) await assert.rejects(client.delegate(...args), /unknown response/)
    subject = 'other-owner'; await assert.rejects(client.delegate(...submissions[0]), /unknown response/)
    assert.equal(new Set(keys).size, 7)
    subject = 'owner'; await assert.rejects(client.delegate(...submissions[0]), /unknown response/)
    assert.equal(keys.at(-1), keys[0])
  } finally { globalThis.fetch = original }
})

test('pending conflict and substituted response retain the exact delegation intent', async () => {
  const original = globalThis.fetch, storage = intentStorage(), keys: string[] = []
  globalThis.fetch = async (_url, init) => {
    keys.push(JSON.parse(String(init?.body)).idempotency_key)
    return keys.length === 1 ? Response.json({detail:{code:'run_submission_pending'}},{status:409}) : Response.json({run_id:'run-other',project_id:'other'})
  }
  try {
    const client = new RemoteJourneyClient('https://core.example', () => 'owner', undefined, false, false, false, false, false, storage)
    await assert.rejects(client.delegate('P','source','task'), /409/)
    await assert.rejects(client.delegate('P','source','task'), /identity is invalid/)
    assert.equal(keys[0],keys[1]); assert.equal(storage.length,1)
  } finally { globalThis.fetch = original }
})

test('delegation storage failure sends no task', async () => {
  const original = globalThis.fetch, storage = intentStorage(); let calls = 0
  storage.setItem = () => { throw Error('storage denied') }
  globalThis.fetch = async () => { calls++; return Response.json({}) }
  try {
    const client = new RemoteJourneyClient('https://core.example', () => 'owner', undefined, false, false, false, false, false, storage)
    await assert.rejects(client.delegate('P','source','task'), /nothing was submitted/)
    assert.equal(calls,0)
  } finally { globalThis.fetch = original }
})

test('coding task argument changes cannot reuse a lost-response execution intent', async () => {
  const original = globalThis.fetch, storage = intentStorage(), bodies: Record<string,unknown>[] = []
  globalThis.fetch = async (_url,init) => { bodies.push(JSON.parse(String(init?.body))); throw Error('unknown response') }
  const client = new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,false,false,storage)
  const task = { schema_version:'opensaddle.coding-task.v1' as const,allowed_paths:['file.py'],verification_commands:[['python','-m','pytest']] }
  try {
    await assert.rejects(client.delegate('P','source','Fix bug','codex-app-server',['doc'],task))
    await assert.rejects(client.delegate('P','source','Fix bug','codex-app-server',['doc'],task))
    await assert.rejects(client.delegate('P','source','Fix bug','codex-app-server',['doc'],{...task,verification_commands:[['python','-m','pytest','-q']]}))
    assert.deepEqual(bodies[0].coding_task,task)
    assert.equal(bodies[0].idempotency_key,bodies[1].idempotency_key)
    assert.notEqual(bodies[0].idempotency_key,bodies[2].idempotency_key)
  } finally { globalThis.fetch = original }
})

test('private registered Git source classification remains private in launch discovery',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input)=>{const path=new URL(String(input)).pathname;if(path.endsWith('/invitations'))return Response.json({project_id:'P',invitations:[]});if(path.endsWith('/members'))return Response.json({project_id:'P',members:[{subject:'member',role:'member',status:'active'}]});if(path.endsWith('/workers'))return Response.json({project_id:'P',workers:[]});if(path.endsWith('/sources'))return Response.json({project_id:'P',items:[{source_id:'runtime-workspace',display_label:'working tree'}]});if(path.endsWith('/authorized-context-sources'))return Response.json({schema_version:'opensaddle.authorized-context-source-list.v1',project_id:'P',items:[{source_id:'knowledge-version-1',classification:'private',source_version:'commit-abc',resource_ref:{authority:'file:/fixture',resource_type:'document',resource_id:'docs/readme.md',version:'commit-abc',digest:'sha256:'+'1'.repeat(64)},immutable:true,provider_freshness:'rechecked_at_packet_create_and_read'}]});if(path.endsWith('/participants'))return Response.json({project_id:'P',items:[]});return Response.json({active_runs:[],outcomes:[]})};try{const snapshot=await new RemoteJourneyClient('https://core.example',()=> 'member',undefined,false,false,true).snapshot('P');assert.deepEqual(snapshot.sources,[{sourceId:'runtime-workspace',label:'working tree'}]);assert.deepEqual(snapshot.authorizedContextSources,[{sourceId:'knowledge-version-1',label:'docs/readme.md',version:'commit-abc',classification:'private'}]);assert.equal(snapshot.authorizedContextSourcesAvailable,true)}finally{globalThis.fetch=original}})

test('structured admission failures explain recovery without exposing arbitrary details or replacing the retry intent', async () => {
  const original = globalThis.fetch, storage = intentStorage(), keys: string[] = []
  const failures = [
    {code:'run_submission_pending',status:409,expected:/earlier submission is still pending/},
    {code:'run_idempotency_conflict',status:409,expected:/bound to different arguments/},
    {code:'selected_context_budget_exceeded',status:422,expected:/Select fewer documents or shorten the task/},
    {code:'coding_execution_unavailable',status:422,expected:/Workspace changes are unavailable/},
    {code:'authorized_context_packet_access_denied',status:503,expected:/knowledge is unavailable or no longer authorized/},
  ]
  let index = 0
  globalThis.fetch = async (_url,init) => { keys.push(JSON.parse(String(init?.body)).idempotency_key); const failure=failures[index++]; return Response.json({detail:{code:failure.code,message:'UNTRUSTED-MESSAGE',debug:{credential:'DO-NOT-DISPLAY'}}},{status:failure.status}) }
  try {
    const client = new RemoteJourneyClient('https://core.example',()=> 'owner',undefined,false,false,false,false,false,storage)
    for (const failure of failures) await assert.rejects(client.delegate('P','source','same task'), (error:Error) => { assert.match(error.message,failure.expected); assert.match(error.message,new RegExp(failure.code)); assert.doesNotMatch(error.message,/UNTRUSTED-MESSAGE|DO-NOT-DISPLAY|credential/); return true })
    assert.equal(new Set(keys).size,1); assert.equal(storage.length,1)
    globalThis.fetch = async()=>Response.json({detail:{code:'unknown_code',message:'DO-NOT-DISPLAY'}},{status:503})
    await assert.rejects(client.delegate('P','source','same task'), /^Error: Connected journey request failed \(503\)$/)
  } finally { globalThis.fetch = original }
})

test('plain server errors remain readable and bounded',async()=>{
  const original=globalThis.fetch
  globalThis.fetch=async()=>Response.json({detail:'Readable denial\n'+'x'.repeat(2000)},{status:403})
  try{await assert.rejects(new RemoteJourneyClient('https://core.example',()=> 'owner').createProject('P'),(error:Error)=>{assert.match(error.message,/^Readable denial /);assert.equal(error.message.length,512);return true})}finally{globalThis.fetch=original}
})

test('Run detail uses authoritative status and scoped cancellation authority without legacy runtime calls',async()=>{
 const original=globalThis.fetch,paths:string[]=[];let subject='owner'
 globalThis.fetch=async(input)=>{const path=new URL(String(input)).pathname;paths.push(path);return Response.json(path.endsWith('/members')?{project_id:'P',members:[{subject:'owner',role:'owner',status:'active'}]}:{run_id:'run-real',project_id:'P',task:'Actual task',status:'running',requested_by:'requester',cancellation_requested:true,policy:{obligations:{coding_task:{schema_version:'opensaddle.coding-task.v1'}}}})}
 try{const client=new RemoteJourneyClient('https://core.example',()=>subject);let value=await client.runDetail('run-real');assert.equal(value.canCancel,true);assert.equal(value.cancellationRequested,true);assert.equal(value.status,'running');assert.equal(value.codingTask,true);subject='other';value=await client.runDetail('run-real');assert.equal(value.canCancel,false);assert.ok(paths.every(path=>path.startsWith('/api/v2/')));globalThis.fetch=async()=>Response.json({run_id:'other',project_id:'P'});await assert.rejects(client.runDetail('run-real'),/identity or status/)}finally{globalThis.fetch=original}
})
