import type { ExactArtifactRef, Participant, ParticipantClient, ParticipantMessage } from './contracts'
const asObj=(v:unknown)=>v as Record<string,unknown>; const s=(v:unknown,n:string)=>{if(typeof v!=='string'||!v)throw Error(n);return v}; const n=(v:unknown,nm:string)=>{if(!Number.isInteger(v))throw Error(nm);return v as number}
export class RemoteParticipantClient implements ParticipantClient {
  private readonly base:string; private readonly user:()=>string; private readonly token?:string
  constructor(base:string,user:()=>string,token?:string){this.base=base;this.user=user;this.token=token}
  private async call(path:string,init?:RequestInit){const r=await fetch(`${this.base.replace(/\/$/,'')}${path}`,{...init,headers:{'Content-Type':'application/json','X-OpenSaddle-User':this.user(),...(this.token?{Authorization:`Bearer ${this.token}`}:{}),...init?.headers}});if(!r.ok){const x=await r.json().catch(()=>null)as {detail?:string}|null;throw Error(x?.detail??`Participant request failed (${r.status})`)}return r.json()}
  private p(v:unknown):Participant{const x=asObj(v),lifecycle=s(x.lifecycle,'lifecycle');if(!['waiting','paused','retired'].includes(lifecycle))throw Error('participant lifecycle');return {participantId:s(x.participant_id,'participant id'),projectId:s(x.project_id,'project id'),source:s(x.source,'source'),ownerSubject:s(x.owner_subject,'owner subject'),title:s(x.title,'title'),commandId:s(x.command_id,'command'),commandVersion:n(x.command_version,'command version'),commandDescriptorDigest:s(x.command_descriptor_digest,'command descriptor digest'),lifecycle:lifecycle as Participant['lifecycle'],revision:n(x.revision,'revision')}}
  private m(v:unknown):ParticipantMessage{const x=asObj(v),r=asObj(x.resource);return {messageId:s(x.message_id,'message id'),participantId:s(x.participant_id,'participant id'),projectId:s(x.project_id,'project id'),status:s(x.status,'status'),runId:s(x.run_id,'run id'),invocationId:typeof x.invocation_id==='string'?x.invocation_id:undefined,resource:{project_id:s(r.project_id,'project'),run_id:s(r.run_id,'run'),artifact_id:s(r.artifact_id,'artifact'),digest:s(r.digest,'digest')},input:asObj(x.input)}}
  async create(projectId:string,input:{source:string;title:string;commandId:string}){return this.p(await this.call(`/api/v2/projects/${encodeURIComponent(projectId)}/participants`,{method:'POST',body:JSON.stringify({source:input.source,title:input.title,command_id:input.commandId})}))}
  async get(id:string){return this.p(await this.call(`/api/v2/participants/${encodeURIComponent(id)}`))}
  async lifecycle(id:string,revision:number,lifecycle:Participant['lifecycle']){return this.p(await this.call(`/api/v2/participants/${encodeURIComponent(id)}/lifecycle`,{method:'PUT',body:JSON.stringify({expected_revision:revision,lifecycle})}))}
  async send(id:string,revision:number,resource:ExactArtifactRef,input:Record<string,unknown>,key:string){return this.m(await this.call(`/api/v2/participants/${encodeURIComponent(id)}/messages`,{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify({expected_participant_revision:revision,resource,input})}))}
  async message(id:string){return this.m(await this.call(`/api/v2/participant-messages/${encodeURIComponent(id)}`))}
  async messages(id:string){const x=asObj(await this.call(`/api/v2/participants/${encodeURIComponent(id)}/messages?limit=50`));return(Array.isArray(x.items)?x.items:[]).map(v=>this.m(v))}
}
