import assert from'node:assert/strict'
import test from'node:test'
import{RemoteOperationsSessionClient}from'./remoteOperations'

test('external-session transport uses the exact authorized Project route and preserves authority evidence',async()=>{const original=globalThis.fetch;let request!:Request;globalThis.fetch=async(input,init)=>{request=new Request(input,init);return Response.json({project_id:'P1',external_sessions:[{session_id:'ses_1',project_id:'P1',harness:'codex',external_session_id:'native_1',transcript_locator:'codex://session/native_1',workspace_locator:'/workspace/P1',authority_mode:'source_managed',source_capabilities:{metadata:true,usage:false},checkpoint_digest:null,authority_hash:'a'.repeat(64),created_at:'2026-09-07T14:00:00Z',updated_at:'2026-09-07T15:00:00Z'}]})};try{const rows=await new RemoteOperationsSessionClient('https://core.example/',()=> 'member-1','token-1').sessions('P1');assert.equal(request.url,'https://core.example/api/v2/projects/P1/external-sessions');assert.equal(request.headers.get('X-OpenSaddle-User'),'member-1');assert.equal(request.headers.get('Authorization'),'Bearer token-1');assert.deepEqual(rows[0],{sessionId:'ses_1',projectId:'P1',harness:'codex',externalSessionId:'native_1',transcriptLocator:'codex://session/native_1',workspaceLocator:'/workspace/P1',authorityMode:'source_managed',sourceCapabilities:{metadata:true,usage:false},checkpointDigest:undefined,authorityHash:'a'.repeat(64),linkedRunId:undefined,createdAt:'2026-09-07T14:00:00Z',updatedAt:'2026-09-07T15:00:00Z'})}finally{globalThis.fetch=original}})

test('external-session revocation errors expose no stale fallback',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({detail:'project membership required'},{status:403});try{await assert.rejects(new RemoteOperationsSessionClient('https://core.example',()=> 'former-member').sessions('P1'),/project membership required/)}finally{globalThis.fetch=original}})

test('external-session transport rejects envelope and row Project substitution',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({project_id:'P2',external_sessions:[]});try{await assert.rejects(new RemoteOperationsSessionClient('https://core.example',()=> 'member').sessions('P1'),/Project identity mismatch/)}finally{globalThis.fetch=original};globalThis.fetch=async()=>Response.json({project_id:'P1',external_sessions:[{session_id:'ses_1',project_id:'P2',harness:'codex',external_session_id:'native',transcript_locator:'opaque',authority_mode:'source_managed',source_capabilities:{},authority_hash:'a',created_at:'now',updated_at:'now'}]});try{await assert.rejects(new RemoteOperationsSessionClient('https://core.example',()=> 'member').sessions('P1'),/Project identity mismatch/)}finally{globalThis.fetch=original}})
