import {ProjectTaskFeedClient} from './projectTaskFeed'
import type { ProjectCommandRequest, ProjectCommandReceipt, ProjectApprovalProjection, ProjectDeviceProjection, ProjectSourceProjection, ApplicationRendererCandidate, ApplicationRendererDescriptor, ApplicationRendererEnablement, ConnectorInvocationResult, EnvironmentPreview, EnvironmentRevision, ExactArtifactRef, MalleableShellClient, PersonalEnvironmentOverrides, PersonalEnvironmentPreview, PersonalEnvironmentRevision, RendererHostObservation, RendererHostObservationList, RendererHostSession, RunConnectorCapability, ShellCommandDescriptor, ShellCommandResult } from './contracts'

export class RemoteMalleableShellClient implements MalleableShellClient {
  private readonly baseUrl: string; private readonly user: () => string; private readonly token?: string
  constructor(baseUrl: string, user: () => string, token?: string) { this.baseUrl = baseUrl.replace(/\/$/, ''); this.user = user; this.token = token }
  private async request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers: { 'Content-Type': 'application/json', 'X-OpenSaddle-User': this.user(), ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}), ...init?.headers } }); if (!response.ok) { const body = await response.json().catch(() => null) as { detail?: unknown } | null; const detail = typeof body?.detail === 'string' ? body.detail : body?.detail ? JSON.stringify(body.detail) : undefined; throw new Error(detail ?? `Shell API failed (${response.status})`) } return response.json() as Promise<T> }
  async commands(projectId?: string) { return (await this.request<{ commands: ShellCommandDescriptor[] }>(projectId ? `/api/v2/projects/${encodeURIComponent(projectId)}/commands` : '/api/v2/commands')).commands }
  async artifacts(runId: string, projectId: string) { const body = await this.request<{ artifacts: Array<{ artifact_id: string; run_id: string; content_digest: string;artifact_type?:string;size_bytes?:number;created_at?:string;redaction_class?:string }> }>(`/api/v2/runs/${encodeURIComponent(runId)}/artifacts`); return body.artifacts.map((a) => ({ project_id: projectId, run_id: a.run_id, artifact_id: a.artifact_id, digest: a.content_digest,...(a.artifact_type?{artifact_type:a.artifact_type}:{}),...(typeof a.size_bytes==='number'?{size_bytes:a.size_bytes}:{}),...(a.created_at?{created_at:a.created_at}:{}),...(a.redaction_class?{redaction_class:a.redaction_class}:{}) })) }
  async content(resource:ExactArtifactRef){const response=await fetch(`${this.baseUrl}/api/v2/runs/${encodeURIComponent(resource.run_id)}/artifacts/${encodeURIComponent(resource.artifact_id)}/content`,{headers:{'X-OpenSaddle-User':this.user(),...(this.token?{Authorization:`Bearer ${this.token}`}:{})}});if(!response.ok){const body=await response.json().catch(()=>null)as{detail?:unknown}|null;const detail=typeof body?.detail==='string'?body.detail:typeof body?.detail==='object'&&body.detail&&'code'in body.detail?String((body.detail as{code:unknown}).code):`Artifact content failed (${response.status})`;throw Error(detail)}const header=response.headers.get('Content-Length');const declared=header===null?undefined:Number(header);if(declared!==undefined&&(!Number.isFinite(declared)||declared<0||declared>262144))throw Error('artifact_content_too_large');if(!response.body)throw Error('artifact_bytes_unavailable');const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;for(;;){const{done,value}=await reader.read();if(done)break;if(value){size+=value.byteLength;if(size>262144){await reader.cancel('artifact_content_too_large');throw Error('artifact_content_too_large')}chunks.push(value)}}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');const expected=resource.digest.replace(/^sha256:/,'').toLowerCase();if(digest!==expected)throw Error('artifact_content_integrity_denied');let text:string;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{throw Error('artifact_content_not_utf8')}return{text,mediaType:response.headers.get('Content-Type')??'application/octet-stream',sizeBytes:bytes.byteLength,digest}}
  async projectArtifacts(projectId:string,runId:string,signal?:AbortSignal){
    const subject=this.user()
    const run=await this.request<{run_id:string;project_id:string}>(`/api/v2/runs/${encodeURIComponent(runId)}`,{cache:'no-store',signal:signal??AbortSignal.timeout(5000)})
    if(subject!==this.user()||run.run_id!==runId||run.project_id!==projectId)throw Error('Project artifact Run scope mismatch')
    const body=await this.request<{artifacts:Array<{run_id:string;artifact_id:string;content_digest:string}>}>(`/api/v2/runs/${encodeURIComponent(runId)}/artifacts`,{cache:'no-store',signal:signal??AbortSignal.timeout(5000)})
    if(subject!==this.user()||!Array.isArray(body.artifacts)||body.artifacts.length>100)throw Error('Invalid Project artifacts')
    const seen=new Set<string>(),items=body.artifacts.map(a=>{if(a.run_id!==runId||typeof a.artifact_id!=='string'||!a.artifact_id||a.artifact_id.length>512||seen.has(a.artifact_id)||typeof a.content_digest!=='string'||!/^[a-f0-9]{64}$/.test(a.content_digest))throw Error('Invalid Project artifact');seen.add(a.artifact_id);return {project_id:projectId,run_id:runId,artifact_id:a.artifact_id,digest:a.content_digest}})
    return {schema_version:'opensaddle.project-artifacts.v1' as const,project_id:projectId,run_id:runId,items}
  }
  async projectCommands(projectId:string,signal?:AbortSignal){
    const subject=this.user(),body=await this.request<{commands:ShellCommandDescriptor[]}>(`/api/v2/projects/${encodeURIComponent(projectId)}/commands`,{cache:'no-store',signal:signal??AbortSignal.timeout(5000)})
    if(subject!==this.user()||!Array.isArray(body.commands)||body.commands.length>100)throw Error('Invalid Project command directory')
    const seen=new Set<string>(),items=body.commands.filter(d=>d.effect==='read'&&Array.isArray(d.required_actions)&&d.required_actions.every(a=>a==='artifacts:read')).map(d=>{
      if(!d.command_id||typeof d.command_id!=='string'||d.command_id.length>200||seen.has(d.command_id)||!Number.isSafeInteger(d.version)||d.version<1||typeof d.descriptor_digest!=='string'||!/^[a-f0-9]{64}$/.test(d.descriptor_digest)||typeof d.title!=='string'||d.title.length>1000||typeof d.description!=='string'||d.description.length>20000||typeof d.available?.available!=='boolean'||!d.input_schema||typeof d.input_schema!=='object'||!d.output_schema||typeof d.output_schema!=='object'||JSON.stringify([d.input_schema,d.output_schema]).length>32768)throw Error('Invalid Project command descriptor')
      seen.add(d.command_id)
      return {command_id:d.command_id,version:d.version,descriptor_digest:d.descriptor_digest,title:d.title,description:d.description,effect:d.effect,required_actions:d.required_actions,available:{available:d.available.available},input_schema:d.input_schema,output_schema:d.output_schema}
    })
    return {schema_version:'opensaddle.project-commands.v1' as const,project_id:projectId,items}
  }
  async invokeProjectCommand(projectId:string,request:ProjectCommandRequest,signal?:AbortSignal):Promise<ProjectCommandReceipt>{
    const subject=this.user(),guard=signal??AbortSignal.timeout(15000)
    if(!request||Object.keys(request).sort().join(',')!=='artifact_id,command_id,digest,expected_descriptor_digest,expected_version,input,run_id'||[request.command_id,request.run_id,request.artifact_id].some(v=>typeof v!=='string'||!v||v.length>512)||typeof request.digest!=='string'||!/^[a-f0-9]{64}$/.test(request.digest)||!request.input||typeof request.input!=='object'||Array.isArray(request.input)||JSON.stringify(request.input).length>8192)throw Error('Invalid Project command request')
    const directory=await this.projectCommands(projectId,guard),descriptor=directory.items.find(d=>d.command_id===request.command_id)
    if(!descriptor?.available.available||descriptor.version!==request.expected_version||descriptor.descriptor_digest!==request.expected_descriptor_digest)throw Error('Project command changed or unavailable')
    const artifacts=await this.projectArtifacts(projectId,request.run_id,guard)
    if(subject!==this.user()||!artifacts.items.some(a=>a.artifact_id===request.artifact_id&&a.digest===request.digest))throw Error('Exact command artifact is unavailable')
    const resource={project_id:projectId,run_id:request.run_id,artifact_id:request.artifact_id,digest:request.digest}
    const canonicalResource=JSON.stringify(Object.fromEntries(Object.entries(resource).sort(([a],[b])=>a.localeCompare(b))))
    const resourceDigest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonicalResource)))).map(byte=>byte.toString(16).padStart(2,'0')).join('')
    if(subject!==this.user())throw Error('Project command account changed')
    const value=await this.request<ShellCommandResult>(`/api/v2/commands/${encodeURIComponent(descriptor.command_id)}/invocations`,{method:'POST',signal:guard,body:JSON.stringify({resource,input:request.input,expected_version:descriptor.version,expected_descriptor_digest:descriptor.descriptor_digest})})
    if(subject!==this.user()||value.project_id!==projectId||value.command_id!==descriptor.command_id||value.version!==descriptor.version||value.descriptor_digest!==descriptor.descriptor_digest||!value.invocation_id||typeof value.invocation_id!=='string'||Object.entries(resource).some(([k,v])=>value.resource?.[k as keyof typeof resource]!==v)||typeof value.status!=='string'||value.receipt?.effect!=='read'||value.receipt.resource_digest!==resourceDigest||typeof value.receipt.verified!=='boolean'||(value.result?.summary!==undefined&&(typeof value.result.summary!=='string'||value.result.summary.length>20000)))throw Error('Project command receipt mismatch')
    return {schema_version:'opensaddle.project-command-receipt.v1',project_id:projectId,invocation_id:value.invocation_id,command_id:descriptor.command_id,descriptor_digest:descriptor.descriptor_digest,resource,status:value.status,summary:value.result?.summary??'',receipt:{effect:value.receipt.effect,resource_digest:value.receipt.resource_digest,verified:value.receipt.verified}}
  }
  async projectApprovals(projectId:string,signal?:AbortSignal):Promise<ProjectApprovalProjection>{
    const model=await new ProjectTaskFeedClient(this.baseUrl,this.user,this.token).read(projectId,signal)
    const items=model.tasks.filter(task=>task.status==='awaiting_approval').map(task=>{
      if(task.id.length>512||Array.from(task.title).length>20000)throw Error('Invalid Project approval item')
      return {run_id:task.id,title:task.title,status:'awaiting_approval' as const}
    })
    return {schema_version:'opensaddle.project-approvals.v1',project_id:projectId,limit:1000,approval_scope:'run_admission',grant_authority:'host_review_required',items}
  }
  async projectDevices(projectId:string,signal?:AbortSignal):Promise<ProjectDeviceProjection>{
    const subject=this.user()
    const body=await this.request<{items:(ProjectDeviceProjection['items'][number]&{project_id:string})[]}>(`/api/v2/projects/${encodeURIComponent(projectId)}/devices`,{cache:'no-store',signal:signal??AbortSignal.timeout(5000)})
    if(subject!==this.user()||!Array.isArray(body.items)||body.items.length>100)throw Error('Invalid Project device projection')
    const seen=new Set<string>()
    const items=body.items.map(item=>{
      if(!item||item.project_id!==projectId||typeof item.device_id!=='string'||!item.device_id||item.device_id.length>512||typeof item.display_name!=='string'||!item.display_name||item.display_name.length>4096||!Number.isSafeInteger(item.revision)||item.revision<1||!['proposed','accepted','removed','revoked'].includes(item.state)||!['owner_only','selected_members','project_members','team_members'].includes(item.audience)||typeof item.consent_allows_requester!=='boolean'||(item.consent_allows_requester&&item.state!=='accepted')||seen.has(item.device_id))throw Error('Invalid Project device item')
      seen.add(item.device_id)
      return {device_id:item.device_id,display_name:item.display_name,revision:item.revision,state:item.state,audience:item.audience,consent_allows_requester:item.consent_allows_requester}
    })
    return {schema_version:'opensaddle.project-devices.v1',project_id:projectId,limit:100,task_admission:'not_evaluated',items}
  }
  async projectSources(projectId:string,signal?:AbortSignal):Promise<ProjectSourceProjection>{
    const subject=this.user()
    const body=await this.request<{schema_version:string;project_id:string;items:ProjectSourceProjection['items']}>(`/api/v2/projects/${encodeURIComponent(projectId)}/sources?limit=100`,{cache:'no-store',signal:signal??AbortSignal.timeout(5000)})
    if(subject!==this.user()||body.schema_version!=='opensaddle.source-list.v1'||body.project_id!==projectId||!Array.isArray(body.items)||body.items.length>100)throw Error('Invalid Project source projection')
    const seen=new Set<string>()
    const items=body.items.map(item=>{
      if(!item||['source_id','source_kind','revision','display_label'].some(key=>typeof item[key as keyof typeof item]!=='string'||!item[key as keyof typeof item]||item[key as keyof typeof item].length>4096)||typeof item.snapshot_digest!=='string'||!/^[a-f0-9]{64}$/.test(item.snapshot_digest)||seen.has(item.source_id))throw Error('Invalid Project source item')
      seen.add(item.source_id)
      return {source_id:item.source_id,source_kind:item.source_kind,revision:item.revision,snapshot_digest:item.snapshot_digest,display_label:item.display_label}
    })
    return {schema_version:'opensaddle.project-sources.v1',project_id:projectId,limit:100,completeness:'bounded_snapshot',items}
  }
  async applicationRenderers(projectId:string,signal?:AbortSignal){const body=await this.request<{project_id:string;renderers:ApplicationRendererDescriptor[]}>(`/api/v2/projects/${encodeURIComponent(projectId)}/application-renderers`,{signal});if(body.project_id!==projectId)throw Error('application renderer project mismatch');return body.renderers}
  async applicationRendererCandidates(projectId:string){const body=await this.request<{project_id:string;candidates:ApplicationRendererCandidate[]}>(`/api/v2/projects/${encodeURIComponent(projectId)}/application-renderer-candidates`);if(body.project_id!==projectId)throw Error('application renderer candidate project mismatch');return body.candidates}
  async enableApplicationRendererCandidate(projectId:string,candidate:ApplicationRendererCandidate){const body=await this.request<ApplicationRendererEnablement>(`/api/v2/projects/${encodeURIComponent(projectId)}/application-renderer-candidates/${encodeURIComponent(candidate.package_id)}/enable`,{method:'POST',body:JSON.stringify({version:candidate.package_version,manifest_digest:candidate.manifest_digest,expected_enablement_revision:candidate.enablement?.revision??null})});if(body.project_id!==projectId||body.package_id!==candidate.package_id||body.package_version!==candidate.package_version||body.manifest_digest!==candidate.manifest_digest)throw Error('application renderer enablement identity mismatch');return body}
  applicationRendererContent(projectId:string,renderer:ApplicationRendererDescriptor,signal?:AbortSignal){const q=new URLSearchParams({package_id:renderer.package_ref.package_id,version:renderer.package_ref.version,manifest_digest:renderer.package_ref.manifest_digest,content_digest:renderer.content_digest});return fetch(`${this.baseUrl}/api/v2/projects/${encodeURIComponent(projectId)}/application-renderers/${encodeURIComponent(renderer.application_id)}/content?${q}`,{signal,headers:{'X-OpenSaddle-User':this.user(),...(this.token?{Authorization:`Bearer ${this.token}`}:{})}})}
  createRendererHostSession(projectId:string,input:Parameters<NonNullable<MalleableShellClient['createRendererHostSession']>>[1]){return this.request<RendererHostSession>(`/api/v2/projects/${encodeURIComponent(projectId)}/renderer-host-sessions`,{method:'POST',body:JSON.stringify(input)})}
  reportRendererHostObservation(sessionId:string,reportToken:string,input:Parameters<NonNullable<MalleableShellClient['reportRendererHostObservation']>>[2]){return this.request<RendererHostObservation>(`/api/v2/renderer-host-sessions/${encodeURIComponent(sessionId)}/observations`,{method:'POST',headers:{'X-OpenSaddle-Renderer-Host-Token':reportToken},body:JSON.stringify(input)})}
  async rendererHostObservations(projectId:string){const value=await this.request<RendererHostObservationList>(`/api/v2/projects/${encodeURIComponent(projectId)}/renderer-host-observations`);if(value.project_id!==projectId||value.authority!=='host_reported'||value.semantic_correctness!=='not_verified')throw Error('renderer host observation authority mismatch');return value}
  invoke(descriptor: ShellCommandDescriptor, resource: ExactArtifactRef, input: Record<string, unknown> = {}) { return this.request<ShellCommandResult>(`/api/v2/commands/${encodeURIComponent(descriptor.command_id)}/invocations`, { method: 'POST', body: JSON.stringify({ resource, input, expected_version: descriptor.version, expected_descriptor_digest: descriptor.descriptor_digest }) }) }
  async invocations(projectId: string) { return (await this.request<{ items: ShellCommandResult[] }>(`/api/v2/projects/${encodeURIComponent(projectId)}/command-invocations?limit=50`)).items }
  invocation(invocationId: string) { return this.request<ShellCommandResult>(`/api/v2/command-invocations/${encodeURIComponent(invocationId)}`) }
  async connectors(runId: string) { return (await this.request<{ run_id: string; capabilities: RunConnectorCapability[] }>(`/api/v2/runs/${encodeURIComponent(runId)}/connectors`)).capabilities }
  invokeConnector(runId: string, connector: string, action: string, args: Record<string, unknown>) { return this.request<ConnectorInvocationResult>(`/api/v2/runs/${encodeURIComponent(runId)}/connectors/${encodeURIComponent(connector)}/${encodeURIComponent(action)}`, { method: 'POST', body: JSON.stringify({ arguments: args }) }) }
  environment(projectId: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment`) }
  private async personalRequest(path:string,projectId:string,init?:RequestInit){const value=await this.request<PersonalEnvironmentRevision>(path,init);if(value.project_id!==projectId)throw Error('personal environment project mismatch');return value}
  personalEnvironment(projectId:string){return this.personalRequest(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/personal`,projectId)}
  async previewPersonalEnvironment(projectId:string,expectedRevision:number,overrides:PersonalEnvironmentOverrides,reason:string){const value=await this.request<PersonalEnvironmentPreview>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/personal/changes/preview`,{method:'POST',body:JSON.stringify({expected_revision:expectedRevision,overrides,reason})});if(value.project_id!==projectId)throw Error('personal environment project mismatch');return value}
  applyPersonalEnvironment(projectId:string,expectedRevision:number,overrides:PersonalEnvironmentOverrides,reason:string,expectedBaseEnvironmentRevision:number,baseDefinitionDigest:string){return this.personalRequest(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/personal/changes`,projectId,{method:'POST',body:JSON.stringify({expected_revision:expectedRevision,overrides,reason,expected_base_environment_revision:expectedBaseEnvironmentRevision,base_definition_digest:baseDefinitionDigest})})}
  revertPersonalEnvironment(projectId:string,expectedRevision:number,targetRevision:number,reason:string){return this.personalRequest(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/personal/reverts`,projectId,{method:'POST',body:JSON.stringify({expected_revision:expectedRevision,target_revision:targetRevision,reason})})}
  preview(projectId: string, expectedRevision: number, definition: EnvironmentRevision['definition'], reason: string, baseDefinitionDigest: string) { return this.request<EnvironmentPreview>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/changes/preview`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, base_definition_digest: baseDefinitionDigest, definition, reason }) }) }
  apply(projectId: string, expectedRevision: number, definition: EnvironmentRevision['definition'], reason: string, baseDefinitionDigest: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/changes`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, base_definition_digest: baseDefinitionDigest, definition, reason }) }) }
  revert(projectId: string, expectedRevision: number, targetRevision: number, reason: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/reverts`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, target_revision: targetRevision, reason }) }) }
}
