import assert from'node:assert/strict'
import test from'node:test'
import{RemoteParticipantClient}from'./remoteParticipants'

const participant={participant_id:'ptc_1',project_id:'P1',source:'reviewer.md',owner_subject:'owner-1',title:'Reviewer',command_id:'dev.opensaddle.artifact.review',command_version:1,command_descriptor_digest:'c'.repeat(64),lifecycle:'waiting',revision:0}
const message={message_id:'pmsg_1',participant_id:'ptc_1',project_id:'P1',status:'queued',run_id:'R2',invocation_id:null,resource:{project_id:'P1',run_id:'R1',artifact_id:'A1',digest:'d'.repeat(64)},input:{}}

test('participant transport binds exact resource, revision, identity, and retry key',async()=>{const requests:Array<{url:string;init?:RequestInit}>=[];const original=globalThis.fetch;globalThis.fetch=async(input,init)=>{requests.push({url:String(input),init});return Response.json(message,{status:202})};try{const client=new RemoteParticipantClient('https://core.example/',()=> 'member-1','secret');const value=await client.send('ptc_1',7,message.resource,{},'intent-1');assert.equal(value.messageId,'pmsg_1');const request=requests[0];assert.equal(request.url,'https://core.example/api/v2/participants/ptc_1/messages');assert.equal(new Headers(request.init?.headers).get('Idempotency-Key'),'intent-1');assert.equal(new Headers(request.init?.headers).get('X-OpenSaddle-User'),'member-1');assert.deepEqual(JSON.parse(String(request.init?.body)),{expected_participant_revision:7,resource:message.resource,input:{}})}finally{globalThis.fetch=original}})

test('participant transport creates owner definition and reopens durable message handle',async()=>{const requests:string[]=[];const original=globalThis.fetch;globalThis.fetch=async(input)=>{requests.push(String(input));return Response.json(requests.length===1?participant:{...message,status:'completed',invocation_id:'inv_1'})};try{const client=new RemoteParticipantClient('https://core.example',()=> 'owner-1');const created=await client.create('P1',{source:'reviewer.md',title:'Reviewer',commandId:'dev.opensaddle.artifact.review'});assert.equal(created.ownerSubject,'owner-1');assert.equal(created.commandDescriptorDigest,'c'.repeat(64));const completed=await client.message('pmsg_1');assert.equal(completed.invocationId,'inv_1');assert.deepEqual(requests,['https://core.example/api/v2/projects/P1/participants','https://core.example/api/v2/participant-messages/pmsg_1'])}finally{globalThis.fetch=original}})
