import type { ProjectSourceProjection, ApplicationRendererCandidate, ApplicationRendererDescriptor, ApplicationRendererEnablement, ConnectorInvocationResult, EnvironmentPreview, EnvironmentRevision, ExactArtifactRef, MalleableShellClient, PersonalEnvironmentOverrides, PersonalEnvironmentPreview, PersonalEnvironmentRevision, RendererHostObservation, RendererHostObservationList, RendererHostSession, RunConnectorCapability, ShellCommandDescriptor, ShellCommandResult } from './contracts'

export class RemoteMalleableShellClient implements MalleableShellClient {
  private readonly baseUrl: string; private readonly user: () => string; private readonly token?: string
  constructor(baseUrl: string, user: () => string, token?: string) { this.baseUrl = baseUrl.replace(/\/$/, ''); this.user = user; this.token = token }
  private async request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers: { 'Content-Type': 'application/json', 'X-OpenSaddle-User': this.user(), ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}), ...init?.headers } }); if (!response.ok) { const body = await response.json().catch(() => null) as { detail?: unknown } | null; const detail = typeof body?.detail === 'string' ? body.detail : body?.detail ? JSON.stringify(body.detail) : undefined; throw new Error(detail ?? `Shell API failed (${response.status})`) } return response.json() as Promise<T> }
  async commands(projectId?: string) { return (await this.request<{ commands: ShellCommandDescriptor[] }>(projectId ? `/api/v2/projects/${encodeURIComponent(projectId)}/commands` : '/api/v2/commands')).commands }
  async artifacts(runId: string, projectId: string) { const body = await this.request<{ artifacts: Array<{ artifact_id: string; run_id: string; content_digest: string;artifact_type?:string;size_bytes?:number;created_at?:string;redaction_class?:string }> }>(`/api/v2/runs/${encodeURIComponent(runId)}/artifacts`); return body.artifacts.map((a) => ({ project_id: projectId, run_id: a.run_id, artifact_id: a.artifact_id, digest: a.content_digest,...(a.artifact_type?{artifact_type:a.artifact_type}:{}),...(typeof a.size_bytes==='number'?{size_bytes:a.size_bytes}:{}),...(a.created_at?{created_at:a.created_at}:{}),...(a.redaction_class?{redaction_class:a.redaction_class}:{}) })) }
  async content(resource:ExactArtifactRef){const response=await fetch(`${this.baseUrl}/api/v2/runs/${encodeURIComponent(resource.run_id)}/artifacts/${encodeURIComponent(resource.artifact_id)}/content`,{headers:{'X-OpenSaddle-User':this.user(),...(this.token?{Authorization:`Bearer ${this.token}`}:{})}});if(!response.ok){const body=await response.json().catch(()=>null)as{detail?:unknown}|null;const detail=typeof body?.detail==='string'?body.detail:typeof body?.detail==='object'&&body.detail&&'code'in body.detail?String((body.detail as{code:unknown}).code):`Artifact content failed (${response.status})`;throw Error(detail)}const header=response.headers.get('Content-Length');const declared=header===null?undefined:Number(header);if(declared!==undefined&&(!Number.isFinite(declared)||declared<0||declared>262144))throw Error('artifact_content_too_large');if(!response.body)throw Error('artifact_bytes_unavailable');const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;for(;;){const{done,value}=await reader.read();if(done)break;if(value){size+=value.byteLength;if(size>262144){await reader.cancel('artifact_content_too_large');throw Error('artifact_content_too_large')}chunks.push(value)}}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');const expected=resource.digest.replace(/^sha256:/,'').toLowerCase();if(digest!==expected)throw Error('artifact_content_integrity_denied');let text:string;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{throw Error('artifact_content_not_utf8')}return{text,mediaType:response.headers.get('Content-Type')??'application/octet-stream',sizeBytes:bytes.byteLength,digest}}
  async projectSources(projectId:string,signal?:AbortSignal):Promise<ProjectSourceProjection>{
    const subject=this.user()
    const body=await this.request<{schema_version:string;project_id:string;items:ProjectSourceProjection['items']}>(`/api/v2/projects/${encodeURIComponent(projectId)}/sources?limit=100`,{cache:'no-store',signal:signal??AbortSignal.timeout(5000)})
    if(subject!==this.user()||body.schema_version!=='opensaddle.source-list.v1'||body.project_id!==projectId||!Array.isArray(body.items)||body.items.length>100)throw Error('Invalid Project source projection')
    const seen=new Set<string>()
    const items=body.items.map(item=>{
      if(!item||['source_id','source_kind','revision','display_label'].some(key=>typeof item[key as keyof typeof item]!=='string'||!item[key as keyof typeof item]||item[key as keyof typeof item].length>4096)||typeof item.snapshot_digest!=='string'||!/^[a-f0-9]{64}$/.test(item.snapshot_digest)||seen.has(item.source_id))throw Error('Invalid Project source item')
      seen.add(item.source_id)
      return {source_id:item.source_id,source_kind:item.source_kind,revision:item.revision,snapshot_digest:item.snapshot_digest,display_label:item.display_label}
    })
    return {schema_version:'opensaddle.project-sources.v1',project_id:projectId,limit:100,completeness:'bounded_snapshot',items}
  }
  async applicationRenderers(projectId:string,signal?:AbortSignal){const body=await this.request<{project_id:string;renderers:ApplicationRendererDescriptor[]}>(`/api/v2/projects/${encodeURIComponent(projectId)}/application-renderers`,{signal});if(body.project_id!==projectId)throw Error('application renderer project mismatch');return body.renderers}
  async applicationRendererCandidates(projectId:string){const body=await this.request<{project_id:string;candidates:ApplicationRendererCandidate[]}>(`/api/v2/projects/${encodeURIComponent(projectId)}/application-renderer-candidates`);if(body.project_id!==projectId)throw Error('application renderer candidate project mismatch');return body.candidates}
  async enableApplicationRendererCandidate(projectId:string,candidate:ApplicationRendererCandidate){const body=await this.request<ApplicationRendererEnablement>(`/api/v2/projects/${encodeURIComponent(projectId)}/application-renderer-candidates/${encodeURIComponent(candidate.package_id)}/enable`,{method:'POST',body:JSON.stringify({version:candidate.package_version,manifest_digest:candidate.manifest_digest,expected_enablement_revision:candidate.enablement?.revision??null})});if(body.project_id!==projectId||body.package_id!==candidate.package_id||body.package_version!==candidate.package_version||body.manifest_digest!==candidate.manifest_digest)throw Error('application renderer enablement identity mismatch');return body}
  applicationRendererContent(projectId:string,renderer:ApplicationRendererDescriptor,signal?:AbortSignal){const q=new URLSearchParams({package_id:renderer.package_ref.package_id,version:renderer.package_ref.version,manifest_digest:renderer.package_ref.manifest_digest,content_digest:renderer.content_digest});return fetch(`${this.baseUrl}/api/v2/projects/${encodeURIComponent(projectId)}/application-renderers/${encodeURIComponent(renderer.application_id)}/content?${q}`,{signal,headers:{'X-OpenSaddle-User':this.user(),...(this.token?{Authorization:`Bearer ${this.token}`}:{})}})}
  createRendererHostSession(projectId:string,input:Parameters<NonNullable<MalleableShellClient['createRendererHostSession']>>[1]){return this.request<RendererHostSession>(`/api/v2/projects/${encodeURIComponent(projectId)}/renderer-host-sessions`,{method:'POST',body:JSON.stringify(input)})}
  reportRendererHostObservation(sessionId:string,reportToken:string,input:Parameters<NonNullable<MalleableShellClient['reportRendererHostObservation']>>[2]){return this.request<RendererHostObservation>(`/api/v2/renderer-host-sessions/${encodeURIComponent(sessionId)}/observations`,{method:'POST',headers:{'X-OpenSaddle-Renderer-Host-Token':reportToken},body:JSON.stringify(input)})}
  async rendererHostObservations(projectId:string){const value=await this.request<RendererHostObservationList>(`/api/v2/projects/${encodeURIComponent(projectId)}/renderer-host-observations`);if(value.project_id!==projectId||value.authority!=='host_reported'||value.semantic_correctness!=='not_verified')throw Error('renderer host observation authority mismatch');return value}
  invoke(descriptor: ShellCommandDescriptor, resource: ExactArtifactRef, input: Record<string, unknown> = {}) { return this.request<ShellCommandResult>(`/api/v2/commands/${encodeURIComponent(descriptor.command_id)}/invocations`, { method: 'POST', body: JSON.stringify({ resource, input, expected_version: descriptor.version, expected_descriptor_digest: descriptor.descriptor_digest }) }) }
  async invocations(projectId: string) { return (await this.request<{ items: ShellCommandResult[] }>(`/api/v2/projects/${encodeURIComponent(projectId)}/command-invocations?limit=50`)).items }
  invocation(invocationId: string) { return this.request<ShellCommandResult>(`/api/v2/command-invocations/${encodeURIComponent(invocationId)}`) }
  async connectors(runId: string) { return (await this.request<{ run_id: string; capabilities: RunConnectorCapability[] }>(`/api/v2/runs/${encodeURIComponent(runId)}/connectors`)).capabilities }
  invokeConnector(runId: string, connector: string, action: string, args: Record<string, unknown>) { return this.request<ConnectorInvocationResult>(`/api/v2/runs/${encodeURIComponent(runId)}/connectors/${encodeURIComponent(connector)}/${encodeURIComponent(action)}`, { method: 'POST', body: JSON.stringify({ arguments: args }) }) }
  environment(projectId: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment`) }
  private async personalRequest(path:string,projectId:string,init?:RequestInit){const value=await this.request<PersonalEnvironmentRevision>(path,init);if(value.project_id!==projectId)throw Error('personal environment project mismatch');return value}
  personalEnvironment(projectId:string){return this.personalRequest(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/personal`,projectId)}
  async previewPersonalEnvironment(projectId:string,expectedRevision:number,overrides:PersonalEnvironmentOverrides,reason:string){const value=await this.request<PersonalEnvironmentPreview>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/personal/changes/preview`,{method:'POST',body:JSON.stringify({expected_revision:expectedRevision,overrides,reason})});if(value.project_id!==projectId)throw Error('personal environment project mismatch');return value}
  applyPersonalEnvironment(projectId:string,expectedRevision:number,overrides:PersonalEnvironmentOverrides,reason:string,expectedBaseEnvironmentRevision:number,baseDefinitionDigest:string){return this.personalRequest(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/personal/changes`,projectId,{method:'POST',body:JSON.stringify({expected_revision:expectedRevision,overrides,reason,expected_base_environment_revision:expectedBaseEnvironmentRevision,base_definition_digest:baseDefinitionDigest})})}
  revertPersonalEnvironment(projectId:string,expectedRevision:number,targetRevision:number,reason:string){return this.personalRequest(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/personal/reverts`,projectId,{method:'POST',body:JSON.stringify({expected_revision:expectedRevision,target_revision:targetRevision,reason})})}
  preview(projectId: string, expectedRevision: number, definition: EnvironmentRevision['definition'], reason: string, baseDefinitionDigest: string) { return this.request<EnvironmentPreview>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/changes/preview`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, base_definition_digest: baseDefinitionDigest, definition, reason }) }) }
  apply(projectId: string, expectedRevision: number, definition: EnvironmentRevision['definition'], reason: string, baseDefinitionDigest: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/changes`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, base_definition_digest: baseDefinitionDigest, definition, reason }) }) }
  revert(projectId: string, expectedRevision: number, targetRevision: number, reason: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/reverts`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, target_revision: targetRevision, reason }) }) }
}
