import type { ConnectorInvocationResult, EnvironmentPreview, EnvironmentRevision, ExactArtifactRef, MalleableShellClient, RunConnectorCapability, ShellCommandDescriptor, ShellCommandResult } from './contracts'

export class RemoteMalleableShellClient implements MalleableShellClient {
  private readonly baseUrl: string; private readonly user: () => string; private readonly token?: string
  constructor(baseUrl: string, user: () => string, token?: string) { this.baseUrl = baseUrl.replace(/\/$/, ''); this.user = user; this.token = token }
  private async request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers: { 'Content-Type': 'application/json', 'X-OpenSaddle-User': this.user(), ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}), ...init?.headers } }); if (!response.ok) { const body = await response.json().catch(() => null) as { detail?: unknown } | null; const detail = typeof body?.detail === 'string' ? body.detail : body?.detail ? JSON.stringify(body.detail) : undefined; throw new Error(detail ?? `Shell API failed (${response.status})`) } return response.json() as Promise<T> }
  async commands(projectId?: string) { return (await this.request<{ commands: ShellCommandDescriptor[] }>(projectId ? `/api/v2/projects/${encodeURIComponent(projectId)}/commands` : '/api/v2/commands')).commands }
  async artifacts(runId: string, projectId: string) { const body = await this.request<{ artifacts: Array<{ artifact_id: string; run_id: string; content_digest: string }> }>(`/api/v2/runs/${encodeURIComponent(runId)}/artifacts`); return body.artifacts.map((a) => ({ project_id: projectId, run_id: a.run_id, artifact_id: a.artifact_id, digest: a.content_digest })) }
  invoke(descriptor: ShellCommandDescriptor, resource: ExactArtifactRef, input: Record<string, unknown> = {}) { return this.request<ShellCommandResult>(`/api/v2/commands/${encodeURIComponent(descriptor.command_id)}/invocations`, { method: 'POST', body: JSON.stringify({ resource, input, expected_version: descriptor.version, expected_descriptor_digest: descriptor.descriptor_digest }) }) }
  async invocations(projectId: string) { return (await this.request<{ items: ShellCommandResult[] }>(`/api/v2/projects/${encodeURIComponent(projectId)}/command-invocations?limit=50`)).items }
  invocation(invocationId: string) { return this.request<ShellCommandResult>(`/api/v2/command-invocations/${encodeURIComponent(invocationId)}`) }
  async connectors(runId: string) { return (await this.request<{ run_id: string; capabilities: RunConnectorCapability[] }>(`/api/v2/runs/${encodeURIComponent(runId)}/connectors`)).capabilities }
  invokeConnector(runId: string, connector: string, action: string, args: Record<string, unknown>) { return this.request<ConnectorInvocationResult>(`/api/v2/runs/${encodeURIComponent(runId)}/connectors/${encodeURIComponent(connector)}/${encodeURIComponent(action)}`, { method: 'POST', body: JSON.stringify({ arguments: args }) }) }
  environment(projectId: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment`) }
  preview(projectId: string, expectedRevision: number, definition: EnvironmentRevision['definition'], reason: string, baseDefinitionDigest: string) { return this.request<EnvironmentPreview>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/changes/preview`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, base_definition_digest: baseDefinitionDigest, definition, reason }) }) }
  apply(projectId: string, expectedRevision: number, definition: EnvironmentRevision['definition'], reason: string, baseDefinitionDigest: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/changes`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, base_definition_digest: baseDefinitionDigest, definition, reason }) }) }
  revert(projectId: string, expectedRevision: number, targetRevision: number, reason: string) { return this.request<EnvironmentRevision>(`/api/v2/projects/${encodeURIComponent(projectId)}/environment/reverts`, { method: 'POST', body: JSON.stringify({ expected_revision: expectedRevision, target_revision: targetRevision, reason }) }) }
}
