import type{ExternalOperationSession,OperationRunDetail,OperationsSessionClient}from'./contracts'

const object=(value:unknown)=>value as Record<string,unknown>
const string=(value:unknown,name:string)=>{if(typeof value!=='string'||!value)throw Error(`Invalid ${name}`);return value}

export class RemoteOperationsSessionClient implements OperationsSessionClient{
  private readonly base:string;private readonly user:()=>string;private readonly token?:string
  constructor(base:string,user:()=>string,token?:string){this.base=base.replace(/\/$/,'');this.user=user;this.token=token}
  async sessions(projectId:string){const response=await fetch(`${this.base}/api/v2/projects/${encodeURIComponent(projectId)}/external-sessions`,{headers:{'X-OpenSaddle-User':this.user(),...(this.token?{Authorization:`Bearer ${this.token}`}:{})}});if(!response.ok){const body=await response.json().catch(()=>null)as{detail?:unknown}|null;const detail=typeof body?.detail==='string'?body.detail:body?.detail?JSON.stringify(body.detail):undefined;throw Error(detail??`Operations sessions request failed (${response.status})`)}const payload=object(await response.json());if(payload.project_id!==projectId||!Array.isArray(payload.external_sessions))throw Error('External sessions Project identity mismatch');const rows=payload.external_sessions.map(raw=>this.map(raw));if(rows.some(row=>row.projectId!==projectId))throw Error('External sessions Project identity mismatch');return rows}
  async run(runId:string):Promise<OperationRunDetail>{const response=await fetch(`${this.base}/api/v2/runs/${encodeURIComponent(runId)}`,{headers:{'X-OpenSaddle-User':this.user(),...(this.token?{Authorization:`Bearer ${this.token}`}:{})}});if(!response.ok){const body=await response.json().catch(()=>null)as{detail?:unknown}|null;throw Error(typeof body?.detail==='string'?body.detail:`Operations Run request failed (${response.status})`)}const value=object(await response.json());if(value.run_id!==runId)throw Error('Operations Run identity mismatch');return{runId,projectId:string(value.project_id,'run project'),sourceRef:string(value.source_ref,'run source'),task:string(value.task,'run task'),requestedBy:string(value.requested_by,'run requester'),status:string(value.status,'run status'),cancellationRequested:value.cancellation_requested===true,assignedWorkerId:typeof value.assigned_worker_id==='string'?value.assigned_worker_id:undefined,leaseEpoch:typeof value.lease_epoch==='number'?value.lease_epoch:0,leaseExpiresAt:typeof value.lease_expires_at==='string'?value.lease_expires_at:undefined,createdAt:string(value.created_at,'run created at'),updatedAt:string(value.updated_at,'run updated at'),policy:object(value.policy)}}
  private map(raw:unknown):ExternalOperationSession{const value=object(raw),mode=string(value.authority_mode,'authority mode'),harness=string(value.harness,'harness');if(!['source_managed','opensaddle_managed','hybrid'].includes(mode))throw Error('Invalid authority mode');if(!['codex','claude_code','other'].includes(harness))throw Error('Invalid harness');const capabilities=object(value.source_capabilities);if(Object.values(capabilities).some(item=>typeof item!=='boolean'))throw Error('Invalid source capabilities');return{sessionId:string(value.session_id,'session id'),projectId:string(value.project_id,'project id'),harness:harness as ExternalOperationSession['harness'],externalSessionId:string(value.external_session_id,'external session id'),transcriptLocator:string(value.transcript_locator,'transcript locator'),workspaceLocator:typeof value.workspace_locator==='string'?value.workspace_locator:undefined,authorityMode:mode as ExternalOperationSession['authorityMode'],sourceCapabilities:capabilities as Record<string,boolean>,checkpointDigest:typeof value.checkpoint_digest==='string'?value.checkpoint_digest:undefined,authorityHash:string(value.authority_hash,'authority hash'),linkedRunId:typeof value.run_id==='string'?value.run_id:undefined,createdAt:string(value.created_at,'created at'),updatedAt:string(value.updated_at,'updated at')}}
}
