type Json = Record<string, unknown>
import{RemoteMalleableShellClient}from'./remoteMalleableShell'
export type JourneyInvitation={invitationId:string;projectId:string;recipientSubject:string;role:string;status:string;revision:number;expiresAt:string}

export class RemoteJourneyClient {
  private readonly baseUrl:string;private readonly user:()=>string;private readonly token?:string
  constructor(baseUrl:string,user:()=>string,token?:string){this.baseUrl=baseUrl;this.user=user;this.token=token}
  private async request(path:string,method:string,body?:unknown){const response=await fetch(`${this.baseUrl.replace(/\/$/,'')}${path}`,{method,headers:{'Content-Type':'application/json','X-OpenSaddle-User':this.user(),...(this.token?{Authorization:`Bearer ${this.token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok){const value=await response.json().catch(()=>null)as{detail?:unknown}|null;throw Error(typeof value?.detail==='string'?value.detail:`Connected journey request failed (${response.status})`)}return await response.json() as Json}
  createProject(projectId:string){return this.request('/api/v2/projects','POST',{project_id:projectId})}
  async snapshot(projectId:string){const invitations=await this.invitations(projectId);if(invitations.project_id!==projectId)throw Error('Connected journey Project identity mismatch');const mappedInvitations=(Array.isArray(invitations.invitations)?invitations.invitations:[]).map(value=>{const item=value as Json;return{invitationId:String(item.invitation_id),recipientSubject:String(item.recipient_subject),status:String(item.status),revision:Number(item.revision),expiresAt:String(item.expires_at)}});let members:Json,workers:Json;try{[members,workers]=await Promise.all([this.request(`/api/v2/projects/${encodeURIComponent(projectId)}/members`,'GET'),this.request(`/api/v2/projects/${encodeURIComponent(projectId)}/workers`,'GET')])}catch(reason){if(mappedInvitations.some(item=>item.status==='pending'))return{projectId,members:[],workers:[],invitations:mappedInvitations,rosterAvailable:false,canManage:false,currentSubject:this.user()};throw reason}if(members.project_id!==projectId||workers.project_id!==projectId)throw Error('Connected journey Project identity mismatch');return{projectId,members:(Array.isArray(members.members)?members.members:[]).map(value=>{const item=value as Json;return{subject:String(item.subject),role:String(item.role),status:String(item.status)}}),workers:(Array.isArray(workers.workers)?workers.workers:[]).map(value=>{const item=value as Json;return{workerId:String(item.worker_id),runtimeKind:String(item.runtime_kind),status:String(item.status)}}),invitations:mappedInvitations,rosterAvailable:true,currentSubject:this.user(),canManage:(Array.isArray(members.members)?members.members:[]).some(value=>{const item=value as Json;return item.subject===this.user()&&(item.role==='owner'||item.role==='admin')})}}
  async invite(projectId:string,subject:string){await this.request(`/api/v2/projects/${encodeURIComponent(projectId)}/invitations`,'POST',{recipient_subject:subject,role:'member',ttl_seconds:3600})}
  async enroll(projectId:string,workerId:string){await this.registerWorker({workerId,organizationId:projectId,projectIds:[projectId],runtimeKind:'remote_worker'})}
  invitations(projectId:string){return this.request(`/api/v2/projects/${encodeURIComponent(projectId)}/invitations`,'GET')}
  acceptInvitation(projectId:string,invitationId:string,expectedRevision:number){return this.request(`/api/v2/projects/${encodeURIComponent(projectId)}/invitations/${encodeURIComponent(invitationId)}/accept`,'POST',{expected_revision:expectedRevision})}
  revokeInvitation(projectId:string,invitationId:string,expectedRevision:number){return this.request(`/api/v2/projects/${encodeURIComponent(projectId)}/invitations/${encodeURIComponent(invitationId)}/revoke`,'POST',{expected_revision:expectedRevision})}
  addMember(projectId:string,subject:string,role:'admin'|'member'|'requester'|'approver'|'auditor'){return this.request(`/api/v2/projects/${encodeURIComponent(projectId)}/members`,'PUT',{subject,role})}
  registerWorker(input:{workerId:string;organizationId:string;projectIds:string[];runtimeKind:'remote_worker'|'aws_firecracker'|'gcp_microvm'|'azure_microvm'}){return this.request('/api/v2/workers','POST',{worker_id:input.workerId,organization_id:input.organizationId,project_ids:input.projectIds,runtime_kind:input.runtimeKind})}
  createRun(input:{projectId:string;sourceId:string;task:string}){return this.request('/api/v2/runs','POST',{project_id:input.projectId,source_id:input.sourceId,task:input.task})}
  run(runId:string){return this.request(`/api/v2/runs/${encodeURIComponent(runId)}`,'GET')}
  cancel(runId:string){return this.request(`/api/v2/runs/${encodeURIComponent(runId)}/cancel`,'POST',{})}
  async review(projectId:string,runId:string){const run=await this.run(runId);if(run.project_id!==projectId)throw Error('Connected journey Run Project mismatch');const listing=await this.request(`/api/v2/runs/${encodeURIComponent(runId)}/artifacts`,'GET');if(listing.run_id!==runId)throw Error('Connected journey artifact Run mismatch');const artifact=(Array.isArray(listing.artifacts)?listing.artifacts:[])[0]as Json|undefined;if(!artifact)throw Error('This Run has no reviewable artifact.');const ref={project_id:projectId,run_id:runId,artifact_id:String(artifact.artifact_id),digest:String(artifact.content_digest)};const content=await new RemoteMalleableShellClient(this.baseUrl,this.user,this.token).content(ref);return{runId,status:String(run.status),workerId:String(run.assigned_worker_id??'unassigned'),resource:ref,text:content.text}}
}
