import assert from'node:assert/strict'
import test from'node:test'
import{createHash}from'node:crypto'
import{desktopRendererDocument,rendererRequestAllowed,validateDesktopRendererMessage,validateDesktopRendererRequest}from'./applicationRendererPolicy'
const fragment='<p>review</p><script>addEventListener("message",()=>{})</script>',digest=createHash('sha256').update(fragment).digest('hex'),request={instanceId:'review-main',generation:1,connectionKey:'connection',packageRef:{package_id:'review',version:'1',manifest_digest:'a'.repeat(64)},contentDigest:digest,fragment,projection:{resource:{project_id:'p',run_id:'r',artifact_id:'a',digest:'b'.repeat(64)},text:'report',verified_bytes:true,fact_verification:'not_verified' as const},bounds:{x:0,y:0,width:500,height:500}}
test('desktop renderer accepts only exact bounded signed fragments',()=>{assert.equal(validateDesktopRendererRequest(request),request);assert.throws(()=>validateDesktopRendererRequest({...request,contentDigest:'c'.repeat(64)}),/identity_invalid/);assert.throws(()=>validateDesktopRendererRequest({...request,fragment:'<iframe src="https://example.com">'}),/identity_invalid|fragment_invalid/)})
test('desktop renderer network policy denies every non-data request',()=>{assert.equal(rendererRequestAllowed('data:text/html,ok'),true);for(const url of['https://example.com/leak','http://127.0.0.1/leak','file:///tmp/private','ws://example.com'])assert.equal(rendererRequestAllowed(url),false)})
test('desktop wrapper establishes the port bridge before code without embedding protected projection',()=>{const html=desktopRendererDocument(request);assert.ok(html.indexOf('Content-Security-Policy')<html.indexOf(fragment));assert.ok(html.indexOf('opensaddle-application-port')<html.indexOf(fragment));assert.doesNotMatch(html,/"report"/)})
test('desktop port accepts only exact bounded current messages',()=>{const base={protocol:'opensaddle.application.v1',kind:'state',nonce:'n',generation:1,instance_id:'review-main',connection_key:'connection',package_ref:request.packageRef,state:{filter:'evidence'}};assert.ok(validateDesktopRendererMessage(base,request,'n'));assert.equal(validateDesktopRendererMessage({...base,nonce:'old'},request,'n'),undefined);assert.equal(validateDesktopRendererMessage({...base,state:{token:'secret'}},request,'n'),undefined);assert.equal(validateDesktopRendererMessage({...base,state:{note:'x'.repeat(4001)}},request,'n'),undefined)})
test('desktop request accepts bounded state and rejects arbitrary replacement state',()=>{assert.deepEqual(validateDesktopRendererRequest({...request,state:{filter:'open',note:'kept'}}).state,{filter:'open',note:'kept'});assert.throws(()=>validateDesktopRendererRequest({...request,state:{secret:'no'} as never}),/desktop_renderer_state_invalid/)})
