import{createHash}from'node:crypto'
import type{ApplicationState,ApplicationStateSchema}from'./applicationState.js'
import{validateApplicationState,validateApplicationStateSchema}from'./applicationState.js'
export const DESKTOP_RENDERER_MAX_BYTES=128*1024
export interface DesktopRendererRequest{instanceId:string;generation:number;connectionKey:string;packageRef:{package_id:string;version:string;manifest_digest:string};contentDigest:string;fragment:string;stateMaxBytes:number;stateSchema:ApplicationStateSchema;state?:ApplicationState;projection:{resource:{project_id:string;run_id:string;artifact_id:string;digest:string};text:string;verified_bytes:boolean;fact_verification:'verified'|'not_verified'|'unavailable'};bounds:{x:number;y:number;width:number;height:number}}
const hex64=/^[a-f0-9]{64}$/
export function validateDesktopRendererRequest(value:DesktopRendererRequest){const bytes=Buffer.byteLength(value.fragment,'utf8');if(!value.instanceId||!Number.isInteger(value.generation)||value.generation<0||!value.connectionKey||!hex64.test(value.packageRef.manifest_digest)||!hex64.test(value.contentDigest)||bytes<1||bytes>DESKTOP_RENDERER_MAX_BYTES||createHash('sha256').update(value.fragment).digest('hex')!==value.contentDigest)throw Error('desktop_renderer_identity_invalid');if(/<!doctype|<\/?(?:html|head|body|base|meta|iframe|object|embed)\b/i.test(value.fragment))throw Error('desktop_renderer_fragment_invalid');if(value.stateMaxBytes!==8192||!validateApplicationStateSchema(value.stateSchema)||value.state&&!validateApplicationState(value.state,value.stateSchema))throw Error('desktop_renderer_state_invalid');const r=value.projection.resource;if(!r.project_id||!r.run_id||!r.artifact_id||!hex64.test(r.digest)||Buffer.byteLength(value.projection.text,'utf8')>256*1024)throw Error('desktop_renderer_projection_invalid');for(const n of Object.values(value.bounds))if(!Number.isFinite(n))throw Error('desktop_renderer_bounds_invalid');if(value.bounds.width<1||value.bounds.height<1||value.bounds.width>10000||value.bounds.height>10000)throw Error('desktop_renderer_bounds_invalid');return value}
export const rendererRequestAllowed=(url:string)=>{try{return new URL(url).protocol==='data:'}catch{return false}}
export function validateDesktopRendererMessage(value:unknown,request:DesktopRendererRequest,nonce:string){if(!value||typeof value!=='object')return;const m=value as Record<string,unknown>;if(m.protocol!=='opensaddle.application.v1'||!['ready','state'].includes(String(m.kind))||m.nonce!==nonce||m.generation!==request.generation||m.instance_id!==request.instanceId||m.connection_key!==request.connectionKey||(!m.package_ref||typeof m.package_ref!=='object'||(m.package_ref as Record<string,unknown>).package_id!==request.packageRef.package_id||(m.package_ref as Record<string,unknown>).version!==request.packageRef.version||(m.package_ref as Record<string,unknown>).manifest_digest!==request.packageRef.manifest_digest))return;if(m.kind==='state'&&!validateApplicationState(m.state,request.stateSchema))return;return m}
export function desktopRendererDocument(value:DesktopRendererRequest){const bridge=`<script>(()=>{let port;addEventListener('message',event=>{if(event.source!==window)return;if(event.data==='opensaddle-application-port'&&event.ports.length===1){port=event.ports[0];port.onmessage=message=>window.postMessage(message.data,'*');port.start();return}const m=event.data;if(port&&m?.protocol==='opensaddle.application.v1'&&(m.kind==='ready'||m.kind==='state'))port.postMessage(m)})})()</script>`;return `<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="default-src 'none';script-src 'unsafe-inline';style-src 'unsafe-inline';connect-src 'none';img-src 'none';font-src 'none';object-src 'none';frame-src 'none';base-uri 'none';form-action 'none'"></head><body>${bridge}${value.fragment}</body></html>`}
