import path from'node:path'
import{spawn,type ChildProcess}from'node:child_process'
import{createConnection}from'node:net'
export interface DesktopPersonalRuntimeRequest{projectId:string;workspace:string;adapter:'codex'|'claude';executable:string;cpuMillicores:number;memoryMiB:number;maxConcurrency:number}
export interface PersonalRuntimeLaunchConfig{projectDatabase:string;stateDir:string;port:number;allowedOrigin:string;handoffFd:number}
const text=(value:unknown,name:string)=>{if(typeof value!=='string'||!value||value.includes('\0'))throw Error(`${name} is invalid`);return value}
const integer=(value:unknown,name:string,max:number)=>{if(!Number.isSafeInteger(value)||Number(value)<1||Number(value)>max)throw Error(`${name} is invalid`);return String(value)}
const absolute=(value:unknown,name:string)=>{const result=text(value,name);if(!path.isAbsolute(result))throw Error(`${name} must be absolute`);return result}
export function personalRuntimeLaunchArgs(request:DesktopPersonalRuntimeRequest,config:PersonalRuntimeLaunchConfig){if(!['codex','claude'].includes(request.adapter))throw Error('adapter is invalid');if(!Number.isSafeInteger(config.handoffFd)||config.handoffFd<3||config.handoffFd>1024)throw Error('handoff FD is invalid');return['serve-personal-runtime','--project-id',text(request.projectId,'project ID'),'--workspace',absolute(request.workspace,'workspace'),'--project-database',absolute(config.projectDatabase,'project database'),'--state-dir',absolute(config.stateDir,'state directory'),'--host','127.0.0.1','--port',integer(config.port,'port',65535),'--adapter',request.adapter,'--executable',absolute(request.executable,'executable'),'--cpu-millicores',integer(request.cpuMillicores,'CPU',1_000_000),'--memory-mib',integer(request.memoryMiB,'memory',16_777_216),'--max-concurrency',integer(request.maxConcurrency,'concurrency',1024),'--allowed-origin',text(config.allowedOrigin,'allowed origin'),'--handoff-fd',String(config.handoffFd)]}
export interface PersonalRuntimeHandoff{baseUrl:string;installationId:string;ownerSubject:string;projectId:string;bearerToken:string;adoptionSocket:string}
export function parsePersonalRuntimeHandoff(raw:unknown,expected:{baseUrl:string;projectId:string;installationId?:string;adoptionSocket?:string}):PersonalRuntimeHandoff{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Personal runtime handoff is invalid');const value=raw as Record<string,unknown>;if(Object.keys(value).sort().join(',')!=='adoption_socket,base_url,bearer_token,installation_id,owner_subject,project_id,protocol_version,schema_version'||value.schema_version!=='opensaddle.personal-runtime-handoff.v1'||value.protocol_version!=='opensaddle.personal-runtime.v1')throw Error('Personal runtime handoff contract is invalid');const baseUrl=text(value.base_url,'base URL');let url:URL;try{url=new URL(baseUrl)}catch{throw Error('Personal runtime base URL is invalid')}if(url.protocol!=='http:'||url.hostname!=='127.0.0.1'||!url.port||url.pathname!=='/'||url.username||url.password||url.search||url.hash||baseUrl!==expected.baseUrl)throw Error('Personal runtime base URL must be loopback');const installationId=text(value.installation_id,'installation'),projectId=text(value.project_id,'project'),adoptionSocket=absolute(value.adoption_socket,'adoption socket');if(projectId!==expected.projectId||(expected.installationId&&installationId!==expected.installationId)||(expected.adoptionSocket&&adoptionSocket!==expected.adoptionSocket))throw Error('Personal runtime handoff identity does not match commissioned runtime');return{baseUrl,installationId,ownerSubject:text(value.owner_subject,'owner'),projectId,bearerToken:text(value.bearer_token,'bearer token'),adoptionSocket}}
const commissions=new Map<string,Promise<{handoff:PersonalRuntimeHandoff;process:ChildProcess}>>()
export function commissionPersonalRuntimeProcess(input:{command:string;request:DesktopPersonalRuntimeRequest;config:PersonalRuntimeLaunchConfig;expected:{baseUrl:string;projectId:string;installationId?:string;adoptionSocket?:string};timeoutMs?:number}){const key=path.resolve(input.config.stateDir);const active=commissions.get(key);if(active)return active;const pending=new Promise<{handoff:PersonalRuntimeHandoff;process:ChildProcess}>((resolve,reject)=>{const args=personalRuntimeLaunchArgs(input.request,{...input.config,handoffFd:3}),child=spawn(input.command,args,{cwd:input.config.stateDir,stdio:['ignore','ignore','pipe','pipe'],detached:process.platform!=='win32'}),pipe=child.stdio[3];if(!pipe){child.kill();reject(Error('Personal runtime handoff pipe is unavailable'));return}let bytes='';const timeout=setTimeout(()=>{child.kill();reject(Error('Personal runtime handoff timed out'))},input.timeoutMs??15_000);const fail=(error:unknown)=>{clearTimeout(timeout);child.kill();reject(error instanceof Error?error:Error(String(error)))};child.once('error',fail);child.once('exit',code=>{if(code!==null&&code!==0)fail(Error(`Personal runtime exited before handoff (${code})`))});pipe.on('data',chunk=>{bytes+=String(chunk);if(Buffer.byteLength(bytes)>65_536){fail(Error('Personal runtime handoff exceeded its bound'));return}const newline=bytes.indexOf('\n');if(newline<0)return;clearTimeout(timeout);try{const raw=JSON.parse(bytes.slice(0,newline)) as unknown;resolve({handoff:parsePersonalRuntimeHandoff(raw,input.expected),process:child})}catch(error){fail(error)}});pipe.once('error',fail)});commissions.set(key,pending);void pending.then(({process:child})=>child.once('exit',()=>{if(commissions.get(key)===pending)commissions.delete(key)}),()=>{if(commissions.get(key)===pending)commissions.delete(key)});return pending}
export function adoptPersonalRuntime(input:{stateDir:string;socketPath:string;baseUrl:string;installationId:string;projectId:string;timeoutMs?:number}){const stateDir=path.resolve(input.stateDir),socketPath=path.resolve(input.socketPath);if(!socketPath.startsWith(`${stateDir}${path.sep}`))return Promise.reject(Error('Personal runtime adoption socket is outside private state'));const request=JSON.stringify({schema_version:'opensaddle.personal-runtime-adoption-request.v1',expected_protocol_version:'opensaddle.personal-runtime.v1',installation_id:text(input.installationId,'installation'),project_id:text(input.projectId,'project')})+'\n';if(Buffer.byteLength(request)>1024)return Promise.reject(Error('Personal runtime adoption request exceeded its bound'));return new Promise<PersonalRuntimeHandoff>((resolve,reject)=>{const socket=createConnection(socketPath),timeout=setTimeout(()=>{socket.destroy();reject(Error('Personal runtime adoption timed out'))},input.timeoutMs??2000);let bytes='';const fail=(reason:unknown)=>{clearTimeout(timeout);socket.destroy();reject(reason instanceof Error?reason:Error(String(reason)))};socket.once('connect',()=>socket.write(request));socket.once('error',fail);socket.on('data',chunk=>{bytes+=String(chunk);if(Buffer.byteLength(bytes)>65_536){fail(Error('Personal runtime adoption response exceeded its bound'));return}const newline=bytes.indexOf('\n');if(newline<0)return;clearTimeout(timeout);socket.end();try{resolve(parsePersonalRuntimeHandoff(JSON.parse(bytes.slice(0,newline)),{baseUrl:input.baseUrl,projectId:input.projectId,installationId:input.installationId,adoptionSocket:socketPath}))}catch(error){fail(error)}})})}
