import { useState } from 'react'

export interface Reaction { emoji: string; count: number; reacted?: boolean }
export function ReactionBar({ reactions, onChange, onReply, onOverflow }: { reactions: Reaction[]; onChange: (reactions: Reaction[]) => void; onReply?: () => void; onOverflow?: () => void }) {
  const [open, setOpen] = useState(false)
  const toggle = (emoji: string) => onChange(reactions.some((item) => item.emoji === emoji)
    ? reactions.map((item) => item.emoji === emoji ? { ...item, count: Math.max(0, item.count + (item.reacted ? -1 : 1)), reacted: !item.reacted } : item).filter((item) => item.count > 0)
    : [...reactions, { emoji, count: 1, reacted: true }])
  return <div className="os-reaction-bar"><div className="os-reaction-controls">{reactions.map((reaction) => <button type="button" key={reaction.emoji} className={reaction.reacted ? 'is-reacted' : ''} onClick={() => toggle(reaction.emoji)} aria-label={`${reaction.emoji} ${reaction.count} reactions`}>{reaction.emoji} <span>{reaction.count}</span></button>)}<button type="button" className="os-reaction-add" aria-label="Add reaction" onClick={() => setOpen((value) => !value)}>☺</button>{open && <div className="os-reaction-popover" role="dialog" aria-label="Choose a reaction">{['👍', '❤️', '😂', '🎉'].map((emoji) => <button key={emoji} type="button" onClick={() => { toggle(emoji); setOpen(false) }}>{emoji}</button>)}</div>}</div><div className="slack-message-hover os-reaction-hover-toolbar" aria-label="Message actions"><button type="button" title="React with thumbs up" aria-label="React with thumbs up" onClick={() => toggle('👍')}>👍</button><button type="button" title="React with heart" aria-label="React with heart" onClick={() => toggle('❤️')}>❤️</button><button type="button" title="React with joy" aria-label="React with joy" onClick={() => toggle('😂')}>😂</button><button type="button" title="React with tada" aria-label="React with tada" onClick={() => toggle('🎉')}>🎉</button><button type="button" title="Reply" aria-label="Reply" onClick={onReply}>↩</button><button type="button" title="More" aria-label="More message actions" onClick={onOverflow}>•••</button></div></div>
}
