import React,{useLayoutEffect,useMemo,useRef,useState}from'react'
import type{ApplicationProjection,ExecutableRendererManifest}from'./executableApplication'
import{readExactRenderer}from'./executableApplication'
import type{ApplicationRendererDescriptor,MalleableShellClient}from'../services/contracts'
void React
let nextDesktopGeneration=0
export function DesktopApplicationHost({client,projectId,manifest,projection,connectionKey}:{client:MalleableShellClient;projectId:string;manifest:ApplicationRendererDescriptor;projection:ApplicationProjection;connectionKey:string}){const loadKey=useMemo(()=>[connectionKey,projectId,projection.resource.run_id,projection.resource.artifact_id,projection.resource.digest,manifest.package_ref.version,manifest.package_ref.manifest_digest,manifest.content_digest].join('\0'),[connectionKey,projectId,projection.resource.run_id,projection.resource.artifact_id,projection.resource.digest,manifest]),holder=useRef<HTMLDivElement>(null),generation=useRef(++nextDesktopGeneration),identity=useRef<string|undefined>(undefined),[status,setStatus]=useState<{key:string;kind:'loading'|'ready'|'error'}>({key:loadKey,kind:'loading'}),expectedIdentity=[connectionKey,manifest.instance_id,generation.current,manifest.package_ref.package_id,manifest.package_ref.version,manifest.package_ref.manifest_digest,manifest.content_digest,projection.resource.project_id,projection.resource.run_id,projection.resource.artifact_id,projection.resource.digest].join('\0')
 useLayoutEffect(()=>{const current=generation.current,desktop=window.opensaddle;let disposed=false,observer:ResizeObserver|undefined,unsubscribe:(()=>void)|undefined;identity.current=undefined;setStatus({key:loadKey,kind:'loading'});if(!desktop?.openApplicationRenderer||!client.applicationRendererContent){setStatus({key:loadKey,kind:'error'});return}const bounds=()=>{const rect=holder.current?.getBoundingClientRect();return rect&&{x:rect.x,y:rect.y,width:rect.width,height:rect.height}},position=()=>{const next=bounds(),active=identity.current;if(active&&next)void desktop.setApplicationRendererBounds(active,next)}
 unsubscribe=desktop.onApplicationRendererEvent(event=>{if(!disposed&&event.identity===expectedIdentity&&event.instanceId===manifest.instance_id&&event.generation===current&&event.kind==='ready')setStatus({key:loadKey,kind:'ready'})});addEventListener('scroll',position,true);addEventListener('resize',position);observer=new ResizeObserver(position);if(holder.current)observer.observe(holder.current)
 void client.applicationRendererContent(projectId,manifest).then(response=>readExactRenderer(response,{...manifest,sandbox_policy:{scripts:true,network:'unavailable',same_origin:false,navigation:'host_observed_only'}} as ExecutableRendererManifest)).then(fragment=>{if(disposed||current!==generation.current)return;const rect=bounds();if(!rect)throw Error('desktop_renderer_bounds_unavailable');return desktop.openApplicationRenderer({instanceId:manifest.instance_id,generation:current,connectionKey,packageRef:manifest.package_ref,contentDigest:manifest.content_digest,fragment,projection,bounds:rect})}).then(opened=>{if(!opened)return;if(disposed||current!==generation.current){void desktop.closeApplicationRenderer(opened.identity);return}identity.current=opened.identity;position()}).catch(()=>{if(!disposed&&current===generation.current)setStatus({key:loadKey,kind:'error'})});return()=>{disposed=true;removeEventListener('scroll',position,true);removeEventListener('resize',position);observer?.disconnect();unsubscribe?.();const active=identity.current;identity.current=undefined;void desktop.closeApplicationRenderer(active??expectedIdentity)}},[client,projectId,manifest,projection,connectionKey,loadKey,expectedIdentity])
 const kind=status.key===loadKey?status.kind:'loading';return <section className="cc-panel"><span className="eyebrow">Desktop application</span><h2>{manifest.application_id}</h2>{kind==='loading'&&<p role="status">Starting the isolated desktop renderer…</p>}{kind==='ready'&&<p role="status">Renderer ready in its isolated desktop process.</p>}{kind==='error'&&<p role="alert">The desktop renderer is unavailable. Host recovery remains available.</p>}<div ref={holder} style={{height:360,minWidth:0}} aria-label="Desktop application viewport"/></section>}
