import assert from'node:assert/strict'
import test from'node:test'
import React from'react'
import{act,create}from'react-test-renderer'
import{createHash}from'node:crypto'
import{DesktopApplicationHost}from'./DesktopApplicationHost'
import type{ApplicationRendererDescriptor,MalleableShellClient}from'../services/contracts'
globalThis.IS_REACT_ACT_ENVIRONMENT=true
Object.assign(globalThis,{addEventListener:()=>{},removeEventListener:()=>{},ResizeObserver:class{observe(){}disconnect(){}}})
const fragment='<p>renderer</p>',digest=createHash('sha256').update(fragment).digest('hex'),manifest:ApplicationRendererDescriptor={application_id:'review-evidence',instance_id:'review-main',entry_file:'renderer.html',content_digest:digest,size:fragment.length,media_type:'text/html; profile=opensaddle-renderer-fragment.v1; charset=utf-8',package_ref:{package_id:'review',version:'1',manifest_digest:'a'.repeat(64)},input_schema:{},output_schema:{},state_schema_version:1,sandbox_policy:{scripts:true,same_origin:false,network_isolation:'unavailable',navigation_containment:'host_observed_only'},authority:'core',execution_trust:'trusted_signed_publisher'}
const projection={resource:{project_id:'p',run_id:'r',artifact_id:'a',digest:'b'.repeat(64)},text:'report',verified_bytes:true as const,fact_verification:'not_verified' as const}
const client=()=>({applicationRendererContent:async()=>new Response(fragment,{headers:{'Content-Type':manifest.media_type,'Content-Length':String(fragment.length)}})})as unknown as MalleableShellClient
test('desktop ready event registered before open resolution is retained',async()=>{const oldWindow=globalThis.window;let listener:(event:any)=>void=()=>{};Object.assign(globalThis,{window:{opensaddleDesktop:true,opensaddle:{onApplicationRendererEvent:(next:any)=>{listener=next;return()=>{}},openApplicationRenderer:async(request:any)=>{listener({identity:[request.connectionKey,request.instanceId,request.generation,request.packageRef.package_id,request.packageRef.version,request.packageRef.manifest_digest,request.contentDigest,request.projection.resource.project_id,request.projection.resource.run_id,request.projection.resource.artifact_id,request.projection.resource.digest].join('\0'),instanceId:'review-main',generation:request.generation,kind:'ready'});return{identity:'opened',rendererPid:2}},closeApplicationRenderer:async()=>true,setApplicationRendererBounds:async()=>true}}});let view:any;await act(async()=>{view=create(<DesktopApplicationHost client={client()} projectId="p" manifest={manifest} projection={projection} connectionKey="c"/>,{createNodeMock:()=>({getBoundingClientRect:()=>({x:0,y:0,width:500,height:360})})})});await act(async()=>{await new Promise(resolve=>setTimeout(resolve,20))});assert.match(JSON.stringify(view.toJSON()),/Renderer ready/);await act(async()=>view.unmount());globalThis.window=oldWindow})
test('desktop unmount closes the exact pending generation identity',async()=>{const oldWindow=globalThis.window,closed:string[]=[];Object.assign(globalThis,{window:{opensaddleDesktop:true,opensaddle:{onApplicationRendererEvent:()=>()=>{},openApplicationRenderer:async()=>new Promise(()=>{}),closeApplicationRenderer:async(identity:string)=>{closed.push(identity);return true},setApplicationRendererBounds:async()=>true}}});let view:any;await act(async()=>{view=create(<DesktopApplicationHost client={client()} projectId="p" manifest={manifest} projection={projection} connectionKey="private-c"/>,{createNodeMock:()=>({getBoundingClientRect:()=>({x:0,y:0,width:500,height:360})})})});await act(async()=>view.unmount());assert.equal(closed.length,1);assert.match(closed[0]!,/^private-c\0review-main\0/);globalThis.window=oldWindow})
