import type{ApplicationState,ApplicationStateMigration,ApplicationStateSchema}from'./applicationState'
import{migrateApplicationState,validateApplicationState,validateApplicationStateMigration,validateApplicationStateSchema}from'./applicationState'
export const APPLICATION_PROTOCOL='opensaddle.application.v1' as const
export const MAX_RENDERER_BYTES=128*1024
export interface ExecutablePackageRef{package_id:string;version:string;manifest_digest:string}
export interface ExecutableRendererManifest{application_id:string;instance_id:string;entry_file:string;content_digest:string;size:number;media_type:'text/html; profile=opensaddle-renderer-fragment.v1; charset=utf-8';package_ref:ExecutablePackageRef;input_schema:Record<string,unknown>;output_schema:Record<string,unknown>;state_schema_version:number;state_max_bytes:number;state_schema:ApplicationStateSchema;state_migrations:ApplicationStateMigration[];sandbox_policy:{scripts:true;network:false|'unavailable';same_origin:false;navigation:false|'host_observed_only'};authority:'core'|'fixture';execution_trust?:'trusted_signed_publisher'}
export interface ApplicationProjection{resource:{project_id:string;run_id:string;artifact_id:string;digest:string};text:string;verified_bytes:boolean;fact_verification:'verified'|'not_verified'|'unavailable'}
export interface ApplicationEnvelope{protocol:typeof APPLICATION_PROTOCOL;kind:'ready'|'state'|'request';nonce:string;generation:number;instance_id:string;connection_key:string;package_ref:ExecutablePackageRef;state?:unknown;request_id?:string;action?:string}
export interface ActiveApplicationFence{source:MessageEventSource|null;nonce:string;generation:number;instanceId:string;connectionKey:string;packageRef:ExecutablePackageRef}
export type RendererState=ApplicationState
const hex64=/^[a-f0-9]{64}$/
export function validateRendererManifest(value:ExecutableRendererManifest){if(!value.application_id||!value.instance_id||!value.entry_file||value.entry_file.startsWith('/')||value.entry_file.includes('..'))throw Error('application_renderer_manifest_invalid');if(!hex64.test(value.content_digest)||!hex64.test(value.package_ref.manifest_digest))throw Error('application_renderer_digest_invalid');if(!Number.isInteger(value.size)||value.size<1||value.size>MAX_RENDERER_BYTES)throw Error('application_renderer_size_invalid');const stateSchema=validateApplicationStateSchema(value.state_schema);if(value.state_max_bytes!==8192||!stateSchema||!Array.isArray(value.state_migrations)||JSON.stringify(value.state_migrations).length>16384||value.state_migrations.some(migration=>!validateApplicationStateMigration(migration,stateSchema,value.state_schema_version))||new Set(value.state_migrations.map(migration=>`${migration.from_version}:${migration.to_version}`)).size!==value.state_migrations.length)throw Error('application_renderer_state_contract_invalid');if(value.media_type!=='text/html; profile=opensaddle-renderer-fragment.v1; charset=utf-8'||value.state_schema_version<1||!Number.isInteger(value.state_schema_version)||!value.input_schema||typeof value.input_schema!=='object'||!value.output_schema||typeof value.output_schema!=='object'||JSON.stringify(value.input_schema).length>16384||JSON.stringify(value.output_schema).length>16384)throw Error('application_renderer_contract_invalid');if(value.sandbox_policy.scripts!==true||!([false,'unavailable']as unknown[]).includes(value.sandbox_policy.network)||value.sandbox_policy.same_origin!==false||!([false,'host_observed_only']as unknown[]).includes(value.sandbox_policy.navigation))throw Error('application_renderer_sandbox_invalid');return value}
const samePackage=(a:ExecutablePackageRef,b:ExecutablePackageRef)=>a.package_id===b.package_id&&a.version===b.version&&a.manifest_digest===b.manifest_digest
export function acceptsApplicationMessage(event:Pick<MessageEvent,'source'|'data'>,fence:ActiveApplicationFence):event is MessageEvent<ApplicationEnvelope>{const m=event.data as Partial<ApplicationEnvelope>|null;return fence.source!==null&&event.source===fence.source&&m?.protocol===APPLICATION_PROTOCOL&&(m.kind==='ready'||m.kind==='state'||m.kind==='request')&&m.nonce===fence.nonce&&m.generation===fence.generation&&m.instance_id===fence.instanceId&&m.connection_key===fence.connectionKey&&Boolean(m.package_ref&&samePackage(m.package_ref,fence.packageRef))}
export function validateRendererState(value:unknown,schema:unknown):RendererState|undefined{return validateApplicationState(value,schema)}
export async function readExactRenderer(response:Response,manifest:ExecutableRendererManifest){validateRendererManifest(manifest);if(!response.ok)throw Error(`application_renderer_unavailable_${response.status}`);if((response.headers.get('Content-Type')??'').split(';').map(x=>x.trim()).join('; ')!==manifest.media_type)throw Error('application_renderer_media_type_invalid');const length=response.headers.get('Content-Length');if(length!==null&&Number(length)!==manifest.size)throw Error('application_renderer_size_mismatch');if(!response.body)throw Error('application_renderer_bytes_unavailable');const reader=response.body.getReader(),parts:Uint8Array[]=[];let size=0;for(;;){const{done,value}=await reader.read();if(done)break;if(value){size+=value.byteLength;if(size>MAX_RENDERER_BYTES||size>manifest.size){await reader.cancel('application_renderer_size_mismatch');throw Error('application_renderer_size_mismatch')}parts.push(value)}}if(size!==manifest.size)throw Error('application_renderer_size_mismatch');const bytes=new Uint8Array(size);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length}const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==manifest.content_digest)throw Error('application_renderer_integrity_denied');try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{throw Error('application_renderer_not_utf8')}}
export function sandboxDocument(fragment:string){if(/<\/?(?:html|head|body|base|iframe|object|embed)\b/i.test(fragment)||/<meta\b/i.test(fragment))throw Error('application_renderer_document_invalid');const csp="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; media-src 'none'; font-src 'none'; object-src 'none'; frame-src 'none'; child-src 'none'; worker-src 'none'; navigate-to 'none'; base-uri 'none'; form-action 'none'";return `<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="${csp}"><meta name="referrer" content="no-referrer"></head><body>${fragment}</body></html>`}
export function compatibleApplicationState(previous:ExecutableRendererManifest,next:ExecutableRendererManifest,state:unknown){if(previous.instance_id!==next.instance_id||previous.application_id!==next.application_id)return;const migration=next.state_migrations?.find(value=>value.from_version===previous.state_schema_version&&value.to_version===next.state_schema_version);return previous.state_schema_version===next.state_schema_version?validateApplicationState(state,next.state_schema):migrateApplicationState(state,previous.state_schema,next.state_schema,migration)}
