import assert from'node:assert/strict'
import test from'node:test'
import{createHash}from'node:crypto'
import{acceptsApplicationMessage,compatibleApplicationState,readExactRenderer,sandboxDocument,validateRendererManifest,validateRendererState,type ActiveApplicationFence,type ExecutableRendererManifest}from'./executableApplication'
const bytes=new TextEncoder().encode('<!doctype html><head></head><body>fixture</body>'),digest=createHash('sha256').update(bytes).digest('hex')
const manifest=(version='1.0.0'):ExecutableRendererManifest=>({application_id:'fixture.report.annotator',instance_id:'review-main',entry_file:'renderer.html',content_digest:digest,size:bytes.length,media_type:'text/html; profile=opensaddle-renderer-fragment.v1; charset=utf-8',package_ref:{package_id:'fixture.report-tools',version,manifest_digest:version==='1.0.0'?'1'.repeat(64):'2'.repeat(64)},input_schema:{type:'object'},output_schema:{type:'object'},state_schema_version:1,sandbox_policy:{scripts:true,network:false,same_origin:false,navigation:false},authority:'fixture'})
test('validates exact bounded renderer manifests and immutable bytes',async()=>{const value=manifest();assert.equal(validateRendererManifest(value),value);const document=await readExactRenderer(new Response(bytes,{headers:{'Content-Type':'text/html; profile=opensaddle-renderer-fragment.v1; charset=utf-8','Content-Length':String(bytes.length)}}),value);assert.match(document,/fixture/);await assert.rejects(readExactRenderer(new Response('changed',{headers:{'Content-Type':'text/html; profile=opensaddle-renderer-fragment.v1; charset=utf-8'}}),value),/size_mismatch|integrity_denied/)})
test('opaque sandbox messages require source nonce generation instance connection and package',()=>{const source={}as Window,base=manifest(),fence:ActiveApplicationFence={source,nonce:'n',generation:4,instanceId:base.instance_id,connectionKey:'connection-B',packageRef:base.package_ref};const data={protocol:'opensaddle.application.v1',kind:'ready',nonce:'n',generation:4,instance_id:'review-main',connection_key:'connection-B',package_ref:base.package_ref};assert.equal(acceptsApplicationMessage({source,data}as MessageEvent,fence),true);for(const event of[{source:{},data},{source,data:{...data,nonce:'wrong'}},{source,data:{...data,generation:3}},{source,data:{...data,connection_key:'connection-A'}},{source,data:{...data,package_ref:{...base.package_ref,version:'9'}}}])assert.equal(acceptsApplicationMessage(event as MessageEvent,fence),false)})
test('replacement preserves only compatible declared instance state',()=>{const first=manifest(),next=manifest('2.0.0'),state={filter:'evidence',note:'mine'};assert.equal(compatibleApplicationState(first,next,state),state);assert.equal(compatibleApplicationState(first,{...next,state_schema_version:2},state),undefined);assert.equal(compatibleApplicationState(first,{...next,instance_id:'another'},state),undefined)})
test('host-owned sandbox wrapper places policy before package markup and rejects nested documents',()=>{const output=sandboxDocument('<style>p{color:red}</style><p>safe</p><script>window.loaded=true</script>');assert.ok(output.indexOf('Content-Security-Policy')<output.indexOf('<style>'));assert.match(output,/connect-src 'none'/);assert.match(output,/navigate-to 'none'/);assert.throws(()=>sandboxDocument('<script>ok()</script><head><meta http-equiv="refresh" content="0;url=https://example.com"></head>'),/document_invalid/)})
test('renderer state schema is bounded and rejects arbitrary host messages',()=>{assert.deepEqual(validateRendererState({filter:'report',note:'mine'}),{filter:'report',note:'mine'});assert.equal(validateRendererState({token:'secret'}),undefined);assert.equal(validateRendererState({note:'x'.repeat(4001)}),undefined)})
