import assert from'node:assert/strict'
import test from'node:test'
import React from'react'
import{act,create,type ReactTestRenderer}from'react-test-renderer'
import{SandboxApplicationHost}from'./SandboxApplicationHost'
globalThis.IS_REACT_ACT_ENVIRONMENT=true
Object.assign(globalThis,{addEventListener:()=>{},removeEventListener:()=>{}})
import{reportAnnotatorV1,reportAnnotatorV2}from'./fixturePackages'
const projection=(project_id='p')=>({resource:{project_id,run_id:'run',artifact_id:'artifact',digest:'a'.repeat(64)},text:'Report',verified_bytes:true as const,fact_verification:'not_verified' as const})
const response=(text:string)=>new Response(text,{headers:{'Content-Type':'text/html; profile=opensaddle-renderer-fragment.v1; charset=utf-8','Content-Length':String(new TextEncoder().encode(text).length)}})
const waitFor=async(check:()=>boolean)=>{for(let i=0;i<200;i++){if(check())return;await act(async()=>{await new Promise(resolve=>setTimeout(resolve,10))})}throw Error('mounted_milestone_timeout')}
const fixture=async(m=reportAnnotatorV1)=>response(await (await import('node:fs/promises')).readFile(new URL(`../../public/application-fixtures/${m.entry_file}`,import.meta.url),'utf8'))
test('mounted host synchronously removes an old package frame during replacement',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async()=>fixture();let view!:ReactTestRenderer;await act(async()=>{view=create(<SandboxApplicationHost manifest={reportAnnotatorV1} contentUrl="/v1" connectionKey="c" projection={projection()} readyTimeoutMs={10000}/>,{createNodeMock:()=>({contentWindow:{postMessage(){}}})})});await waitFor(()=>view.root.findAllByType('iframe').length===1);assert.equal(view.root.findAllByType('iframe').length,1);await act(async()=>{view.update(<SandboxApplicationHost manifest={reportAnnotatorV2} previousManifest={reportAnnotatorV1} contentUrl="/v2" connectionKey="c" projection={projection()}/>)});assert.equal(view.root.findAllByType('iframe').length,0);assert.match(JSON.stringify(view.toJSON()),/Loading isolated application/);await act(async()=>view.unmount());globalThis.fetch=oldFetch})
test('connection replacement aborts the old renderer byte read and clears its frame',async()=>{const oldFetch=globalThis.fetch;const signals:AbortSignal[]=[];globalThis.fetch=async(_input,init)=>{signals.push(init?.signal as AbortSignal);return new Promise<Response>(()=>{})};let view!:ReactTestRenderer;await act(async()=>{view=create(<SandboxApplicationHost manifest={reportAnnotatorV1} contentUrl="/v1" connectionKey="old" projection={projection()}/>)});await act(async()=>{view.update(<SandboxApplicationHost manifest={reportAnnotatorV1} contentUrl="/v1" connectionKey="new" projection={projection()}/>)});assert.equal(signals[0]?.aborted,true);assert.equal(view.root.findAllByType('iframe').length,0);await act(async()=>view.unmount());globalThis.fetch=oldFetch})
test('a renderer that never becomes ready falls back to host recovery',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async()=>fixture();let view!:ReactTestRenderer;await act(async()=>{view=create(<SandboxApplicationHost manifest={reportAnnotatorV1} contentUrl="/v1" connectionKey="c" projection={projection()} readyTimeoutMs={5}/>,{createNodeMock:()=>({contentWindow:{postMessage(){}}})})});await act(async()=>{await new Promise(resolve=>setTimeout(resolve,40))});assert.match(JSON.stringify(view.toJSON()),/Host recovery remains available/);assert.equal(view.root.findAllByType('iframe').length,0);await act(async()=>view.unmount());globalThis.fetch=oldFetch})
test('invalid renderer markup resolves to recovery instead of an unhandled load',async()=>{const oldFetch=globalThis.fetch,bad='<head><meta http-equiv="refresh" content="0"></head>';globalThis.fetch=async()=>response(bad);const content_digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(bad)).then(value=>[...new Uint8Array(value)].map(x=>x.toString(16).padStart(2,'0')).join('')),manifest={...reportAnnotatorV1,size:new TextEncoder().encode(bad).length,content_digest};let view!:ReactTestRenderer;await act(async()=>{view=create(<SandboxApplicationHost manifest={manifest} contentUrl="/bad" connectionKey="c" projection={projection()}/>)});await act(async()=>{await new Promise(resolve=>setTimeout(resolve,10))});assert.match(JSON.stringify(view.toJSON()),/application_renderer_document_invalid/);await act(async()=>view.unmount());globalThis.fetch=oldFetch})
