import React,{useEffect,useRef,useState,type FormEvent}from'react'
import{useNavigate,useSearchParams}from'react-router-dom'
import{useStore}from'../../data/store'
import type{ExactArtifactRef,Participant,ParticipantClient,ParticipantMessage}from'../../services/contracts'
import{Button}from'../../ui/Button'

void React
const errorText=(value:unknown)=>value instanceof Error?value.message:String(value)
const exactKey=(resource:ExactArtifactRef)=>JSON.stringify(resource)

export function ParticipantReviewSurface({client,participantId,projectId,resource,onSelectParticipant}:{client?:ParticipantClient;participantId:string;projectId:string;resource?:ExactArtifactRef;onSelectParticipant:(id:string)=>void}){
  const[participant,setParticipant]=useState<Participant>();const[messages,setMessages]=useState<ParticipantMessage[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false)
  const[lookup,setLookup]=useState(participantId);const[source,setSource]=useState('.opensaddle/participants/reviewer.md');const[title,setTitle]=useState('Artifact reviewer');const[commandId,setCommandId]=useState('dev.opensaddle.artifact.review')
  const generation=useRef(0);const intent=useRef<{fingerprint:string;key:string}|undefined>(undefined);const alive=useRef(true)
  useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
  const load=async()=>{const g=++generation.current;setParticipant(undefined);setMessages([]);setError('');if(!client){setError('Participant authority unavailable.');return}if(!participantId)return;try{const[v,m]=await Promise.all([client.get(participantId),client.messages(participantId)]);if(alive.current&&g===generation.current){setParticipant(v);setMessages(m)}}catch(reason){if(alive.current&&g===generation.current)setError(errorText(reason))}}
  useEffect(()=>{setLookup(participantId);setBusy(false);intent.current=undefined;void load()},[participantId,client]) // eslint-disable-line react-hooks/exhaustive-deps
  const discover=(event:FormEvent)=>{event.preventDefault();const id=lookup.trim();if(id)onSelectParticipant(id)}
  const create=async(event:FormEvent)=>{event.preventDefault();if(!client||!projectId||!source.trim()||!title.trim()||!commandId.trim())return;const g=++generation.current;setBusy(true);setError('');try{const value=await client.create(projectId,{source:source.trim(),title:title.trim(),commandId:commandId.trim()});if(alive.current&&g===generation.current)onSelectParticipant(value.participantId)}catch(reason){if(alive.current&&g===generation.current)setError(errorText(reason))}finally{if(alive.current&&g===generation.current)setBusy(false)}}
  const lifecycle=async(next:Participant['lifecycle'])=>{if(!participant||!client)return;const g=generation.current;const expectedId=participant.participantId;setBusy(true);setError('');try{const value=await client.lifecycle(expectedId,participant.revision,next);if(alive.current&&g===generation.current&&participantId===expectedId)setParticipant(value)}catch(reason){if(alive.current&&g===generation.current)setError(errorText(reason))}finally{if(alive.current&&g===generation.current)setBusy(false)}}
  const submit=async()=>{if(!participant||!client||!resource)return;const g=generation.current;const expectedId=participant.participantId;const fingerprint=`${expectedId}:${participant.revision}:${exactKey(resource)}`;if(!intent.current||intent.current.fingerprint!==fingerprint)intent.current={fingerprint,key:crypto.randomUUID()};setBusy(true);setError('');try{const value=await client.send(expectedId,participant.revision,resource,{},intent.current.key);if(alive.current&&g===generation.current&&participantId===expectedId){setMessages(items=>items.some(item=>item.messageId===value.messageId)?items.map(item=>item.messageId===value.messageId?value:item):[value,...items]);intent.current=undefined}}catch(reason){if(alive.current&&g===generation.current)setError(errorText(reason))}finally{if(alive.current&&g===generation.current)setBusy(false)}}
  return <main className="content-page cc-page"><h1>Reviewer participant</h1>{error&&<p role="alert">{error}</p>}
    <section className="cc-panel"><h2>Find a reviewer</h2><form onSubmit={discover}><label>Participant ID<input value={lookup} onChange={event=>setLookup(event.target.value)} placeholder="ptc_…"/></label><Button type="submit" disabled={!lookup.trim()}>Open reviewer</Button></form></section>
    {!participantId&&<section className="cc-panel"><h2>Create an owner-controlled reviewer</h2>{projectId?<form onSubmit={create}><label>Definition source<input value={source} onChange={event=>setSource(event.target.value)} required/></label><label>Title<input value={title} onChange={event=>setTitle(event.target.value)} required/></label><label>Review command<input value={commandId} onChange={event=>setCommandId(event.target.value)} required/></label><p>Creation records a durable reviewer definition. Waiting does not poll or run a model.</p><Button type="submit" loading={busy}>Create reviewer</Button></form>:<p>Choose a Project before creating a reviewer.</p>}</section>}
    {participantId&&!participant&&!error&&<p aria-live="polite">Loading reviewer…</p>}
    {participant&&<><section className="cc-panel"><h2>{participant.title}</h2><p><code>{participant.participantId}</code> · {participant.lifecycle} · revision {participant.revision}</p><p>Owner <code>{participant.ownerSubject}</code> · source <code>{participant.source}</code></p><p>Command <code>{participant.commandId}</code> v{participant.commandVersion} · descriptor <code>{participant.commandDescriptorDigest}</code></p><p>Waiting is a configured lifecycle. Message Run status remains authoritative. Closing this page does not change the reviewer or cancel work.</p>{resource?<p>Exact resource: <code>{resource.project_id}/{resource.run_id}/{resource.artifact_id}</code> · <code>{resource.digest}</code></p>:<p>No exact artifact resource is selected.</p>}<div className="page-actions"><Button disabled={busy||participant.lifecycle!=='waiting'||!resource} onClick={()=>void submit()}>Request exact artifact review</Button><Button disabled={busy||participant.lifecycle!=='waiting'} onClick={()=>void lifecycle('paused')}>Pause reviewer</Button><Button disabled={busy||participant.lifecycle!=='paused'} onClick={()=>void lifecycle('waiting')}>Resume reviewer</Button><Button variant="danger" disabled={busy||participant.lifecycle==='retired'} onClick={()=>void lifecycle('retired')}>Retire reviewer</Button></div></section>
      <section className="cc-panel"><h2>Durable inbox</h2><Button variant="secondary" disabled={busy} onClick={()=>void load()}>Refresh status</Button>{messages.length===0?<p>No accepted review messages.</p>:<ul>{messages.map(message=><li key={message.messageId}><code>{message.messageId}</code> · <strong>{message.status}</strong> · Run <code>{message.runId}</code>{message.invocationId&&<> · result <a href={'/review?'+new URLSearchParams({project:message.resource.project_id,run:message.resource.run_id,invocation:message.invocationId})}><code>{message.invocationId}</code></a></>}{!message.invocationId&&<> · accepted; no result yet</>}</li>)}</ul>}</section></>}
  </main>
}

export function ParticipantReviewPage(){const{services}=useStore();const[params]=useSearchParams();const navigate=useNavigate();const participantId=params.get('participant')??'';const projectId=params.get('project')??'';const run=params.get('run')??'';const artifact=params.get('artifact')??'';const digest=params.get('digest')??'';const resource=projectId&&run&&artifact&&digest?{project_id:projectId,run_id:run,artifact_id:artifact,digest}:undefined;return <ParticipantReviewSurface client={services?.participants} participantId={participantId} projectId={projectId} resource={resource} onSelectParticipant={id=>{const next=new URLSearchParams(params);next.set('participant',id);navigate(`/participants/review?${next}`)}}/>}
