import assert from'node:assert/strict'
import test from'node:test'
import React,{StrictMode}from'react'
import{act,create,type ReactTestRenderer}from'react-test-renderer'
import{MemoryRouter}from'react-router-dom'
import type{ExactArtifactRef,Participant,ParticipantClient,ParticipantMessage}from'../../services/contracts'
import{ParticipantReviewSurface}from'./ParticipantReviewPage'

;(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true
void React
const resource:ExactArtifactRef={project_id:'P1',run_id:'R1',artifact_id:'A1',digest:'d'.repeat(64)}
const participant=(id='ptc_1',lifecycle:Participant['lifecycle']='waiting',revision=0):Participant=>({participantId:id,projectId:'P1',source:'.opensaddle/participants/reviewer.md',ownerSubject:'owner-1',title:`Reviewer ${id}`,commandId:'dev.opensaddle.artifact.review',commandVersion:1,commandDescriptorDigest:'c'.repeat(64),lifecycle,revision})
const message=(status='queued',invocationId?:string):ParticipantMessage=>({messageId:`pmsg_${status}`,participantId:'ptc_1',projectId:'P1',status,runId:'run_review_1',invocationId,resource,input:{}})
const api=(overrides:Partial<ParticipantClient>={}):ParticipantClient=>({create:async()=>participant(),get:async id=>participant(id),lifecycle:async(id,_revision,next)=>participant(id,next,1),send:async()=>message(),message:async()=>message(),messages:async()=>[],...overrides})
const view=(client:ParticipantClient,id='ptc_1',onSelectParticipant=()=>{})=><MemoryRouter><ParticipantReviewSurface client={client} participantId={id} projectId="P1" resource={resource} onSelectParticipant={onSelectParticipant}/></MemoryRouter>
async function mount(client:ParticipantClient,id='ptc_1'){let renderer!:ReactTestRenderer;await act(async()=>{renderer=create(view(client,id));await Promise.resolve()});return renderer}
const button=(renderer:ReactTestRenderer,label:string)=>renderer.root.findAllByType('button').find(node=>node.findAllByProps({className:'os-button__label'}).some(child=>child.children.join('')===label))!

test('mounted reviewer fences stale route and client responses',async()=>{let resolveOld!:(value:Participant)=>void;const old=api({get:async()=>new Promise(resolve=>{resolveOld=resolve})});const current=api({get:async()=>participant('ptc_new')});let renderer!:ReactTestRenderer;await act(async()=>{renderer=create(view(old,'ptc_old'));await Promise.resolve()});await act(async()=>{renderer.update(view(current,'ptc_new'));await Promise.resolve()});await act(async()=>{resolveOld(participant('ptc_old'));await Promise.resolve()});const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/ptc_new/);assert.doesNotMatch(markup,/Reviewer ptc_old/)})

test('StrictMode effect replay retains a live mounted reviewer surface',async()=>{let renderer!:ReactTestRenderer;await act(async()=>{renderer=create(<StrictMode>{view(api())}</StrictMode>);await Promise.resolve()});assert.match(JSON.stringify(renderer.toJSON()),/Reviewer ptc_1/)})

test('route change releases busy state while a stale lifecycle response is pending',async()=>{let resolveOld!:(value:Participant)=>void;const old=api({lifecycle:async()=>new Promise(resolve=>{resolveOld=resolve})});const current=api({get:async()=>participant('ptc_new')});let renderer=await mount(old);await act(async()=>{button(renderer,'Pause reviewer').props.onClick();await Promise.resolve()});assert.equal(button(renderer,'Pause reviewer').props.disabled,true);await act(async()=>{renderer.update(view(current,'ptc_new'));await Promise.resolve()});assert.equal(button(renderer,'Pause reviewer').props.disabled,false);await act(async()=>{resolveOld(participant('ptc_1','paused',1));await Promise.resolve()});assert.match(JSON.stringify(renderer.toJSON()),/Reviewer ptc_new.*waiting/s)})

test('unknown response retry reuses one intent key and does not create a duplicate',async()=>{const keys:string[]=[];let attempts=0;const client=api({send:async(_id,_revision,exact,_input,key)=>{keys.push(key);assert.deepEqual(exact,resource);attempts++;if(attempts===1)throw Error('response lost');return message('queued')}});const renderer=await mount(client);await act(async()=>{button(renderer,'Request exact artifact review').props.onClick();await Promise.resolve()});assert.match(JSON.stringify(renderer.toJSON()),/response lost/);await act(async()=>{button(renderer,'Request exact artifact review').props.onClick();await Promise.resolve()});assert.equal(attempts,2);assert.equal(keys[0],keys[1]);assert.equal(renderer.root.findAll(node=>node.type==='code'&&node.children.join('')==='pmsg_queued').length,1)})

test('owner denial is explicit and create/discovery remain deliberate',async()=>{let selected='';const client=api({create:async()=>{throw Error('project owner or admin role required')}});let renderer!:ReactTestRenderer;await act(async()=>{renderer=create(view(client,'',id=>{selected=id}));await Promise.resolve()});const forms=renderer.root.findAllByType('form');await act(async()=>{await forms[1].props.onSubmit({preventDefault(){}})});assert.match(JSON.stringify(renderer.toJSON()),/project owner or admin role required/);const lookup=renderer.root.findAllByType('input')[0];await act(async()=>{lookup.props.onChange({target:{value:'ptc_known'}})});await act(async()=>{forms[0].props.onSubmit({preventDefault(){}})});assert.equal(selected,'ptc_known')})

test('unmount does not send cancellation or lifecycle mutation',async()=>{let resolveGet!:(value:Participant)=>void;let mutations=0;const client=api({get:async()=>new Promise(resolve=>{resolveGet=resolve}),lifecycle:async()=>{mutations++;return participant()},send:async()=>{mutations++;return message()}});let renderer!:ReactTestRenderer;await act(async()=>{renderer=create(view(client));await Promise.resolve()});await act(async()=>{renderer.unmount();resolveGet(participant());await Promise.resolve()});assert.equal(mutations,0)})

test('mounted exact resource and lifecycle transitions preserve authoritative revisions',async()=>{const transitions:Array<[number,string]>=[];const client=api({messages:async()=>[message('running'),message('completed','inv_1')],lifecycle:async(id,revision,next)=>{transitions.push([revision,next]);return participant(id,next,revision+1)}});const renderer=await mount(client);let markup=JSON.stringify(renderer.toJSON());assert.match(markup,new RegExp(`P1.*R1.*A1.*${'d'.repeat(64)}.*running.*completed.*inv_1`,'s'));await act(async()=>{button(renderer,'Pause reviewer').props.onClick();await Promise.resolve()});await act(async()=>{button(renderer,'Resume reviewer').props.onClick();await Promise.resolve()});await act(async()=>{button(renderer,'Retire reviewer').props.onClick();await Promise.resolve()});assert.deepEqual(transitions,[[0,'paused'],[1,'waiting'],[2,'retired']]);markup=JSON.stringify(renderer.toJSON());assert.match(markup,/retired.*revision.*3/s);assert.equal(button(renderer,'Request exact artifact review').props.disabled,true)})

test('completed message deep-links its exact invocation',async()=>{const renderer=await mount(api({messages:async()=>[message('completed','inv_exact')]}));const link=renderer.root.findByType('a');assert.equal(link.props.href,'/review?project=P1&run=R1&invocation=inv_exact')})
