import {StandalonePluginSettings} from './StandalonePluginSettings'
import {ProjectRendererSettings} from './RendererSettingsEditor'
import {ProjectTeamSettings} from '../teams/ProjectTeamSettings'
import {useEffect,useState} from 'react'
import {PresentationSettingsClient} from '../../services/presentationSettings'
import {useParams} from 'react-router-dom'
import {useStore} from '../../data/store'
import {PresentationEditor} from './PresentationEditor'
export function PresentationPage(){const {projectId}=useParams();const {services}=useStore();const client=services?.presentationSettings;return <div className="content-page connected-local-page"><header className="page-header"><h1>{projectId?`${projectId} · Appearance`:'Personal appearance'}</h1></header>{client?<><EffectivePreferences client={client} projectId={projectId}/>{projectId?<><PresentationEditor catalog={services?.malleableShell} client={client} scope="user_project" projectId={projectId}/><PresentationEditor catalog={services?.malleableShell} client={client} scope="project" projectId={projectId}/>{services?.teams?.associationsAvailable&&<ProjectTeamSettings key={projectId+services.teams.identity()} client={services.teams} presentation={client} projectId={projectId}/>}</>:<PresentationEditor catalog={services?.malleableShell} client={client} scope="user"/>}</>:<p>Presentation settings are unavailable on this server.</p>}{!projectId&&services?.standalonePluginSettings&&<StandalonePluginSettings client={services.standalonePluginSettings}/>} {projectId&&services?.rendererSettings&&services?.malleableShell&&<ProjectRendererSettings client={services.rendererSettings} catalog={services.malleableShell} projectId={projectId}/>}</div>}

const originLabel=(scope?:string)=>({user:'personal defaults',team:'Team defaults',project:'project defaults',user_project:'my project override'}[scope??'']??'built-in defaults')
function EffectivePreferences({client,projectId}:{client:PresentationSettingsClient;projectId?:string}) {const [value,setValue]=useState<Awaited<ReturnType<PresentationSettingsClient['effective']>>>();const [revision,setRevision]=useState(0);useEffect(()=>client.subscribe(()=>setRevision(value=>value+1)),[client]);useEffect(()=>{let live=true;setValue(undefined);client.effective(projectId).then(value=>{if(live)setValue(value)}).catch(()=>{});return()=>{live=false}},[client,projectId,revision]);return value?<p>Effective theme: {value.values.theme} ({originLabel(value.provenance.theme)}). Spacing: {value.values.density} ({originLabel(value.provenance.density)}).</p>:null}
