import {PROJECT_PERSPECTIVES} from '../../perspectives/project/builtins'
import {installedProjectViews} from '../../perspectives/project/installed'
import type {MalleableShellClient} from '../../services/contracts'
import React,{useEffect,useRef,useState} from 'react'
import {PresentationSettingsClient,type PresentationLayer,type PresentationScope,type PresentationValues} from '../../services/presentationSettings'
export function PresentationEditor({client,scope,projectId,catalog}:{catalog?:Pick<MalleableShellClient,'applicationRenderers'>;client:PresentationSettingsClient;scope:PresentationScope;projectId?:string}) {
 const [saved,setSaved]=useState<PresentationLayer>(),[values,setValues]=useState<PresentationValues>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0)
 const [views,setViews]=useState<Array<{id:string;title:string}>>([])
 const generation=useRef(0),locked=useRef(false)
 const identity=client.identity()
 useEffect(()=>{const epoch=++generation.current;setSaved(undefined);setValues({});setViews([]);setMessage('');setBusy(true);locked.current=true;Promise.all([client.read(scope,projectId),projectId&&(scope==='project'||scope==='user_project')&&catalog?.applicationRenderers?catalog.applicationRenderers(projectId,AbortSignal.timeout(5000)).then(installedProjectViews).catch(()=>[]):Promise.resolve([])]).then(([value,installed])=>{if(epoch===generation.current){setSaved(value);setValues(value.values);setViews(installed)}}).catch(error=>{if(epoch===generation.current)setMessage(error.message)}).finally(()=>{if(epoch===generation.current){setBusy(false);locked.current=false}});return()=>{generation.current++}},[client,scope,projectId,identity,reload,catalog])
 async function save(next:PresentationValues){if(!saved||!saved.can_write||locked.current)return;const epoch=generation.current;locked.current=true;setBusy(true);setMessage('');try{const value=await client.replace(scope,projectId,saved.revision,next);if(epoch===generation.current){setSaved(value);setValues(value.values);setMessage('Preferences saved.')}}catch(error){if(epoch===generation.current){setSaved(undefined);setMessage(error instanceof Error?error.message:'Could not save preferences.')}}finally{if(epoch===generation.current){locked.current=false;setBusy(false)}}}
 function change(key:'theme'|'density'|'perspective',value:string){const next={...values};if(!value)delete next[key];else Object.assign(next,{[key]:value});setValues(next)}
 const choices=[...PROJECT_PERSPECTIVES,...views]
 return <React.Fragment><section className="settings-card presentation-editor"><h2>{scope==='team'?'Team defaults':scope==='user'?'Personal appearance':scope==='project'?'Project defaults':'My project appearance'}</h2><p>{scope==='team'?'Shared team preferences. Project inheritance requires an explicit association.':scope==='project'?'Shared defaults for project members. Only owners and admins can save changes.':scope==='user_project'?'Private overrides for this project. Other members keep their own preferences.':'Your defaults across projects. Project settings can override them.'}</p><button disabled={busy} onClick={()=>setReload(value=>value+1)}>Reload preferences</button>{message&&<p role="status">{message}</p>}{saved&&!saved.can_write&&<p>These shared defaults are read-only for your project role.</p>}{saved&&<fieldset disabled={busy||!saved.can_write}><legend>Presentation</legend><label>Theme<select value={values.theme??''} onChange={event=>change('theme',event.target.value)}><option value="">Inherit</option><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Spacing<select value={values.density??''} onChange={event=>change('density',event.target.value)}><option value="">Inherit</option><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label>Default view<select aria-label="Default view" value={values.perspective??''} onChange={event=>change('perspective',event.target.value)}><option value="">Inherit</option>{choices.map(view=><option key={view.id} value={view.id}>{view.title}</option>)}{values.perspective&&!choices.some(view=>view.id===values.perspective)&&<option value={values.perspective}>Unavailable view: {values.perspective}</option>}</select></label><p>A view preference does not install or enable a plugin. Unavailable views fall back to Dialogue while preserving the preference.</p><button onClick={()=>void save(values)}>Save preferences</button><button onClick={()=>void save({})}>Reset to inherited defaults</button></fieldset>}</section></React.Fragment>
}
