import React,{useEffect,useRef,useState} from 'react'
import type {ApplicationRendererDescriptor,MalleableShellClient} from '../../services/contracts'
import {rendererSettingsContract,type RendererSettingsAuthority,type RendererSettingsSnapshot,type RendererSettingsScope} from '../../services/rendererSettings'
import {validateApplicationState,type ApplicationState} from '../../applications/applicationState'
void React
export function ProjectRendererSettings({client,catalog,projectId}:{client:RendererSettingsAuthority;catalog:Pick<MalleableShellClient,'applicationRenderers'>;projectId:string}){
 const identity=client.identity(),[reload,setReload]=useState(0),[error,setError]=useState('')
 const [result,setResult]=useState<{catalog:typeof catalog;identity:string;projectId:string;items:ApplicationRendererDescriptor[]}>()
 const current=result?.catalog===catalog&&result.identity===identity&&result.projectId===projectId?result:undefined
 useEffect(()=>{let active=true;setResult(undefined);setError('');void catalog.applicationRenderers?.(projectId,AbortSignal.timeout(10000)).then(rows=>{if(active)setResult({catalog,identity,projectId,items:rows.filter(row=>row.authority==='core'&&row.execution_trust==='trusted_signed_publisher'&&rendererSettingsContract(row.descriptor?.settings_contract)?.scopes.some(scope=>['user','team','project','user_project'].includes(scope)))})}).catch(()=>{if(active)setError('Plugin settings catalog is unavailable.')});return()=>{active=false}},[catalog,identity,projectId,reload])
 return <section className="presentation-editor"><h2>Plugin appearance settings</h2><button onClick={()=>setReload(value=>value+1)}>Reload plugin catalog</button>{error&&<p role="alert">{error}</p>}{current?.items.map(renderer=><RendererSettingsEditor key={JSON.stringify([renderer.package_ref,renderer.application_id,renderer.instance_id])} client={client} projectId={projectId} renderer={renderer}/>)}{current&&!current.items.length&&<p>No enabled plugins declare settings for this project.</p>}</section>
}
export function RendererSettingsEditor({client,projectId,renderer}:{client:RendererSettingsAuthority;projectId:string;renderer:ApplicationRendererDescriptor}){
 const identity=client.identity(),epoch=useRef(0),locked=useRef(false)
 const [loaded,setLoaded]=useState<{client:typeof client;identity:string;projectId:string;renderer:typeof renderer;value:RendererSettingsSnapshot}>(),[scope,setScope]=useState<RendererSettingsScope>('user_project'),[draft,setDraft]=useState<ApplicationState>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0),[needsReload,setNeedsReload]=useState(false)
 const current=loaded?.client===client&&loaded.identity===identity&&loaded.projectId===projectId&&loaded.renderer===renderer?loaded.value:undefined
 useEffect(()=>{const generation=++epoch.current;setLoaded(undefined);setDraft({});setError('');setNeedsReload(false);setBusy(true);locked.current=true
  void client.read(projectId,renderer).then(value=>{if(generation!==epoch.current)return;const selected=value.layers.find(layer=>layer.scope==='user_project')??value.layers[0];setScope(selected?.scope??'user_project');setDraft(selected?.values??{});setLoaded({client,identity,projectId,renderer,value})}).catch(reason=>{if(generation===epoch.current)setError(reason instanceof Error?reason.message:'Settings unavailable.')}).finally(()=>{if(generation===epoch.current){setBusy(false);locked.current=false}})
  return()=>{epoch.current++}
 },[client,identity,projectId,renderer,reload])
 const layer=current?.layers.find(item=>item.scope===scope),dirty=JSON.stringify(draft)!==JSON.stringify(layer?.values??{}),valid=Boolean(current&&validateApplicationState(draft,{...current.contract.values_schema,required:[]}))
 async function save(){if(!current||!layer?.can_write||!valid||locked.current||needsReload)return;const generation=epoch.current;locked.current=true;setBusy(true);setError('');try{const value=await client.replace(projectId,renderer,scope,layer.revision,draft,scope==='team'?current.team_context:undefined);if(generation===epoch.current){setLoaded({client,identity,projectId,renderer,value});setDraft(value.layers.find(item=>item.scope===scope)!.values)}}catch(reason){if(generation===epoch.current){setError(reason instanceof Error?reason.message:'Settings save failed.');setNeedsReload(true)}}finally{if(generation===epoch.current){locked.current=false;setBusy(false)}}}
 return <details className="settings-card presentation-editor renderer-settings-editor"><summary>{renderer.application_id} · {renderer.instance_id}</summary>{error&&<p role="alert">{error}</p>}<button disabled={busy||dirty} onClick={()=>setReload(value=>value+1)}>Reload settings</button>{current&&layer&&<><label>Settings scope<select aria-label="Settings scope" value={scope} disabled={busy||dirty} onChange={event=>{const next=event.target.value as RendererSettingsScope;setScope(next);setDraft(current.layers.find(item=>item.scope===next)!.values)}}>{current.layers.map(item=><option key={item.scope} value={item.scope}>{item.scope==='user'?'My defaults across projects':item.scope==='team'?`Team defaults · ${current.team_context?.team_id}`:item.scope==='project'?'Shared project defaults':'My project overrides'}</option>)}</select></label>{!layer.can_write&&<p>These settings are read-only for your role.</p>}<fieldset disabled={busy||!layer.can_write}><legend>Plugin preferences</legend>{Object.entries(current.contract.values_schema.properties).map(([key,property])=>{const override=Object.hasOwn(draft,key),label=current.contract.labels[key],inherited=current.layers.slice(0,current.layers.findIndex(item=>item.scope===scope)).reduce((values,item)=>({...values,...item.values}),current.contract.defaults)[key],value=override?draft[key]:inherited;return <div key={key}><label><input type="checkbox" checked={override} onChange={event=>setDraft(previous=>{const next={...previous};if(event.target.checked)next[key]=inherited;else delete next[key];return next})}/>{`Override ${label}`}</label><label>{label}<input aria-label={label} disabled={!override} type={property.type==='boolean'?'checkbox':property.type==='number'?'number':'text'} {...(property.type==='boolean'?{checked:Boolean(value)}:{value:String(value??'')})} maxLength={property.maxLength} min={property.minimum} max={property.maximum} step={property.type==='number'?'any':undefined} onChange={event=>setDraft(previous=>({...previous,[key]:property.type==='boolean'?event.target.checked:property.type==='number'&&event.target.value!==''?Number(event.target.value):event.target.value}))}/></label></div>})}<button disabled={!dirty||!valid||needsReload} onClick={()=>void save()}>Save plugin settings</button><button disabled={!dirty} onClick={()=>setDraft({...layer.values})}>Discard changes</button><button onClick={()=>setDraft({})}>Use inherited values</button></fieldset></>}{busy&&!current&&<p role="status">Loading plugin settings…</p>}</details>
}
