import assert from'node:assert/strict'
import test from'node:test'
import React,{StrictMode}from'react'
import{act,create}from'react-test-renderer'
import{MemoryRouter}from'react-router-dom'
import type{CommandCenterClient,CommandCenterSnapshot}from'../../services/contracts'
import{CommandCenterSurface}from'./CommandCenterSurface'
;(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;void React
const snapshot=(name:string):CommandCenterSnapshot=>({generatedAt:'2026-09-07T12:00:00Z',priority:null,priorityStatus:{state:'empty'},attentionItems:[],activeRuns:[],projects:[{projectId:name,status:'active',objective:`${name} objective`}],outcomes:[{id:`${name}-outcome`,projectId:name,title:`${name} outcome`,verified:false,completedAt:'2026-09-07T12:00:00Z'}],unavailableSections:[]})
const deferred=<T,>()=>{let resolve!:(value:T)=>void,reject!:(reason:Error)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}}
const client=(get:()=>Promise<CommandCenterSnapshot>):CommandCenterClient=>({get})
const view=(api:CommandCenterClient|undefined,connected=true,identity:object=api??{})=><MemoryRouter><CommandCenterSurface client={api} connected={connected} identity={identity} projects={[]}/></MemoryRouter>
const markup=(renderer:ReturnType<typeof create>)=>JSON.stringify(renderer.toJSON())

test('a disconnected mounted surface cannot republish a deferred protected snapshot',async()=>{const old=deferred<CommandCenterSnapshot>();const api=client(()=>old.promise);let renderer!:ReturnType<typeof create>;await act(async()=>{renderer=create(view(api));await Promise.resolve()});await act(async()=>{renderer.update(view(undefined,false,{}));await Promise.resolve()});old.resolve(snapshot('Private old project'));await act(async()=>{await old.promise});assert.match(markup(renderer),/Command Center unavailable/);assert.doesNotMatch(markup(renderer),/Private old project|old outcome/)})

test('replacement client success and error both fence the earlier connection',async()=>{for(const oldSettles of['resolve','reject']as const){const old=deferred<CommandCenterSnapshot>(),fresh=deferred<CommandCenterSnapshot>();const a=client(()=>old.promise),b=client(()=>fresh.promise);let renderer!:ReturnType<typeof create>;await act(async()=>{renderer=create(view(a,true,{client:a}));await Promise.resolve()});await act(async()=>{renderer.update(view(b,true,{client:b}));await Promise.resolve()});fresh.resolve(snapshot('Current B'));await act(async()=>{await fresh.promise});assert.match(markup(renderer),/Current B/);if(oldSettles==='resolve')old.resolve(snapshot('Private A'));else old.reject(Error('old credential revoked'));await act(async()=>{await old.promise.catch(()=>undefined)});assert.match(markup(renderer),/Current B/);assert.doesNotMatch(markup(renderer),/Private A|old credential revoked/)}})

test('overlapping refreshes retain only the latest result or error',async()=>{for(const firstSettles of['resolve','reject']as const){const older=deferred<CommandCenterSnapshot>(),newer=deferred<CommandCenterSnapshot>();const queue:Array<Promise<CommandCenterSnapshot>>=[Promise.resolve(snapshot('Initial')),older.promise,newer.promise];const api=client(()=>queue.shift()!);let renderer!:ReturnType<typeof create>;await act(async()=>{renderer=create(view(api));await new Promise(resolve=>setTimeout(resolve,0))});const refreshNode=renderer.root.findAllByType('button').find(node=>node.findAllByType('span').some(label=>label.children.join('')==='Refresh'));assert.ok(refreshNode,markup(renderer));const clickRefresh=refreshNode.props.onClick;await act(async()=>{void clickRefresh();void clickRefresh();await Promise.resolve()});newer.resolve(snapshot('Latest'));await act(async()=>{await newer.promise});if(firstSettles==='resolve')older.resolve(snapshot('Older'));else older.reject(Error('older refresh failed'));await act(async()=>{await older.promise.catch(()=>undefined)});assert.match(markup(renderer),/Latest/);assert.doesNotMatch(markup(renderer),/Older|older refresh failed/)}})

test('StrictMode replay and unmount do not publish stale work or disable a reopened surface',async()=>{const stale=deferred<CommandCenterSnapshot>();const api=client(()=>stale.promise);let renderer!:ReturnType<typeof create>;await act(async()=>{renderer=create(<StrictMode>{view(api)}</StrictMode>);await Promise.resolve()});await act(async()=>{renderer.unmount()});stale.resolve(snapshot('Unmounted private'));await act(async()=>{await stale.promise});await act(async()=>{renderer=create(<StrictMode>{view(client(async()=>snapshot('Reopened')))}</StrictMode>);await Promise.resolve()});assert.match(markup(renderer),/Reopened/);assert.doesNotMatch(markup(renderer),/Unmounted private|Loading authoritative/)})

test('render-time client replacement hides a ready old snapshot before effects run',async()=>{const a=client(async()=>snapshot('Visible A')),pending=deferred<CommandCenterSnapshot>(),b=client(()=>pending.promise),sameIdentity={connection:'same wrapper'};let renderer!:ReturnType<typeof create>;await act(async()=>{renderer=create(view(a,true,sameIdentity));await new Promise(resolve=>setTimeout(resolve,0))});assert.match(markup(renderer),/Visible A/);await act(async()=>{renderer.update(view(b,true,sameIdentity));await Promise.resolve()});assert.match(markup(renderer),/Loading authoritative Command Center/);assert.doesNotMatch(markup(renderer),/Visible A/);await act(async()=>{renderer.unmount()});pending.resolve(snapshot('Never mounted'));await pending.promise})
