import {ManagerMessageDispatch} from './ManagerMessageDispatch'
import React,{useCallback,useEffect,useRef,useState} from 'react'
import type {ManagerConversation,ManagerConversationsAuthority,ManagerConversationView} from '../../services/managerConversations'
void React
export function ManagerConversationsPanel({client,identity,projectIds,name,selection,conversationDrafts,onBusy}:{onBusy?:(value:boolean)=>void;selection?:{id:string;onChange:(id:string)=>void};conversationDrafts?:Map<string,string>;client:ManagerConversationsAuthority;identity:unknown;projectIds:string[];name:(id:string)=>string}){
 const [state,setState]=useState<{client:typeof client;identity:unknown;items:ManagerConversation[]}>(),[active,setActive]=useState(''),[title,setTitle]=useState(client.fixedProject?'New conversation':'Manager conversation'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[threadBusy,setThreadBusy]=useState(false)
 const epoch=useRef(0),locked=useRef(false),drafts=useRef(new Map<string,string>())
 if(conversationDrafts)drafts.current=conversationDrafts
 useEffect(()=>{onBusy?.(busy||threadBusy);return()=>onBusy?.(false)},[busy,threadBusy,onBusy])
 const binding=useRef({client,identity})
 const current=state?.client===client&&state.identity===identity?state:undefined
 useEffect(()=>{const generation=++epoch.current;setState(undefined);setActive('');setError('');setBusy(true);locked.current=true;if(binding.current.client!==client||binding.current.identity!==identity){drafts.current.clear();setTitle(client.fixedProject?'New conversation':'Manager conversation');binding.current={client,identity}}void client.list().then(items=>{if(generation===epoch.current)setState({client,identity,items})}).catch(()=>{if(generation===epoch.current)setError('Saved conversations could not be loaded.')}).finally(()=>{if(generation===epoch.current){setBusy(false);locked.current=false}});return()=>{epoch.current++}},[client,identity,reload])
 useEffect(()=>{if(selection)setActive(current?.items.some(item=>item.conversation_id===selection.id)?selection.id:'')},[selection?.id,current])
 function choose(id:string){setActive(id);selection?.onChange(id)}
 async function create(){if(locked.current||!current||!projectIds.length)return;const generation=epoch.current;locked.current=true;setBusy(true);setError('');try{const value=await client.create(title,projectIds);if(generation===epoch.current){setState({...current,items:[value,...current.items.filter(item=>item.conversation_id!==value.conversation_id)]});choose(value.conversation_id)}}catch(reason){if(generation===epoch.current)setError(reason instanceof Error?reason.message:'Conversation could not be created.')}finally{if(generation===epoch.current){setBusy(false);locked.current=false}}}
 return <section className="manager-conversations" aria-label={client.fixedProject?"Project conversations":"Manager conversations"}>
  <header className="manager-conversation-heading"><div><h3>Conversations</h3><p>{client.childTasks?'Save a message, then dispatch it to a Project when you’re ready.':'No agent is connected. Messages are private; saving does not start work.'}</p></div><button disabled={busy||threadBusy} onClick={()=>setReload(value=>value+1)}>Reload conversations</button></header>
  {error&&<p role="alert">{error}</p>}
  {current&&<div className="manager-conversation-layout">
   <aside className="manager-conversation-list" aria-label="Saved conversations">
    <ul>{current.items.map(item=><li key={item.conversation_id}><button disabled={busy||threadBusy} aria-pressed={active===item.conversation_id} onClick={()=>choose(item.conversation_id)}>{item.title||'Untitled conversation'}</button></li>)}</ul>
    {!current.items.length&&<p>No saved conversations.</p>}
   </aside>
   <div className="manager-conversation-content">
    <div className="manager-conversation-create"><label>Conversation title<input value={title} maxLength={1000} disabled={busy} onChange={event=>setTitle(event.target.value)}/></label><button disabled={busy||threadBusy||!projectIds.length} onClick={()=>void create()}>{client.fixedProject?'New conversation':'New conversation with selected Projects'}</button></div>
    {!projectIds.length&&<p className="manager-conversation-hint">Choose Projects above to start a conversation.</p>}
    {active?<ManagerConversationThread key={active} client={client} identity={identity} id={active} projectIds={projectIds} name={name} drafts={drafts.current} onBusy={setThreadBusy}/>:<div className="manager-conversation-empty"><h4>Your work starts with a conversation</h4><p>Open a saved conversation or start one with the selected Projects.</p></div>}
   </div>
  </div>}
 </section>
}
function ManagerConversationThread({client,identity,id,projectIds,name,drafts,onBusy}:{onBusy:(value:boolean)=>void;client:ManagerConversationsAuthority;identity:unknown;id:string;projectIds:string[];name:(id:string)=>string;drafts:Map<string,string>}){
 const [state,setState]=useState<{client:typeof client;identity:unknown;value:ManagerConversationView}>(),[text,setText]=useState(drafts.get(id)??''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[reload,setReload]=useState(0)
 const epoch=useRef(0),locked=useRef(false)
 const dispatchBusy=useCallback((value:boolean)=>{locked.current=value;setBusy(value);onBusy(value);if(value)epoch.current++},[onBusy])
 const current=state?.client===client&&state.identity===identity?state.value:undefined
 useEffect(()=>{let stopped=false,pending=false;setState(undefined);setError('');const refresh=async()=>{if(locked.current||pending)return;pending=true;const generation=++epoch.current;try{const value=await client.open(id);if(!stopped&&generation===epoch.current){setState({client,identity,value});setError('')}}catch(reason){if(!stopped&&generation===epoch.current){setState(undefined);setError(reason instanceof Error?reason.message:'Conversation could not be loaded.')}}finally{pending=false}};void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>{stopped=true;clearInterval(timer);epoch.current++;onBusy(false)}},[client,identity,id,reload])
 async function mutate(kind:'message'|'scope'){if(!current||locked.current)return;const generation=++epoch.current;locked.current=true;setBusy(true);onBusy(true);setError('');setNotice('');const submitted=text;try{if(kind==='message'){await client.append(current.conversation,submitted);if(generation!==epoch.current)return;drafts.delete(id);setText('');setNotice('Message saved. No provider execution was started.')}else await client.scope(current.conversation,projectIds);if(generation!==epoch.current)return;const value=await client.open(id);if(generation===epoch.current)setState({client,identity,value})}catch(reason){if(generation===epoch.current){setState(undefined);setError(reason instanceof Error?reason.message:'Conversation changed. Reload before retrying.')}}finally{if(generation===epoch.current){setBusy(false);locked.current=false;onBusy(false)}}}
 return <section aria-label="Open manager conversation">{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={busy} onClick={()=>setReload(value=>value+1)}>Reload conversation</button>{current?<><h4>{current.conversation.title}</h4><p>Conversation scope: {current.conversation.scope.project_ids.map(name).join(', ')}</p>{!client.fixedProject&&!current.conversation.project_id&&<button disabled={busy||!projectIds.length||JSON.stringify(projectIds)===JSON.stringify(current.conversation.scope.project_ids)} onClick={()=>void mutate('scope')}>Apply selected Projects to future messages</button>}<ol>{current.messages.map(message=><li key={message.message_id}><p>{message.content}</p><small>Saved · Scope {message.payload.manager_scope.revision}: {message.payload.manager_scope.project_ids.map(name).join(', ')}</small>{client.childTasks&&client.dispatch&&client.dispatches&&client.taskOptions&&<ManagerMessageDispatch client={client} identity={identity} conversation={current.conversation} message={message} name={name} disabled={busy} onBusy={dispatchBusy}/>}</li>)}</ol></>:!error&&<p role="status">Loading conversation…</p>}<label>Your message<textarea rows={5} maxLength={20000} value={text} disabled={busy} onChange={event=>{setText(event.target.value);drafts.set(id,event.target.value)}}/></label><button disabled={busy||!current||!text.trim()} onClick={()=>void mutate('message')}>Save message</button></section>
}
