import React,{useEffect,useRef,useState} from 'react'
import type {ManagerContext,ManagerContextAuthority} from '../../services/managerContext'
import type {DirectoryProject,ProjectDirectoryClient} from '../../services/projectDirectory'
void React
export function ManagerScopePanel({client,directory,identity}:{client:ManagerContextAuthority;directory:Pick<ProjectDirectoryClient,'list'>;identity:unknown}){
 const [scope,setScope]=useState<{client:ManagerContextAuthority;directory:typeof directory;identity:unknown;projects:DirectoryProject[];selected:string[]}>(),[preview,setPreview]=useState<ManagerContext>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0)
 const epoch=useRef(0)
 const current=scope?.client===client&&scope?.directory===directory&&scope?.identity===identity?scope:undefined
 useEffect(()=>{const generation=++epoch.current;setScope(undefined);setPreview(undefined);setError('');setBusy(true)
  void directory.list().then(projects=>{if(generation===epoch.current)setScope({client,directory,identity,projects,selected:[]})}).catch(()=>{if(generation===epoch.current)setError('Your Projects could not be loaded.')}).finally(()=>{if(generation===epoch.current)setBusy(false)})
  return()=>{epoch.current++}
 },[client,directory,identity,reload])
 function toggle(id:string,checked:boolean){if(!current)return;epoch.current++;setPreview(undefined);setError('');setBusy(false);setScope({...current,selected:checked?[...current.selected,id]:current.selected.filter(value=>value!==id)})}
 async function inspect(){if(!current||busy||!current.selected.length)return;const generation=++epoch.current;setPreview(undefined);setError('');setBusy(true);try{const value=await client.preview(current.selected);if(generation===epoch.current)setPreview(value)}catch(reason){if(generation===epoch.current)setError(reason instanceof Error?reason.message:'Context could not be loaded.')}finally{if(generation===epoch.current)setBusy(false)}}
 const name=(id:string)=>current?.projects.find(project=>project.id===id)?.name??id
 return <section className="cc-panel manager-scope" aria-labelledby="manager-scope-title"><h2 id="manager-scope-title">Manager context</h2><p>Choose the Projects to include. Manager conversation is not connected yet; you can inspect its context here.</p>{current?<fieldset><legend>Included Projects ({current.selected.length}/32)</legend>{current.projects.map(project=><label key={project.id}><input type="checkbox" checked={current.selected.includes(project.id)} disabled={!current.selected.includes(project.id)&&current.selected.length>=32} onChange={event=>toggle(project.id,event.target.checked)}/>{project.name}</label>)}{!current.projects.length&&<p>You have no current Project memberships.</p>}</fieldset>:<p role="status">{busy?'Loading Projects…':'Project selection unavailable.'}</p>}<button disabled={busy||!current?.selected.length} onClick={()=>void inspect()}>Preview context</button><button disabled={busy} onClick={()=>setReload(value=>value+1)}>Reload Projects</button>{current&&busy&&<p role="status">Loading selected context…</p>}{error&&<p role="alert">{error}</p>}{current&&preview&&<div aria-label="Selected manager context"><p>Snapshot: <time dateTime={preview.generated_at}>{preview.generated_at}</time></p><p>No tasks have been started.</p>{Object.values(preview.truncated).some(Boolean)&&<p role="status">This preview is partial: {Object.entries(preview.truncated).filter(([,flag])=>flag).map(([key])=>key.replaceAll('_',' ')).join(', ')} reached the response limit.</p>}<ul>{preview.projects.map(project=><li key={project.project_id}><strong>{name(project.project_id)}</strong><p>{project.objective??'No objective recorded.'}</p><p>{project.next_action??'No next action recorded.'}</p></li>)}</ul><details><summary>Active tasks ({preview.active_runs.length})</summary><ul>{preview.active_runs.map(run=><li key={run.run_id}>{name(run.project_id)}: {run.task??'Task'} · {run.status??'Unknown status'}</li>)}</ul></details><details><summary>Recent outcomes ({preview.outcomes.length})</summary><ul>{preview.outcomes.map((outcome,index)=><li key={index}>{name(outcome.project_id)}: {outcome.title??'Outcome'} · {outcome.verified?'Verified':'Unverified'}</li>)}</ul></details><details><summary>Needs attention ({preview.attention_items.length})</summary><ul>{preview.attention_items.map((item,index)=><li key={index}>{name(item.project_id)}: {item.title??'Action needed'} {item.requested_action}</li>)}</ul></details></div>}</section>
}
