import {TaskResultPanel} from '../runs/TaskResultPanel'
import React,{useEffect,useMemo,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import type {ManagerConversation,ManagerMessage,ManagerConversationsAuthority,ManagerChildTask} from '../../services/managerConversations'
import type {JourneySnapshot,NativeAdapterId} from '../onboarding/ConnectedJourneySurface'
void React
export function ManagerMessageDispatch({client,identity,conversation,message,name,disabled,onBusy}:{client:ManagerConversationsAuthority;identity:unknown;conversation:ManagerConversation;message:ManagerMessage;name:(id:string)=>string;disabled:boolean;onBusy:(value:boolean)=>void}){
 const [opened,setOpened]=useState(false),[project,setProject]=useState(''),[source,setSource]=useState(''),[adapter,setAdapter]=useState<NativeAdapterId|''>(''),[options,setOptions]=useState<JourneySnapshot>(),[tasks,setTasks]=useState<ManagerChildTask[]>(),[error,setError]=useState(''),[pending,setPending]=useState(false),[reload,setReload]=useState(0)
 const generation=useRef(0),locked=useRef(false)
 const matching=JSON.stringify(message.payload.manager_scope)===JSON.stringify(conversation.scope)
 useEffect(()=>{if(!opened)return;let stopped=false,reading=false;setTasks(undefined);setError('');const refresh=async()=>{if(stopped||reading||locked.current)return;reading=true;const current=++generation.current;try{const items=await client.dispatches!(conversation.conversation_id,message.message_id);if(items.some(item=>!message.payload.manager_scope.project_ids.includes(item.project_id)))throw Error('Task scope mismatch');if(!stopped&&current===generation.current){setTasks(items);setError('')}}catch{if(!stopped&&current===generation.current){setTasks(undefined);setError('Task status unavailable. Reload before dispatching.')}}finally{reading=false}};void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>{stopped=true;clearInterval(timer);generation.current++}},[client,identity,conversation.conversation_id,message.message_id,opened,reload])
 useEffect(()=>{let stopped=false;setOptions(undefined);setSource('');setAdapter('');if(project&&opened)void client.taskOptions!(project).then(value=>{if(!stopped)setOptions(value)}).catch(()=>{if(!stopped)setError('Sources and agent readiness are unavailable.')});return()=>{stopped=true}},[client,identity,project,opened])
 useEffect(()=>()=>{if(locked.current)onBusy(false)},[onBusy])
 const sources=options?.sources??[],agents=options?.nativeAdapters?.filter(item=>item.sourceId===source&&item.ready)??[]
 const ids=[...new Set(agents.map(item=>item.adapterId))]
 const existing=tasks?.find(item=>item.project_id===project)
 const allowed=matching&&conversation.scope.project_ids.includes(project)&&sources.some(item=>item.sourceId===source)&&ids.includes(adapter as NativeAdapterId)&&tasks!==undefined&&!existing?.run_id
 async function dispatch(){if(!allowed||locked.current||disabled)return;const epoch=++generation.current;locked.current=true;setPending(true);onBusy(true);setError('');try{const task=await client.dispatch!(conversation,message.message_id,project,source,adapter as NativeAdapterId);if(epoch===generation.current)setTasks(previous=>[...(previous??[]).filter(item=>item.project_id!==project),task])}catch{if(epoch===generation.current)setError('Task admission could not be confirmed. Reload status, then retry the same selection.')}finally{if(epoch===generation.current){locked.current=false;setPending(false);onBusy(false)}}}
 return <details open={opened} onToggle={event=>{if(locked.current){event.currentTarget.open=true;return}setOpened(event.currentTarget.open)}}><summary>Run as a project task</summary>{opened&&<><p>Send this saved message to one project. Other conversation messages and the multi-project preview are not sent.</p>{error&&<p role="alert">{error}</p>}<button disabled={disabled||pending} onClick={()=>setReload(value=>value+1)}>Reload child tasks</button>{tasks?.map(task=><React.Fragment key={task.project_id}><p>{name(task.project_id)} · {task.status} {task.run_id&&<Link to={`/project/${encodeURIComponent(task.project_id)}/tasks/${encodeURIComponent(task.run_id)}`}>Open task</Link>}</p>{task.run_id&&task.status==='completed'&&client.childResults&&client.childResult&&<ManagerChildReply client={client} conversationId={conversation.conversation_id} messageId={message.message_id} projectId={task.project_id} runId={task.run_id}/>}</React.Fragment>)}{!matching?<p>This message has an older scope. Save a new message to dispatch with the current scope.</p>:<><label>Task project<select value={project} disabled={disabled||pending} onChange={event=>setProject(event.target.value)}><option value="">Choose a project</option>{conversation.scope.project_ids.map(id=><option key={id} value={id}>{name(id)}</option>)}</select></label>{project&&<><label>Task source<select value={source} disabled={disabled||pending||!options} onChange={event=>{setSource(event.target.value);setAdapter('')}}><option value="">Choose a source</option>{sources.map(item=><option key={item.sourceId} value={item.sourceId}>{item.label}</option>)}</select></label><label>Task agent<select value={adapter} disabled={disabled||pending||!source} onChange={event=>setAdapter(event.target.value as NativeAdapterId)}><option value="">Choose an available agent</option>{ids.map(id=><option key={id} value={id}>{id==='codex-app-server'?'Codex':'Claude Code'}</option>)}</select></label>{source&&!ids.length&&<p>No ready agent is reported for this source.</p>}</>}<button disabled={disabled||pending||!allowed} onClick={()=>void dispatch()}>Dispatch saved message</button></>}</>}</details>
}

function ManagerChildReply({client,conversationId,messageId,projectId,runId}:{client:ManagerConversationsAuthority;conversationId:string;messageId:string;projectId:string;runId:string}){
 const authority=useMemo(()=>({review:(project:string,run:string)=>client.childResult!(conversationId,messageId,project,run)}),[client,conversationId,messageId])
 return <TaskResultPanel authority={authority} projectId={projectId} runId={runId}/>
}
