import React,{useEffect,useRef,useState}from'react'
import{Link,useSearchParams}from'react-router-dom'
import{useStore}from'../../data/store'
import type{CommandCenterClient,CommandCenterRun,ExternalOperationSession,OperationRunDetail,OperationsSessionClient}from'../../services/contracts'
import{Button}from'../../ui/Button'

void React
type State={kind:'loading'}|{kind:'error';reason:string}|{kind:'ready';asOf:string;runs:CommandCenterRun[];sessions:ExternalOperationSession[];sessionsError?:string;selectedRun?:OperationRunDetail}
const authorityLabel:Record<ExternalOperationSession['authorityMode'],string>={opensaddle_managed:'Managed',hybrid:'Cooperative',source_managed:'Observed'}
const time=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?'Unavailable':date.toLocaleString([],{dateStyle:'medium',timeStyle:'short'})}
function ready(projectId:string,center:Awaited<ReturnType<CommandCenterClient['get']>>,sessions:ExternalOperationSession[],selectedRun?:OperationRunDetail,sessionsError?:string):State{if(selectedRun&&selectedRun.projectId!==projectId)throw Error('Operations Run Project identity mismatch');const byId=new Map<string,CommandCenterRun>();for(const run of center.activeRuns)if(run.projectId===projectId)byId.set(run.runId,run);for(const outcome of center.outcomes)if(outcome.projectId===projectId&&outcome.runId&&!byId.has(outcome.runId))byId.set(outcome.runId,{runId:outcome.runId,projectId:outcome.projectId,task:outcome.title,status:'completed',updatedAt:outcome.completedAt});return{kind:'ready',asOf:center.generatedAt,runs:[...byId.values()],sessions,selectedRun,sessionsError}}

export function OperationsSurface({projectId,selectedSessionId,selectedRunId='',commandCenter,sessionsClient}:{projectId:string;selectedSessionId:string;selectedRunId?:string;commandCenter?:CommandCenterClient;sessionsClient?:OperationsSessionClient}){
  const[state,setState]=useState<State>({kind:'loading'})
  const generation=useRef(0)
  const load=async()=>{const current=++generation.current;setState({kind:'loading'});if(!projectId||!commandCenter||!sessionsClient){if(current===generation.current)setState({kind:'error',reason:'The connected control plane does not expose the required operations sources.'});return}const[centerResult,sessionsResult,runResult]=await Promise.allSettled([commandCenter.get(),sessionsClient.sessions(projectId),selectedRunId?sessionsClient.run(selectedRunId):Promise.resolve(undefined)]);if(current!==generation.current)return;if(centerResult.status==='rejected'){const reason=centerResult.reason;setState({kind:'error',reason:reason instanceof Error?reason.message:String(reason)});return}if(runResult.status==='rejected'){const reason=runResult.reason;setState({kind:'error',reason:reason instanceof Error?reason.message:String(reason)});return}const sessionsError=sessionsResult.status==='rejected'?(sessionsResult.reason instanceof Error?sessionsResult.reason.message:String(sessionsResult.reason)):undefined;try{setState(ready(projectId,centerResult.value,sessionsResult.status==='fulfilled'?sessionsResult.value:[],runResult.value,sessionsError))}catch(reason){setState({kind:'error',reason:reason instanceof Error?reason.message:String(reason)})}}
  useEffect(()=>{void load();return()=>{generation.current++}},[commandCenter,projectId,selectedRunId,sessionsClient]) // eslint-disable-line react-hooks/exhaustive-deps
  if(state.kind==='loading')return <main className="content-page cc-page" aria-busy="true"><p role="status">Loading authorized operations…</p></main>
  if(state.kind==='error')return <main className="content-page cc-page"><section className="cc-unavailable" role="alert"><div><h1>Operations unavailable</h1></div><p>{state.reason}</p><Button onClick={()=>void load()}>Retry</Button></section></main>
  const selected=state.sessions.find(session=>session.sessionId===selectedSessionId)
  return <main className="content-page cc-page"><header className="cc-header"><div><span className="eyebrow">Project operations</span><h1>Sessions and Runs</h1><p>Server-managed work and explicitly observed external sessions, kept in their original authority modes.</p></div><div className="cc-freshness"><span>Command Center source</span><time dateTime={state.asOf}>{time(state.asOf)}</time><Button size="sm" variant="secondary" onClick={()=>void load()}>Refresh</Button></div></header>
    {state.sessionsError&&<section className="cc-unavailable" role="status"><div><span className="eyebrow">Partial source coverage</span><h2>External sessions unavailable</h2></div><p>The authoritative Run snapshot loaded with its stated freshness. The external-session registry could not be read: {state.sessionsError}</p></section>}
    <div className="cc-grid"><section className="cc-panel"><div className="cc-section-heading"><div><span className="eyebrow">Managed by OpenSaddle</span><h2>Runs</h2></div><strong className="cc-count">{state.runs.length}</strong></div>{state.runs.length?<div className="cc-stack">{state.runs.map(run=><article className="cc-row" key={run.runId}><div className="cc-row-top"><Link to={`/operations?${new URLSearchParams({project:projectId,run:run.runId})}`}><strong>{run.task??'Managed Run'}</strong></Link><span className={`cc-status cc-status--${run.status}`}>{run.status.replaceAll('_',' ')}</span></div><div className="cc-row-meta"><code>{run.runId}</code><span>Source: Core Run projection</span><time dateTime={run.updatedAt}>{run.updatedAt?time(run.updatedAt):'Freshness unavailable'}</time></div></article>)}</div>:<p className="cc-section-empty">No Run identities for this Project were returned by the current Command Center snapshot.</p>}</section>
      <section className="cc-panel"><div className="cc-section-heading"><div><span className="eyebrow">Registered external records</span><h2>Sessions</h2></div><strong className="cc-count">{state.sessionsError?'—':state.sessions.length}</strong></div>{state.sessionsError?<p className="cc-section-empty">Session count unavailable because the registry source could not be read.</p>:state.sessions.length?<div className="cc-stack">{state.sessions.map(session=><Link className="cc-row" key={session.sessionId} to={`/operations?${new URLSearchParams({project:projectId,session:session.sessionId})}`}><div className="cc-row-top"><strong>{session.harness.replaceAll('_',' ')}</strong><span className="cc-kind">{authorityLabel[session.authorityMode]}</span></div><div className="cc-row-meta"><code>{session.sessionId}</code><span>Source: Core external-session registry</span><time dateTime={session.updatedAt}>{time(session.updatedAt)}</time></div>{session.linkedRunId&&<p>Exact linked Run <code>{session.linkedRunId}</code>.</p>}</Link>)}</div>:<p className="cc-section-empty">No explicitly registered external sessions were returned for this Project.</p>}</section></div>
    {selectedRunId&&state.selectedRun&&<section className="cc-panel" aria-labelledby="operation-run-detail"><span className="eyebrow">Authoritative Core record</span><h2 id="operation-run-detail">Run evidence</h2><dl><dt>Run</dt><dd><code>{state.selectedRun.runId}</code></dd><dt>Source</dt><dd><code>{state.selectedRun.sourceRef}</code></dd><dt>Requested by</dt><dd><code>{state.selectedRun.requestedBy}</code></dd><dt>Status</dt><dd>{state.selectedRun.status}</dd><dt>Cancellation requested</dt><dd>{state.selectedRun.cancellationRequested?'Yes':'No'}</dd><dt>Assigned worker</dt><dd>{state.selectedRun.assignedWorkerId?<code>{state.selectedRun.assignedWorkerId}</code>:'Unavailable'}</dd><dt>Lease epoch</dt><dd>{state.selectedRun.leaseEpoch}</dd><dt>Lease expires</dt><dd>{state.selectedRun.leaseExpiresAt?<time dateTime={state.selectedRun.leaseExpiresAt}>{time(state.selectedRun.leaseExpiresAt)}</time>:'Unavailable'}</dd><dt>Policy</dt><dd><code>{JSON.stringify(state.selectedRun.policy)}</code></dd><dt>Created</dt><dd><time dateTime={state.selectedRun.createdAt}>{time(state.selectedRun.createdAt)}</time></dd><dt>As of</dt><dd><time dateTime={state.selectedRun.updatedAt}>{time(state.selectedRun.updatedAt)}</time></dd></dl></section>}
    {selectedSessionId&&(selected?<section className="cc-panel" aria-labelledby="operation-session-detail"><span className="eyebrow">Selected authorized record</span><h2 id="operation-session-detail">Session evidence</h2><dl><dt>Session</dt><dd><code>{selected.sessionId}</code></dd><dt>External identity</dt><dd><code>{selected.externalSessionId}</code></dd><dt>Authority</dt><dd>{authorityLabel[selected.authorityMode]} · <code>{selected.authorityMode}</code></dd><dt>Harness</dt><dd>{selected.harness}</dd><dt>Transcript locator</dt><dd><code>{selected.transcriptLocator}</code></dd><dt>Workspace locator</dt><dd>{selected.workspaceLocator?<code>{selected.workspaceLocator}</code>:'Unavailable'}</dd><dt>Checkpoint</dt><dd>{selected.checkpointDigest?<code>{selected.checkpointDigest}</code>:'Unavailable'}</dd><dt>Authority digest</dt><dd><code>{selected.authorityHash}</code></dd><dt>Source capabilities</dt><dd>{Object.entries(selected.sourceCapabilities).map(([key,value])=>`${key}: ${value?'observed':'unavailable'}`).join(', ')||'Unavailable'}</dd><dt>As of</dt><dd><time dateTime={selected.updatedAt}>{time(selected.updatedAt)}</time></dd></dl>{selected.linkedRunId&&<Link className="cc-text-link" to={`/runs?run=${encodeURIComponent(selected.linkedRunId)}`}>Open exact linked Run evidence</Link>}</section>:<section className="cc-unavailable" role="alert"><div><h2>Session evidence unavailable</h2></div><p>The selected session is absent from the refreshed authorized Project list. Cached details were cleared.</p></section>)}
    <div className="cc-grid"><section className="cc-unavailable"><div><span className="eyebrow">Fleet</span><h2>Worker status unavailable</h2></div><p>Core does not expose a permission-scoped worker read projection in this server version. Online, offline, trust, capacity, leases, drain, and revoke state are unknown.</p></section><section className="cc-unavailable"><div><span className="eyebrow">Usage</span><h2>Usage and quota unavailable</h2></div><p>These sources report neither measured usage nor an estimate or quota reset window. No zero balance, cost, or remaining quota is inferred.</p></section></div>
    <section className="cc-unavailable"><div><span className="eyebrow">Controls and health</span><h2>Additional operations unavailable</h2></div><p>Worker controls, checkpoint lineage, account quota, and connector health need authoritative read and action contracts. This view sends no drain, revoke, schedule, or connection mutation.</p></section>
  </main>
}

export function OperationsPage(){const{services}=useStore();const[params]=useSearchParams();const requested=params.get('project')??'';const[discovered,setDiscovered]=useState('');useEffect(()=>{let active=true;if(requested){setDiscovered('');return()=>{active=false}}setDiscovered('');void services?.commandCenter?.get().then(snapshot=>{if(!active)return;const ids=[...new Set(snapshot.projects.map(project=>project.projectId))];setDiscovered(ids.length===1?ids[0]:'')}).catch(()=>undefined);return()=>{active=false}},[requested,services?.commandCenter]);const projectId=requested||discovered;return <OperationsSurface projectId={projectId} selectedSessionId={params.get('session')??''} selectedRunId={params.get('run')??''} commandCenter={services?.commandCenter} sessionsClient={services?.operationsSessions}/>}
