import assert from'node:assert/strict'
import test from'node:test'
import React from'react'
import{act,create,type ReactTestRenderer}from'react-test-renderer'
import{MemoryRouter}from'react-router-dom'
import type{CommandCenterClient,CommandCenterSnapshot,ExternalOperationSession,OperationsSessionClient}from'../../services/contracts'
import{OperationsSurface}from'./OperationsPage'

;(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true
void React
const snapshot=(project='P1'):CommandCenterSnapshot=>({generatedAt:'2026-09-07T15:00:00Z',priority:null,priorityStatus:{state:'empty'},attentionItems:[],activeRuns:[{runId:'run_same',projectId:project,task:'Active work',status:'running',updatedAt:'2026-09-07T14:59:00Z'}],projects:[],outcomes:[{id:'out_1',projectId:project,runId:'run_same',title:'Duplicate outcome',verified:true,completedAt:'2026-09-07T14:58:00Z'},{id:'out_2',projectId:project,runId:'run_done',title:'Done work',verified:false,completedAt:'2026-09-07T14:57:00Z'}],unavailableSections:[]})
const session=(id='ses_1',mode:ExternalOperationSession['authorityMode']='source_managed'):ExternalOperationSession=>({sessionId:id,projectId:'P1',harness:'codex',externalSessionId:`native_${id}`,transcriptLocator:`codex://session/${id}`,workspaceLocator:'/workspace/P1',authorityMode:mode,sourceCapabilities:{metadata:true,usage:false},authorityHash:'a'.repeat(64),linkedRunId:'run_same',createdAt:'2026-09-07T14:00:00Z',updatedAt:'2026-09-07T14:30:00Z'})
const view=(project:string,center:CommandCenterClient,sessions:OperationsSessionClient,selected='')=><MemoryRouter><OperationsSurface projectId={project} selectedSessionId={selected} commandCenter={center} sessionsClient={sessions}/></MemoryRouter>
async function mount(center:CommandCenterClient,sessions:OperationsSessionClient,selected=''){let renderer!:ReactTestRenderer;await act(async()=>{renderer=create(view('P1',center,sessions,selected));await Promise.resolve()});return renderer}
const button=(renderer:ReactTestRenderer,label:string)=>renderer.root.findAllByType('button').find(node=>node.findAllByProps({className:'os-button__label'}).some(child=>child.children.join('')===label))!

test('mounted operations deduplicates exact Run IDs and keeps managed, cooperative, and observed labels',async()=>{const rows=[session('ses_observed'),session('ses_cooperative','hybrid'),session('ses_managed','opensaddle_managed')];const renderer=await mount({get:async()=>snapshot()},{sessions:async()=>rows});const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Runs.*2.*Active work.*run_same.*Done work.*run_done/s);assert.doesNotMatch(markup,/Duplicate outcome/);assert.match(markup,/Observed.*Cooperative.*Managed/s);assert.match(markup,/Worker status unavailable.*unknown.*Usage and quota unavailable.*No zero balance/s)})

test('route and client revocation clear cached protected rows and selected detail',async()=>{let resolveNew!:(value:CommandCenterSnapshot)=>void;const firstCenter={get:async()=>snapshot('P1')};const firstSessions={sessions:async()=>[session('ses_private')]};let renderer=await mount(firstCenter,firstSessions,'ses_private');assert.match(JSON.stringify(renderer.toJSON()),/native_ses_private/);const nextCenter={get:async()=>new Promise<CommandCenterSnapshot>(resolve=>{resolveNew=resolve})};const deniedSessions={sessions:async()=>{throw Error('project membership revoked')}};await act(async()=>{renderer.update(view('P2',nextCenter,deniedSessions,'ses_private'));await Promise.resolve()});assert.doesNotMatch(JSON.stringify(renderer.toJSON()),/native_ses_private|codex:\/\/session\/ses_private/);await act(async()=>{resolveNew(snapshot('P2'));await Promise.resolve()});const markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Operations unavailable.*project membership revoked/s);assert.doesNotMatch(markup,/native_ses_private/)})

test('manual refresh from an old client cannot restore protected rows after a route change',async()=>{let refreshes=0,resolveOld!:(value:CommandCenterSnapshot)=>void;const oldCenter={get:async()=>{refreshes++;return refreshes===1?snapshot('P1'):new Promise<CommandCenterSnapshot>(resolve=>{resolveOld=resolve})}};const oldSessions={sessions:async()=>[session('ses_private')]};let renderer=await mount(oldCenter,oldSessions,'ses_private');await act(async()=>{button(renderer,'Refresh').props.onClick();await Promise.resolve()});const nextCenter={get:async()=>snapshot('P2')};const nextSessions={sessions:async()=>[]};await act(async()=>{renderer.update(view('P2',nextCenter,nextSessions));await Promise.resolve()});await act(async()=>{resolveOld(snapshot('P1'));await Promise.resolve()});const markup=JSON.stringify(renderer.toJSON());assert.doesNotMatch(markup,/ses_private|native_ses_private/);assert.match(markup,/No explicitly registered external sessions/)})

test('unknown selected session fails closed while exact Run and session evidence links remain inspectable',async()=>{const renderer=await mount({get:async()=>snapshot()},{sessions:async()=>[session()],run:async()=>{throw Error('unused')}},'missing');let markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Session evidence unavailable.*Cached details were cleared/s);const links=renderer.root.findAllByType('a').map(node=>node.props.href);assert.ok(links.includes('/operations?project=P1&run=run_same'));assert.ok(links.includes('/operations?project=P1&run=run_done'));assert.ok(links.includes('/operations?project=P1&session=ses_1'));await act(async()=>{renderer.update(view('P1',{get:async()=>snapshot()},{sessions:async()=>[session()],run:async()=>{throw Error('unused')}},'ses_1'));await Promise.resolve()});markup=JSON.stringify(renderer.toJSON());assert.match(markup,/Session evidence.*native_ses_1.*source_managed.*codex:\/\/session\/ses_1.*usage: unavailable/s)})

test('selected Run loads exact authoritative v2 evidence and rejects cross-Project substitution',async()=>{const exact={runId:'run_same',projectId:'P1',sourceRef:'participant-review',task:'Active work',requestedBy:'owner',status:'running',cancellationRequested:false,leaseEpoch:3,createdAt:'2026-09-07T14:00:00Z',updatedAt:'2026-09-07T15:00:00Z',policy:{mode:'bounded'}};let requested='';let renderer!:ReactTestRenderer;await act(async()=>{renderer=create(<MemoryRouter><OperationsSurface projectId="P1" selectedSessionId="" selectedRunId="run_same" commandCenter={{get:async()=>snapshot()}} sessionsClient={{sessions:async()=>[],run:async id=>{requested=id;return exact}}}/></MemoryRouter>);await Promise.resolve()});assert.equal(requested,'run_same');assert.match(JSON.stringify(renderer.toJSON()),/Run evidence.*participant-review.*owner.*Lease epoch.*3.*bounded/s);await act(async()=>{renderer.update(<MemoryRouter><OperationsSurface projectId="P1" selectedSessionId="" selectedRunId="run_same" commandCenter={{get:async()=>snapshot()}} sessionsClient={{sessions:async()=>[],run:async()=>({...exact,projectId:'P2'})}}/></MemoryRouter>);await Promise.resolve()});assert.match(JSON.stringify(renderer.toJSON()),/Operations unavailable.*Project identity mismatch/s)})
