import React, { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useStore } from '../../data/store'
import type { KrailProposalApproval, KrailProposalClient, OperationProposal } from '../../services/contracts'
import { Button } from '../../ui/Button'
import { EmptyState } from '../../ui/EmptyState'
import { effectBoundsSummary, formatMicrounits, fullEffectBounds, isApprovalCurrent } from './proposalReviewModel'

// Node's mounted renderer uses the classic JSX transform.
void React

type LoadState = { kind: 'loading'; identity: string } | { kind: 'ready'; identity: string; proposal: OperationProposal } | { kind: 'error'; identity: string; reason: string }
type ApprovalState = { identity: string; value: KrailProposalApproval }
function dateTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) }
function approvalFailureTitle(reason: string) { if (/expired/i.test(reason)) return 'Proposal expired'; if (/own KRAIL proposal|approver role|required.*membership/i.test(reason)) return 'Approval is not permitted'; if (/not found|restricted/i.test(reason)) return 'Proposal is unavailable'; return 'Approval could not be recorded' }
function isExpired(proposal: OperationProposal, now: number) { const expiry = new Date(proposal.expiresAt).getTime(); return !Number.isFinite(expiry) || expiry <= now }


// oxlint-disable-next-line react/only-export-components -- mounted identity-fencing tests exercise the public surface.
export function ProposalReviewSurface({ proposalId, client }: { proposalId: string; client?: KrailProposalClient }) {
  const identity = proposalId; const generation = useRef(0); const [retry, setRetry] = useState(0); const [state, setState] = useState<LoadState>({ kind: 'loading', identity: '' }); const [busy, setBusy] = useState(false); const [approval, setApproval] = useState<ApprovalState>(); const [approvalError, setApprovalError] = useState<{ identity: string; reason: string }>(); const [now, setNow] = useState(() => Date.now())
  useEffect(() => {
    const request = ++generation.current; setBusy(false); setApproval(undefined); setApprovalError(undefined)
    if (!proposalId) { setState({ kind: 'error', identity, reason: 'A proposal ID is required.' }); return }
    if (!client) { setState({ kind: 'error', identity, reason: 'This control plane does not advertise governed KRAIL proposal review.' }); return }
    setState({ kind: 'loading', identity })
    void client.get(proposalId).then((proposal) => { if (generation.current === request && proposal.proposalId === proposalId) setState({ kind: 'ready', identity, proposal }) }).catch((error) => { if (generation.current === request) setState({ kind: 'error', identity, reason: error instanceof Error ? error.message : String(error) }) })
  }, [client, identity, proposalId, retry])
  useEffect(() => { if (typeof window === 'undefined') return; const interval = globalThis.setInterval(() => setNow(Date.now()), 1_000); return () => globalThis.clearInterval(interval) }, [])
  const proposal = state.kind === 'ready' && state.identity === identity && state.proposal.proposalId === proposalId ? state.proposal : undefined
  const approvalIdentity = proposal ? `${proposal.proposalId}:${proposal.recordDigest}` : ''
  const currentApproval = approval?.identity === approvalIdentity ? approval.value : undefined
  const expired = proposal ? isExpired(proposal, now) : false; const approvalCurrent = currentApproval ? isApprovalCurrent(currentApproval, now) : false
  const reload = useCallback(() => setRetry((value) => value + 1), [])
  if (!proposal) { if (state.kind === 'error' && state.identity === identity) return <main className="content-page cc-page"><EmptyState role="alert" title="Proposal review unavailable" description={state.reason} action={<Button onClick={reload}>Retry</Button>} secondaryAction={<Link className="cc-text-link" to="/home">Command Center</Link>} /></main>; return <main className="content-page cc-page" aria-busy="true"><p role="status">Loading immutable proposal record…</p></main> }
  const effectBounds = proposal.declaredEffects.map((effect) => fullEffectBounds(effect.bounds)); const boundsReviewable = effectBounds.every((item) => item.reviewable)
  const approve = async () => {
    if (expired || busy || !client || !boundsReviewable) return
    const request = generation.current; setBusy(true); setApprovalError(undefined)
    try { const result = await client.approve(proposal.proposalId, 3_600); if (generation.current !== request) return; if (result.proposalId !== proposal.proposalId || result.recordDigest !== proposal.recordDigest) throw new Error('approval identity does not match the reviewed immutable proposal'); setApproval({ identity: approvalIdentity, value: result }) }
    catch (error) { if (generation.current === request) setApprovalError({ identity: approvalIdentity, reason: error instanceof Error ? error.message : String(error) }) } finally { if (generation.current === request) setBusy(false) }
  }
  const currentError = approvalError?.identity === approvalIdentity ? approvalError.reason : ''
  return <main className="content-page cc-page"><header className="cc-header"><div><span className="eyebrow">Governed human decision</span><h1>Review KRAIL proposal</h1><p>Approval records consent for this immutable proposal. It does not execute the promotion.</p></div><Link className="cc-text-link" to="/home">Command Center</Link></header>
    <section className="cc-unavailable" aria-label="Proposal identity"><div><h2>Immutable identity</h2></div><div><p>Proposal <code>{proposal.proposalId}</code></p><p>Record digest <code>{proposal.recordDigest}</code></p><p>Protected input <code>{proposal.protectedInputDigest}</code></p></div></section>
    <div className="cc-grid"><section className="cc-panel"><span className="eyebrow">Requested change</span><h2>{proposal.registeredActionId}</h2><p>Action version {proposal.registeredActionVersion} · project <code>{proposal.projectId}</code></p><dl><dt>Requested by</dt><dd><code>{proposal.actor}</code></dd><dt>On behalf of</dt><dd>{proposal.delegationChain.length ? proposal.delegationChain.map((item) => <code key={item}>{item} </code>) : 'No delegation chain'}</dd><dt>Created</dt><dd><time dateTime={proposal.createdAt}>{dateTime(proposal.createdAt)}</time></dd><dt>Expires</dt><dd><time dateTime={proposal.expiresAt}>{dateTime(proposal.expiresAt)}</time></dd><dt>Cost</dt><dd>{formatMicrounits(proposal.costEstimate.estimatedMicrounits, proposal.costEstimate.currency)}{proposal.costEstimate.budgetMicrounits === null ? '' : ` of ${formatMicrounits(proposal.costEstimate.budgetMicrounits, proposal.costEstimate.currency)} budget`}</dd></dl><h3>Exact targets ({proposal.targets.length})</h3>{proposal.targets.length ? <ul>{proposal.targets.map((target) => <li key={`${target.resourceType}:${target.resourceId}`}><code>{target.issuer}:{target.resourceType}/{target.resourceId}</code> · resource version <code>{target.resourceVersion}</code> · expected <code>{target.expectedVersion}</code><br />Resource digest <code>{target.digest}</code><br />Source <code>{target.source.origin}/{target.source.sourceId}@{target.source.version}</code> · <code>{target.source.digest}</code></li>)}</ul> : <p>No targets were returned.</p>}<h3>Declared effects</h3><ul>{proposal.declaredEffects.map((effect, index) => <li key={`${effect.effectClass}:${index}`}><strong>{effect.effectClass}</strong><br />{effectBoundsSummary(effect.bounds)}{effectBounds[index]!.reviewable ? <details><summary>Show exact declared bounds</summary><pre>{effectBounds[index]!.text}</pre></details> : <p role="alert">Effect bounds are too large or invalid for safe review. Approval is unavailable.</p>}</li>)}</ul></section>
      <section className="cc-panel"><span className="eyebrow">Policy and review</span><h2>{proposal.policy.outcome}</h2><dl><dt>Policy</dt><dd><code>{proposal.policy.id}@{proposal.policy.version}</code></dd><dt>Policy hash</dt><dd><code>{proposal.policy.hash}</code></dd><dt>Reason</dt><dd>{proposal.policy.reason ?? 'No policy reason returned'}</dd></dl><h3>Required approvals</h3><ul>{proposal.requiredApprovals.map((item) => <li key={`${item.kind}:${item.role}`}>{item.count} {item.kind} · {item.role}</li>)}</ul><h3>Validation</h3><ul>{proposal.validationResults.map((item) => <li key={item.code}>{item.passed ? 'Passed' : 'Failed'} · {item.code}{item.message ? `: ${item.message}` : ''}</li>)}</ul>{proposal.blockers.length > 0 && <><h3>Blockers</h3><ul>{proposal.blockers.map((item) => <li key={item.code}>{item.code}: {item.message}</li>)}</ul></>}</section></div>
    <section className="cc-panel" aria-labelledby="proposal-decision"><span className="eyebrow">Decision</span><h2 id="proposal-decision">Grant approval</h2><p>The approval endpoint is bound to this proposal’s immutable ID. The control plane stores its record digest; no execution request is sent from this page.</p>{!boundsReviewable && <p role="alert">Every declared effect must be fully reviewable before approval can be granted.</p>}{expired && <p role="alert">This proposal has expired. Refresh cannot extend it.</p>}{currentError && <div role="alert"><h3>{approvalFailureTitle(currentError)}</h3><p>{currentError}</p><p>No automatic retry was attempted. Reload the immutable record before deciding again.</p></div>}{currentApproval ? <div role={approvalCurrent ? 'status' : 'alert'}><h3>{approvalCurrent ? 'Approval recorded' : 'Returned approval has expired'}</h3><p>Approval <code>{currentApproval.approvalId}</code> by <code>{currentApproval.approvedBy}</code>, valid until <time dateTime={currentApproval.expiresAt}>{dateTime(currentApproval.expiresAt)}</time>.</p><p>Server-bound record digest <code>{currentApproval.recordDigest}</code></p>{approvalCurrent ? <p>Execution remains a separate, server-governed action.</p> : <p>This replayed approval does not currently authorize execution. The server will recheck approval expiry and membership.</p>}</div> : <Button disabled={busy || expired || !boundsReviewable} onClick={() => void approve()}>{busy ? 'Recording approval…' : 'Grant approval'}</Button>}</section>
  </main>
}
export function ProposalReviewPage() { const { services } = useStore(); const [params] = useSearchParams(); return <ProposalReviewSurface proposalId={params.get('proposal') ?? ''} client={services?.krailProposals} /> }
